import re
import sqlite3

from common import BASE_DIR, DB_PATH, ensure_dirs


def word_count(value):
    if not value:
        return 0
    text = re.sub(r"<[^>]+>", " ", value)
    return len(re.findall(r"\b[\w'-]+\b", text))


def main():
    ensure_dirs()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    checks = [
        ("persons", "name", "bio_html", 700, "biography"),
        ("texts", "title", "analysis_html", 700, "text summary"),
        ("concepts", "label", "definition_long", 900, "dictionary entry"),
    ]
    lines = [
        "# Content Depth Audit",
        "",
        "Generated by `scripts/audit_content_depth.py`. This report distinguishes relationally seeded entries from encyclopedia-ready entries.",
        "",
    ]
    total_gaps = 0
    for table, label_col, prose_col, minimum, kind in checks:
        rows = conn.execute(f"SELECT {label_col} AS label, {prose_col} AS prose, review_status FROM {table} ORDER BY {label_col}").fetchall()
        gaps = [(row["label"], word_count(row["prose"]), row["review_status"]) for row in rows if word_count(row["prose"]) < minimum]
        total_gaps += len(gaps)
        lines.extend([f"## {kind.title()} Gaps", ""])
        lines.append(f"Minimum target for this audit: {minimum} words.")
        lines.append("")
        for label, count, status in gaps:
            lines.append(f"- {label}: {count} words, status {status}")
        lines.append("")

    lines.insert(3, f"Total entries below current depth target: {total_gaps}.")
    (BASE_DIR / "CONTENT_DEPTH_AUDIT.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {BASE_DIR / 'CONTENT_DEPTH_AUDIT.md'}")
    print(f"Depth gaps: {total_gaps}")
    conn.close()


if __name__ == "__main__":
    main()
