import json
import sqlite3

from common import BASE_DIR, DB_PATH, ensure_dirs


def load_counts():
    path = BASE_DIR / "staging" / "corpus_discovery_candidates.json"
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    counts = {}
    for group, items in data.items():
        for item in items:
            counts[item["label"].lower()] = item["count"]
    return counts


def main():
    ensure_dirs()
    counts = load_counts()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    queue = []
    specs = [
        ("persons", "person_id", "name", "bio_html", "biography", 700),
        ("texts", "text_id", "title", "analysis_html", "text summary", 700),
        ("concepts", "slug", "label", "definition_long", "dictionary entry", 900),
    ]
    for table, key_col, label_col, prose_col, kind, minimum in specs:
        for row in conn.execute(f"SELECT {key_col} AS key, {label_col} AS label, {prose_col} AS prose FROM {table}"):
            existing_words = len((row["prose"] or "").split())
            if existing_words >= minimum:
                continue
            mention_count = counts.get(row["label"].lower(), 0)
            score = mention_count * 10 + (minimum - existing_words)
            queue.append({
                "kind": kind,
                "key": row["key"],
                "label": row["label"],
                "mention_count": mention_count,
                "existing_words": existing_words,
                "target_min_words": minimum,
                "priority_score": score,
            })

    queue.sort(key=lambda item: (item["priority_score"], item["mention_count"], item["label"]), reverse=True)
    json_path = BASE_DIR / "staging" / "enrichment_queue.json"
    md_path = BASE_DIR / "ENRICHMENT_QUEUE.md"
    json_path.write_text(json.dumps(queue, indent=2, ensure_ascii=False), encoding="utf-8")

    lines = [
        "# Enrichment Queue",
        "",
        "Generated by `scripts/build_enrichment_queue.py`. Priority combines corpus mention count with missing prose depth. It is a guide for the next encyclopedia-writing passes, not a substitute for scholarly judgment.",
        "",
        "## Top 60",
        "",
    ]
    for item in queue[:60]:
        lines.append(
            f"- {item['label']} ({item['kind']}): mentions {item['mention_count']}, "
            f"words {item['existing_words']}/{item['target_min_words']}, score {item['priority_score']}"
        )
    lines.append("")
    md_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}")
    print(f"Queued entries: {len(queue)}")
    conn.close()


if __name__ == "__main__":
    main()
