import json
import re
from collections import Counter, defaultdict

from common import MARKDOWN_DIR, BASE_DIR, ensure_dirs


CANDIDATES = {
    "scholars": [
        "Richard Kieckhefer", "Claire Fanger", "Frank Klaassen", "Sophie Page",
        "Michael D. Bailey", "Catherine Rider", "Benedek Lang", "Lynn Thorndike",
        "Nicolas Weill-Parot", "Jean-Patrice Boudet", "Julien Veronese",
        "Julien Véronèse", "David Pingree", "Valerie Flint", "Robert Mathiesen",
        "Charles Burnett", "Paola Zambelli", "Don C. Skemer", "Lea T. Olsan",
        "Jan R. Veenstra", "Katelyn Mesler", "Béatrice Delaurenti",
    ],
    "figures": [
        "Johannes Hartlieb", "Ulrich Molitor", "John of Morigny", "Honorius of Thebes",
        "Solomon", "Raziel", "Apollonius of Tyana", "Theysolius", "Michael Scot",
        "Albertus Magnus", "Roger Bacon", "Cecco d'Ascoli", "Thabit ibn Qurra",
        "Thomas Aquinas", "William of Auvergne", "Augustine", "Isidore of Seville",
        "Adelard of Bath", "Hugh of Saint-Victor", "Hugh of St. Victor",
        "Bernard Silvester", "Peter Abelard", "Arnald of Villanova", "Pietro d'Abano",
        "Abu Ma'shar", "al-Kindi", "Nicole Oresme",
    ],
    "texts": [
        "Forbidden Rites", "Unlocked Books", "Magic in Medieval Manuscripts",
        "Hazards of the Dark Arts", "Liber Theysolius", "Ars Notoria",
        "Sworn Book of Honorius", "Liber Juratus", "Liber Razielis",
        "Sefer Raziel", "Picatrix", "De radiis", "De imaginibus",
        "Speculum astronomiae", "Book of Angels", "Munich Manual",
        "Buch aller verbotenen Kunst", "History of Magic and Experimental Science",
        "Secretum Secretorum", "Liber experimentorum", "De occultis operibus naturae",
        "De mineralibus", "Opus Majus", "De universo", "Etymologiae",
    ],
    "concepts": [
        "learned magic", "ritual magic", "natural magic", "astral magic",
        "image magic", "necromancy", "nigromancy", "superstition",
        "familiar spirit", "magic and cognition", "manuscript miscellany",
        "clerical underworld", "angelic invocation", "demonic pact",
        "divination", "geomancy", "chiromancy", "hydromancy", "pyromancy",
        "sortilege", "exorcism", "charms", "amulets", "talismans",
        "suffumigation", "characters", "seals", "notae", "voces magicae",
        "ritual purity", "confession", "witchcraft", "maleficium",
        "experimental science", "occult properties", "celestial influence",
        "scholastic classification", "natural powers", "secret of secrets",
        "prohibited arts", "licit magic", "demonology", "mathematical arts",
    ],
}


def normalize(text):
    return re.sub(r"\s+", " ", text)


def count_candidate(text, phrase):
    pattern = re.compile(r"\b" + re.escape(phrase).replace(r"\ ", r"\s+") + r"\b", re.IGNORECASE)
    return len(pattern.findall(text))


def main():
    ensure_dirs()
    markdown_files = sorted(MARKDOWN_DIR.glob("*.md"))
    totals = {group: Counter() for group in CANDIDATES}
    sources = {group: defaultdict(list) for group in CANDIDATES}

    for path in markdown_files:
        text = normalize(path.read_text(encoding="utf-8", errors="replace"))
        for group, phrases in CANDIDATES.items():
            for phrase in phrases:
                count = count_candidate(text, phrase)
                if count:
                    totals[group][phrase] += count
                    sources[group][phrase].append({"file": str(path), "count": count})

    report = {}
    for group in CANDIDATES:
        report[group] = [
            {
                "label": label,
                "count": count,
                "source_count": len(sources[group][label]),
                "sources": sorted(sources[group][label], key=lambda x: x["count"], reverse=True)[:8],
            }
            for label, count in totals[group].most_common()
        ]

    staging_path = BASE_DIR / "staging" / "corpus_discovery_candidates.json"
    docs_path = BASE_DIR / "CORPUS_DISCOVERY.md"
    staging_path.parent.mkdir(parents=True, exist_ok=True)
    docs_path.parent.mkdir(parents=True, exist_ok=True)
    staging_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    lines = [
        "# Corpus Discovery Report",
        "",
        "This report is generated by `scripts/discover_corpus_candidates.py` from the Markdown corpus. Counts are lexical signals, not final scholarly judgments; they identify candidates for biographies, dictionary entries, text summaries, and relationship links.",
        "",
    ]
    for group in ("scholars", "figures", "texts", "concepts"):
        lines.append(f"## {group.title()}")
        lines.append("")
        for item in report[group][:40]:
            lines.append(f"- {item['label']}: {item['count']} mentions across {item['source_count']} Markdown files")
        lines.append("")
    docs_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Markdown files scanned: {len(markdown_files)}")
    print(f"Wrote {staging_path}")
    print(f"Wrote {docs_path}")


if __name__ == "__main__":
    main()
