"""
Enrich batch 8: remaining texts and persons.
"""
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import DB_PATH


CONCEPT_ENRICHMENTS = {}


PERSON_ENRICHMENTS = {

"julien_veronese": """<h2>Life and Scholarship</h2>
<p>Julien Véronèse is a French historian of medieval magic at the Université Paris 1 Panthéon-Sorbonne whose critical edition of the <em>Ars notoria</em> tradition — <em>L'Ars notoria au Moyen Âge: Introduction et édition critique</em> (Sismel/Edizioni del Galluzzo, 2007) — is the definitive scholarly treatment of the most widely circulated system of medieval angel magic. Véronèse's work combines rigorous manuscript philology with attention to the liturgical and theological contexts within which the Ars Notoria operated.</p>

<h2>Ars Notoria Edition</h2>
<p>The critical edition documents the manuscript tradition of the Ars Notoria in its two principal recensions (the shorter <em>Ars notoria brevis</em> and the longer version including the <em>Flores aurei</em>), identifies the relationship between the different manuscript families, and provides a text with full critical apparatus and extensive annotation. The introduction situates the Ars Notoria within the broader context of medieval ritual magic (especially its relationship to the Sworn Book of Honorius and to the Ars Almadel), discusses the theological debate over its licitness (from Aquinas's condemnation onward), and analyses the visual dimension of the tradition — the distinctive geometric <em>notae</em> that give the system its name and that survive in sometimes spectacular form in the illustrated manuscripts.</p>
<p>Véronèse's edition replaced earlier incomplete studies and for the first time provided historians with a reliable text of what was, in terms of manuscript circulation, one of the most popular learned magic texts of the medieval period. His collaboration with Claire Fanger and Nicholas Watson on the related <em>Liber visionum</em> of John of Morigny (Penn State, 2015) has extended the analysis to the Ars Notoria's most creative medieval response.</p>""",

"edward_kelley": """<h2>Life</h2>
<p>Edward Kelley (1555–1597/98) — born Edward Talbot, later calling himself Kelley — was an English scryer, alchemist, and occultist who served as John Dee's medium in the angel conversations of 1582–1589, receiving the communications that produced the Enochian language and cosmology. Kelley's background before meeting Dee was obscure and partly disreputable: he had lost his ears (a punishment for forgery or fraud) before joining Dee in 1582, and his subsequent career was marked by repeated conflicts with authorities, patrons, and Dee himself.</p>

<h2>The Angel Conversations</h2>
<p>Kelley's role in the angel conversations was as scryer: he gazed into Dee's crystal "shewstone" while Dee recorded the communications received. The Enochian language, the Tables of Enoch, and all the cosmological material of the angel conversations came through Kelley's mediation. The question of whether Kelley was a genuine visionary, a skilled fraud exploiting Dee's credulity, or something more ambiguous — a person who genuinely entered trance states but whose interpretations were shaped by the cultural and personal dynamics of the sessions — has been debated since the sessions themselves.</p>
<p>After Dee and Kelley's continental travels (1583–1589), Kelley remained in the Holy Roman Empire under the patronage of Emperor Rudolf II, who was interested in alchemy and occult philosophy. Kelley claimed to have discovered the "philosopher's stone" (the alchemical substance enabling transmutation of base metals into gold) and was alternately favoured and imprisoned by Rudolf, dying in 1597 or 1598 apparently while trying to escape from prison. Deborah Harkness's <em>John Dee's Conversations with Angels</em> (1999) provides the most thorough analysis of Kelley's role; Glyn Parry's <em>The Arch-Conjuror of England</em> (2011) offers a more sceptical reading.</p>""",

"dennis_duling": """<h2>Life and Scholarship</h2>
<p>Dennis C. Duling is a New Testament scholar and historian of early Christianity whose annotated translation of the <em>Testament of Solomon</em>, published in James H. Charlesworth's <em>Old Testament Pseudepigrapha</em> (Doubleday, 1983), remains the standard English edition of this foundational Solomonic text. Duling's academic career was spent at Canisius College in Buffalo, New York, where he specialized in New Testament studies with particular attention to the social history of early Christianity and to the pseudepigraphic literature that surrounded the canonical texts.</p>

<h2>The Testament of Solomon Translation</h2>
<p>Duling's translation in <em>OTP</em> vol. 1 (pp. 935–987) is annotated with full scholarly apparatus: introduction covering date, provenance, original language (Greek), manuscript tradition, relation to other pseudepigrapha, and theological significance; translation with notes identifying demon names, parallels in other sources, and textual variants. The translation made the <em>Testament of Solomon</em> accessible to the mainstream biblical scholarship audience that the <em>OTP</em> volumes were designed to serve, situating Solomonic demonology within the context of Jewish apocalyptic and early Christian writing rather than treating it as an isolated curiosity of the magical tradition.</p>
<p>Duling's introduction engages with the question of the <em>Testament</em>'s genre — neither exactly a pseudepigraphon (it narrates Solomon's activities rather than presenting revelation in his name) nor exactly a grimoire (it lacks practical instructions for replication) — and contextualizes the spirit catalogue within the broader late antique tradition of demonological literature. His treatment of the Christian interpolations in the Greek manuscript tradition identifies layers of revision that show how the text was adapted for different audiences across centuries. McCown's 1922 critical edition of the Greek text remains the textual basis; Duling's translation made it usable for non-specialist scholars.</p>""",

"don_c_skemer": """<h2>Life and Scholarship</h2>
<p>Don C. Skemer is a curator and historian at Princeton University Library whose scholarly work on medieval textual amulets — objects on which written texts are inscribed or enclosed for protective or magical purposes — has been foundational for understanding the material culture of medieval magic. His book <em>Binding Words: Textual Amulets in the Middle Ages</em> (Pennsylvania State University Press, 2006) is the most comprehensive study of this topic in any language and the essential reference for the history of written magic as a material practice.</p>

<h2>Binding Words</h2>
<p><em>Binding Words</em> examines the production and use of written protective objects across medieval Europe from approximately the sixth through the fifteenth centuries, with particular attention to England, France, and the Italian peninsula. Skemer's approach is broadly interdisciplinary: he combines codicological analysis (examining the physical properties of surviving objects — the materials on which texts are written, their size and form, their marks of wear and use), textual criticism (establishing what texts were inscribed and how they changed across the tradition), and social history (who commissioned, who produced, and who used these objects).</p>
<p>The book's central argument is that textual amulets were not simply residual paganism or popular superstition but a coherent and sophisticated material practice embedded in medieval literate culture at multiple social levels. The same person who read a scholastic theological text might commission or wear a written amulet bearing divine names or Gospel passages. The boundary between legitimate religious use of sacred texts (devotional books, relics) and illicit magical use of the same texts (written charms worn on the body) was a genuine object of theological debate rather than a simple institutional given. Skemer's documentation of the enormous variety of textual amulets in circulation — from simple Gospel inscriptions to complex Solomonic seal-sequences — demonstrates the richness of this material tradition.</p>""",

"michael_morgan": """<h2>Life and Scholarship</h2>
<p>Michael A. Morgan is a scholar of late antique Jewish religion and magic whose English translation of Mordecai Margalioth's critical edition of <em>Sepher ha-Razim</em> (The Book of Mysteries) — published by the Society of Biblical Literature in 1983 as part of the SBL Texts and Translations series — made this foundational text of Jewish magical tradition available to English-language scholars for the first time. Morgan's translation drew on Margalioth's 1966 Hebrew critical edition and provided the notes, introduction, and scholarly apparatus needed for non-Hebrew readers to use the text.</p>

<h2>The Sepher ha-Razim Translation</h2>
<p>The <em>Sepher ha-Razim</em> is a Hebrew magical handbook, probably compiled in the Geonic period (sixth to tenth centuries CE) but incorporating much older material, that organizes the seven heavens and their angelic inhabitants and provides adjuration formulas, incantations, and ritual procedures keyed to each heavenly realm. Morgan's translation introduced this text to the broader scholarly conversation about Jewish magic and its relationship to the Greek magical papyri, the Solomonic grimoire tradition, and the magical culture of late antique and early medieval Judaism.</p>
<p>The translation appeared in the same year as Dennis Duling's <em>Testament of Solomon</em> in Charlesworth's <em>Old Testament Pseudepigrapha</em> (1983), making 1983 a landmark year for the accessibility of the Jewish magical tradition to English-language scholarship. Together, the two translations established the basic scholarly foundation on which Gideon Bohak's subsequent comprehensive history of ancient Jewish magic (2008) could be built. Morgan's translation, though now partly superseded by more recent scholarship on specific textual problems, remains useful and is still widely cited.</p>""",

"katelyn_mesler": """<h2>Life and Scholarship</h2>
<p>Katelyn Mesler is a historian of medieval science and magic at Northwestern University whose work focuses on the transmission of knowledge — particularly magical and astrological knowledge — between Jewish, Christian, and Islamic cultures in the medieval Mediterranean world. Her research addresses how Hebrew magical texts entered Latin circulation, how Jewish scholars participated in or resisted the transmission of magical learning to Christian audiences, and how the boundaries between licit and illicit knowledge were negotiated across religious and cultural divides.</p>

<h2>Research Contributions</h2>
<p>Mesler's contributions to the history of medieval magic centre on the role of Jewish intermediaries and translators in the transmission of magical texts from Arabic and Hebrew into Latin, and on the specific textual traditions (amulet texts, Solomonic conjurations, astrological magic) that crossed religious boundaries. Her work on the Latin reception of Hebrew magical material illuminates a dimension of the Arabic-Latin translation movement that has been understudied: the translation of specifically Jewish magical texts (the <em>Liber Razielis</em>, Hebrew angel magic) into Latin, and the transformation of their meaning and authority in the process.</p>
<p>Her research engages with the broader question of how Jewish scholars in medieval Christian Europe navigated the demand for their expertise in magical and astrological matters while managing the religious and social risks that such engagement entailed. The essays collected in Sophie Page and Catherine Rider (eds.), <em>The Routledge History of Medieval Magic</em> (2019), to which Mesler contributed, provide the broader scholarly context for this research. Her work connects the Jewish magical tradition analysed by Bohak and Torijano to the Latin learned magic tradition analysed by Kieckhefer and Klaassen.</p>""",

"charles_burnett": """<h2>Life and Scholarship</h2>
<p>Charles Burnett is Professor of the History of Islamic Influences in Europe at the Warburg Institute, University of London, and the leading authority on the twelfth-century Arabic-Latin translation movement — the systematic transfer of Arabic scientific, philosophical, and magical learning into Latin that transformed European intellectual culture between approximately 1100 and 1200. His work spans Arabic astronomy, astrology, mathematics, philosophy, and magic, with particular attention to the scholars who performed the translations (Adelard of Bath, Hermann of Carinthia, Robert of Ketton, Gerard of Cremona, and others) and to the texts they chose to translate.</p>

<h2>Work on Magic</h2>
<p>For the history of magic, Burnett's most important contributions are his studies of specific translated magical texts and of the translators who brought them into Latin. His work on Adelard of Bath (including editions of several of Adelard's translations) documents the early phase of Arabic-Latin transmission. His studies of the <em>Picatrix</em> tradition, of al-Kindi's works on astrology and magic, and of the astrological-magic texts translated in the twelfth century provide the documentary basis for understanding how Arabic natural magic theory entered Latin learned culture.</p>
<p>Burnett has also worked on Arabic-Hebrew and Arabic-Latin transmission routes for magical texts, contributing to the understanding of how Solomonic and angel magic traditions moved between Jewish, Islamic, and Christian learned cultures. His editions and studies of specific texts — including works attributed to Michael Scot and to the Toledo translation circle — provide essential primary-source documentation. His broad command of the primary languages (Latin, Arabic, Hebrew, Greek) and his commitment to rigorous philological method make him indispensable to anyone working on the transmission of magical knowledge in the medieval period.</p>""",

"paola_zambelli": """<h2>Life and Scholarship</h2>
<p>Paola Zambelli (1929–2020) was an Italian historian of science and philosophy at the University of Florence whose work on Renaissance magic, natural philosophy, and the history of astrology and divination shaped the field across half a century. Her approach combined rigorous archival research with philosophical analysis, situating figures like Agrippa, Pomponazzi, and Cecco d'Ascoli within the social and institutional history of the Renaissance university and court.</p>

<h2>Major Contributions</h2>
<p>Zambelli's study of Cornelius Agrippa — developed across several articles and culminating in her analysis of the relationship between <em>De occulta philosophia</em> and <em>De incertitudine</em> — provided one of the most sophisticated accounts of Agrippa's intellectual development, arguing that his scepticism in <em>De incertitudine</em> was not simply a repudiation of the magical programme but a complex rhetorical and theological response to the dangers of public exposure. Her reading of Agrippa as a fideist sceptic — using Pyrrhonist arguments to defend religious faith against both scholastic rationalism and magical speculation — influenced Charles Nauert's biography and subsequent Agrippa scholarship.</p>
<p>Her work on Pietro Pomponazzi's <em>De naturalium effectuum causis sive de incantationibus</em> (On the Causes of Natural Effects, or On Incantations) — an Aristotelian argument that all apparently magical effects, including those attributed to demons and angels, can be explained through natural causes — placed this controversial text in its Paduan university context and illuminated the connection between Pomponazzi's radical Aristotelian naturalism and the broader Renaissance debate about magical causation. Her essays on astrological determinism and its condemnation, collected in <em>White Magic, Black Magic in the European Renaissance</em> (Brill, 2007), provide the best overview of her contributions to the history of magic.</p>""",

"benedict_lang": """<h2>Life and Scholarship</h2>
<p>Benedek Láng is a Hungarian historian of medieval science and magic at the Budapest University of Technology and Economics whose systematic research on Central European manuscript collections — libraries in Hungary, Austria, Poland, and Bohemia — has substantially extended the geographic scope of medieval magic scholarship beyond its traditional focus on English and French manuscripts. His work demonstrates that the learned magical tradition was pan-European in distribution and shows regional variations that earlier scholarship had not documented.</p>

<h2>Unlocked Books</h2>
<p><em>Unlocked Books: Manuscripts of Learned Magic in the Medieval Libraries of Central Europe</em> (Pennsylvania State University Press, 2008) is Láng's major contribution. The book surveys magical manuscripts in the major medieval library collections of Central Europe, providing a systematic catalogue and analysis of the distribution, types, and manuscript contexts of learned magic texts in a region that had been largely ignored by earlier grimoire scholarship. The survey reveals that Central European libraries contained substantial quantities of magical material — from astrological and geomantic texts through Solomonic conjuration and the Ars Notoria — circulating in manuscript contexts very similar to those identified by Klaassen for England and by Page for monastic contexts.</p>
<p>The book's arguments about the "unlocked" (openly accessible) character of many magical manuscripts — that is, their presence in regular library collections rather than in hidden or restricted locations — challenge the assumption that magical texts were necessarily clandestine. Many magical manuscripts were simply part of the learned library, accessible to anyone with access to the collection, suggesting that the social reality of magical manuscript circulation was more open than the theological rhetoric of condemnation implies. Láng's work complements Klaassen's and Page's studies of the English tradition and helps establish that the learned magical tradition was a genuinely European phenomenon.</p>""",

"jan_veenstra": """<h2>Life and Scholarship</h2>
<p>Jan R. Veenstra is a Dutch historian of medieval and Renaissance literature and magic at the University of Groningen whose work focuses on the intersection of political thought, court culture, and learned magic in late medieval Europe, with particular attention to France and the Low Countries. His research addresses how magical texts and magical practitioners operated within the specifically political contexts of the late medieval court and how the definition and condemnation of magic served political as well as theological purposes.</p>

<h2>Magic and Divination at Court</h2>
<p>Veenstra's most important work for magic history is his study of Jean de Bar and his magical activities at the French court, and more broadly his analysis of how divination and political prophecy intersected in late medieval French court culture. His book <em>Magic and Divination at the Courts of Burgundy and France: Text and Context of Laurens Pignon's 'Contre les devineurs'</em> (Brill, 1998) provides an edition of a fifteenth-century French treatise against divination alongside a rich contextual analysis of the political and social dimensions of divinatory practice in the Burgundian court milieu.</p>
<p>The analysis shows how the condemnation of divination and magic served specific political functions: attacks on court diviners could be instruments of factional politics as much as expressions of theological principle, and the definition of what counted as illicit divination was shaped by the specific political circumstances of specific moments. Veenstra's work thus connects the history of magic to the political history of late medieval France and Burgundy in ways that purely theological or natural philosophical analyses miss.</p>""",

}


TEXT_ENRICHMENTS = {

"liber_visionum": """<h2>Overview</h2>
<p>The <em>Liber visionum</em> (Book of Visions), composed by the Benedictine monk John of Morigny between approximately 1301 and 1315, is the most remarkable response to the Ars Notoria tradition in the medieval period: an extended autobiographical visionary text in which John narrates his use of the Ars Notoria, his gradual disillusionment with it following Marian visions, and his composition of a new, purified form of angel magic under direct divine and angelic guidance. The <em>Liber visionum</em> survives in several manuscript versions representing different stages of John's ongoing revision of the text.</p>

<h2>Narrative and Significance</h2>
<p>John began using the Ars Notoria to acquire knowledge of the arts and sciences and experienced visions of the Virgin Mary and Christ in which the Notory Art was condemned as contaminated by demonic elements — the voces magicae and geometric <em>notae</em> of the Ars Notoria, John's visionary informants told him, worked through demonic rather than angelic mediation. Under continued visionary guidance, John composed a new system of Marian contemplation and prayer — the <em>Liber florum celestis doctrine</em> or <em>Flowers of Heavenly Teaching</em> — that he believed replaced the Ars Notoria with a purified form of angelic illumination.</p>
<p>The text is unique in the medieval magical tradition for its sustained autobiographical narrative of a practitioner's engagement with, critique of, and revision of a magical tradition in response to visionary experience. It demonstrates from within the tradition how practitioners understood and evaluated what they were doing, rather than from the external perspective of theological condemnation. Claire Fanger and Nicholas Watson's critical edition and translation (<em>Liber florum celestis doctrine / The Flowers of Heavenly Teaching</em>, Penn State University Press, 2015) is the definitive scholarly treatment.</p>""",

"flowers_of_heavenly_teaching": """<h2>Overview</h2>
<p>The <em>Liber florum celestis doctrine</em> (Book of the Flowers of Heavenly Teaching), the revised core of John of Morigny's angel magic system, is the operative text that John presented as the purified replacement for the Ars Notoria. Where the Ars Notoria used geometric <em>notae</em> accompanied by voces magicae and extended prayers to secure divine infusion of the liberal arts, John's system uses a series of elaborate figure-based prayers (<em>flores</em>, flowers) designed under visionary guidance by the Virgin Mary and Christ, addressed to the Marian figure and the Trinity rather than to ambiguous angelic intermediaries.</p>

<h2>Structure and Content</h2>
<p>The <em>flores</em> are prayers of extraordinary length and density, each associated with a visual figure (related to but distinct from the Ars Notoria's <em>notae</em>). The first <em>flos</em> — the "flower of the beginning" — establishes the practitioner's relationship with the Virgin and requests her intercession. Subsequent flowers address specific kinds of knowledge (theology, philosophy, the arts), virtues, and states of contemplative consciousness. The system is designed to take weeks or months of sustained practice, with each flower to be used at appropriate times in the liturgical day.</p>
<p>The <em>Liber florum</em> demonstrates how a medieval practitioner transformed the inherited categories of learned magic — figures, prayers, systematic cycles of practice — within a specifically devotional and visionary framework. John's insistence that his system worked through genuine divine grace rather than demonic mediation places it in the contested territory between approved contemplative practice and condemned magic, a territory that his visionary informants navigated for him but that the Inquisition would likely have assessed differently. Claire Fanger and Nicholas Watson's Penn State edition (2015) is the essential scholarly resource.</p>""",

"munich_manual": """<h2>Overview</h2>
<p>The Munich Manual of demonic magic (Bayerische Staatsbibliothek, Clm 849) is a Latin miscellany copied in southern Germany around the 1440s and containing the most complete medieval Latin handbook of practical demonic magic to survive. The manuscript is significant precisely because it is unexceptional as an object: it is not a handsome presentation copy but a practical working document, bound with other material (medical and astrological texts), showing signs of use, and representing the kind of compiled magical resource that a learned practitioner — probably a clerk with university training — would assemble and use.</p>

<h2>Contents</h2>
<p>Clm 849 contains three main categories of material. The first is "illusionist" experiments: procedures for creating apparent wonders through sleight of hand, optical tricks, and psychological suggestion rather than demonic power. The second is practical experiments using spirit assistance: finding hidden treasure, compelling love or hate, discovering thieves, causing discord — operations that require the cooperation of named spirits but fall short of the full demonic conjuration of the third category. The third category is formal necromantic conjuration: complete rituals for summoning, binding, interrogating, and dismissing named demons, with all the ritual apparatus (magic circle, fumigations, prayers, conjuration formulas) specified in detail.</p>
<p>Richard Kieckhefer's <em>Forbidden Rites: A Necromancer's Manual of the Fifteenth Century</em> (Penn State University Press, 1997) provides the critical edition (Latin text with facing English translation) and the most thorough analysis. Kieckhefer's examination of the manuscript's social context — who would have possessed and used it, what the ritual apparatus implies about the practitioner's social position and resources — has been foundational for the concept of the "clerical underworld" in medieval magic scholarship.</p>""",

"history_magic_experimental_science": """<h2>Overview</h2>
<p>Lynn Thorndike's <em>A History of Magic and Experimental Science</em> (Columbia University Press, 1923–1958), in eight volumes, is the most extensive survey of the relationship between magic and science in European intellectual history and remains, despite its limitations, an indispensable research tool for anyone working on the subject. The project covered the Roman Empire through the seventeenth century and drew on primary sources — often in manuscript — that Thorndike was the first modern scholar to examine systematically.</p>

<h2>Argument and Organization</h2>
<p>Thorndike's thesis — implicit in the title — is that magic and experimental science were parallel developments sharing an empirical orientation toward the investigation of nature's hidden properties. Medieval magic, he argued, was not mere superstition: it represented a serious attempt to understand and exploit natural forces, and the gradual differentiation of legitimate experimental science from magical practice is a key theme in the history of European thought from the Roman period through the Scientific Revolution. The work proceeds chronologically and person-by-person: each chapter treats a specific author, manuscript, or text, summarizing its contents and situating it in the broader intellectual history.</p>
<p>The work's strengths are its scope (no subsequent project has approached its coverage) and its primary-source depth (Thorndike read widely in manuscript collections and provides the first systematic accounts of dozens of texts). Its weaknesses include a tendency toward uncritical summary, an outdated historiographical framework (the "magic to science" teleology has been substantially revised), and factual errors in the earlier volumes that have been corrected by subsequent specialized scholarship. Despite these limitations, Thorndike's chapter-length surveys often remain the only readily available accounts of specific texts and authors, and the eight-volume index is an invaluable finding tool.</p>""",

"invoking_angels": """<h2>Overview</h2>
<p>Claire Fanger (ed.), <em>Invoking Angels: Theurgic Ideas and Practices, Thirteenth to Sixteenth Centuries</em> (Penn State University Press, 2012) is the follow-up volume to Fanger's earlier <em>Conjuring Spirits</em> (1998) and represents the state of the field in the study of medieval and early Renaissance angel magic. The volume collects essays by leading scholars on the Ars Notoria tradition, the <em>Liber visionum</em> of John of Morigny, the <em>Sworn Book of Honorius</em>, and related texts, with particular attention to the relationship between angel magic, mysticism, and devotional practice.</p>

<h2>Contents and Significance</h2>
<p>The essays in <em>Invoking Angels</em> demonstrate how the category of "angel magic" — operations aimed at communication with angelic beings for the acquisition of knowledge or other benefits — overlaps with and cannot be cleanly separated from approved forms of medieval Christian contemplation and prayer. The practitioners of the Ars Notoria understood themselves as engaging in a form of pious enquiry for divine gifts of knowledge; John of Morigny's Marian angel magic was explicitly framed as a devotional practice. The volume's central argument is that the boundary between magic and mysticism in the medieval period was contested, permeable, and historically produced rather than given by the nature of the practices themselves.</p>
<p>Contributors include Julien Véronèse (on the Ars Notoria), Nicholas Watson (on John of Morigny), Sophie Page, and other leading historians of medieval magic. The volume is essential reading for the history of angelic magic and for understanding how the learned magical tradition intersected with the broader landscape of medieval Christian spiritual practice. Together with Fanger's <em>Conjuring Spirits</em> (1998), it constitutes the foundational edited collection for the study of medieval ritual magic.</p>""",

"magic_in_the_cloister": """<h2>Overview</h2>
<p>Sophie Page's <em>Magic in the Cloister: Pious Motives, Illicit Interests, and Occult Approaches to the Medieval Universe</em> (Penn State University Press, 2013) examines magical manuscripts in English monastic and collegiate library collections, demonstrating that monks, canons, and other religious not only possessed magical texts but engaged with them in ways that made sense within their intellectual and devotional frameworks. The book challenges the assumption that magic was simply suppressed by institutional Christianity and argues instead for a more complex picture of accommodation, curiosity, and practical use.</p>

<h2>Evidence and Argument</h2>
<p>Page's primary evidence consists of the magical manuscripts preserved in collections associated with specific English monastic and collegiate institutions — principally St Augustine's Canterbury, the Augustinian canons at Oxford, and related houses. By examining these manuscripts in their codicological context (what texts surround them, how the manuscripts are constructed, what marks of ownership and use they bear), Page reconstructs something of the reading practices of the religious who possessed them.</p>
<p>The picture that emerges is of a learned culture that maintained theoretical condemnations of magic while in practice preserving, copying, and apparently using magical texts for a variety of purposes: curiosity about the natural world and its hidden workings; practical medical applications (the boundary between healing and magic was genuinely ambiguous); interest in the cosmological frameworks that magical texts assumed; and possibly direct practical use of the simpler magical procedures. Page's argument that "pious motives" could coexist with "illicit interests" in the same practitioner is an important corrective to the tendency to treat magic and orthodoxy as simply opposed.</p>""",

"giordano_bruno_hermetic_yates": """<h2>Overview</h2>
<p>Frances Yates's <em>Giordano Bruno and the Hermetic Tradition</em> (Routledge and Kegan Paul, 1964) is the book that launched the scholarly study of Renaissance Hermeticism and Renaissance magic as serious historical subjects. Arguing that Giordano Bruno's philosophy was fundamentally Hermetic — shaped by the recovery and promotion of the <em>Corpus Hermeticum</em> in Ficino's 1463 translation — and that the Hermetic tradition provided crucial psychological and conceptual preconditions for the Scientific Revolution, the book provoked decades of debate and established the "Yates thesis" as the primary framework within which subsequent scholars engaged with Renaissance occult philosophy.</p>

<h2>The Argument</h2>
<p>Yates reconstructed Bruno's philosophical career as a sustained engagement with the Hermetic tradition: his Italian dialogues, his Latin memory treatises, his works on magic, and his cosmic philosophy all expressed, she argued, a Hermetic vision of the cosmos as animated by divine intelligence, of the human soul as a microcosm capable of ascending to union with the world-soul, and of the philosopher-magus as the person who operates within this animated cosmos to produce beneficial effects. Bruno's rejection of Aristotelian cosmology in favour of an infinite, heliocentric (or more precisely aheliocentric) universe was, Yates argued, motivated not by mathematical astronomy but by the Hermetic vision of an infinite deity filling an infinite cosmos.</p>
<p>The argument extended to a grand claim about the Scientific Revolution: the Hermetic emphasis on the human being as active operator on nature, the magus who changes the world rather than merely contemplating it, provided the psychological preconditions for the experimental orientation of early modern science. This claim, in its strong form, has been largely abandoned; but the book's rehabilitation of Bruno and its opening of the Hermetic tradition to scholarly analysis are lasting contributions. Brian Copenhaver, Nicholas Clulee, and Hilary Gatti's subsequent work on Bruno has refined and in some respects corrected Yates's account.</p>""",

"occult_philosophy_elizabethan_yates": """<h2>Overview</h2>
<p>Frances Yates's <em>The Occult Philosophy in the Elizabethan Age</em> (Routledge and Kegan Paul, 1979) examines the role of Hermetic and Kabbalistic thought in Elizabethan England, focusing on figures including John Dee, Christopher Marlowe, Shakespeare, and Edmund Spenser as participants in a broadly Hermetic-Rosicrucian intellectual culture. The book extends the argument of <em>Giordano Bruno and the Hermetic Tradition</em> into English literary and intellectual history, arguing that the occult philosophy permeated Elizabethan culture at a deep level.</p>

<h2>Argument and Assessment</h2>
<p>Yates argues that the Elizabethan period saw the climax of the Hermetic-Kabbalistic synthesis in England, particularly through John Dee's influence on court culture and intellectual circles. She traces connections between Dee's mathematical and magical programme, the Sidney circle's Neoplatonism, Marlowe's Doctor Faustus as a meditation on the magician's fate, and the allegorical structure of Spenser's Faerie Queene. Her identification of a coherent "occult philosophy" pervading Elizabethan culture was characteristic of her synthetic ambition.</p>
<p>The book has been received more cautiously than the Bruno study. The specific connections between Dee and the literary figures Yates discusses have often been questioned; Glyn Parry's more sceptical political reading of Dee (<em>The Arch-Conjuror of England</em>, 2011) and Nicholas Clulee's philosophical analysis of Dee's natural philosophy (<em>John Dee's Natural Philosophy</em>, 1988) have both provided frameworks that engage with Yates's account while qualifying its broader claims. Nevertheless, the book remains valuable for its documentation of the circulation of Hermetic ideas in Elizabethan England and for its attention to the literary dimensions of occult philosophy.</p>""",

"making_magic_elizabethan": """<h2>Overview</h2>
<p>Frank Klaassen and Sharon Hubbs Wright's <em>The Magic of Roger Bacon: Practical Magic in Medieval and Early Modern England</em> (Penn State University Press, forthcoming) and, more broadly, the body of scholarship focused on practical magic in the Elizabethan and early Stuart periods, examines the continuity between medieval learned magic and its early modern English manifestations. The primary source record for Elizabethan practical magic includes the Folger <em>Book of Oberon</em> (edited by Harms, Clark, and Peterson, 2015), the British Library's Sloane manuscripts, and the Ashmole collection at the Bodleian.</p>

<h2>The Elizabethan Magical Milieu</h2>
<p>Elizabethan England provides unusually rich documentation of practical magic at multiple social levels. At the learned end: John Dee's angel conversations (1582–1589), documented in meticulous diaries. At the middling level: the Sloane and Ashmole magical manuscripts, collections of astrological, Solomonic, and natural magical material assembled by practitioners like Simon Forman and Richard Napier. At the popular level: the cunning folk documented in quarter sessions records and pamphlet literature, offering services that included healing, divination, and counter-magic. Keith Thomas's <em>Religion and the Decline of Magic</em> (1971) provided the foundational social-historical account of Elizabethan magical practice; Frank Klaassen's subsequent manuscript-based scholarship has refined and corrected Thomas's picture by showing the continuity between medieval and Elizabethan learned magic that Thomas's "decline of magic" framework obscured.</p>""",

"hazards_of_the_dark_arts": """<h2>Overview</h2>
<p>Richard Kieckhefer's <em>Hazards of the Dark Arts: Advice for Medieval Princes on Witchcraft and Magic</em> (Penn State University Press, 2017) compiles and translates a series of late medieval advisory texts — addressed to princes, rulers, and nobles — that address the dangers of magic and witchcraft from a practical political perspective. The volume demonstrates that the discourse about magic was not confined to theological treatises and inquisitorial manuals but extended into the genre of political advice literature, where magic was addressed as a practical concern for rulers who might be targeted by maleficium or who needed to adjudicate accusations of magical harm.</p>

<h2>Contents and Significance</h2>
<p>The texts compiled by Kieckhefer represent a rarely examined genre: advice for princes on how to recognize, respond to, and protect against magical attack, written by court-connected scholars and clerics who combined theological learning with political practicality. The texts address topics including how to evaluate accusations of witchcraft, how to distinguish natural from demonic causation in apparent marvels, and how a prince should comport himself in relation to practitioners of magic — whether to prosecute them, tolerate them, or employ them.</p>
<p>The volume contributes to the broader social-historical understanding of how magical discourse operated in political contexts, complementing the institutional history of the Inquisition and the theological history of demonological writing. Kieckhefer's introduction situates these texts within the broader landscape of medieval political thought and the history of magic, and the translations make them accessible to English-language readers for the first time.</p>""",

"ot_pseudepigrapha_vol1": """<h2>Overview</h2>
<p>James H. Charlesworth's <em>The Old Testament Pseudepigrapha, Volume 1: Apocalyptic Literature and Testaments</em> (Doubleday, 1983) is the standard English reference collection for Jewish and Jewish-Christian pseudepigraphic literature adjacent to the Hebrew Bible and New Testament. Volume 1 contains Dennis Duling's annotated translation of the <em>Testament of Solomon</em> (pp. 935–987) — the standard English text of this foundational Solomonic document — alongside other apocalyptic and testamentary literature including 1 Enoch (translated by E. Isaac), 2 Enoch, the Testaments of the Twelve Patriarchs, and the <em>Apocalypse of Abraham</em>.</p>

<h2>Significance for Solomonic Studies</h2>
<p>The inclusion of the <em>Testament of Solomon</em> in a scholarly reference collection designed for mainstream biblical scholarship was significant for the history of magic: it placed Solomonic demonology within the context of Jewish apocalyptic and early Christian writing rather than treating it as an isolated curiosity of the magical tradition. Duling's introduction addresses the text's date, provenance, original language (Greek), and manuscript tradition with full scholarly apparatus, situating it within New Testament scholarship's engagement with the pseudepigraphic literature that surrounded the canonical texts.</p>
<p>The volume's theological context — the <em>OTP</em> was explicitly designed to serve biblical scholarship and seminary education — meant that Duling's translation reached audiences that would not typically have encountered the <em>Testament of Solomon</em> in the history-of-magic literature. This cross-disciplinary availability helped establish the text as a recognized reference point in New Testament studies as well as in the history of magic, and facilitated the subsequent scholarly conversation between Solomonic magic specialists (Torijano, Bohak) and biblical scholars working on pseudepigraphy and late antique Jewish-Christian relations.</p>""",

"steganographia": """<h2>Overview</h2>
<p>Johannes Trithemius's <em>Steganographia</em> (written c.1499, circulated in manuscript, printed posthumously in 1606) is one of the most enigmatic texts in the history of Renaissance learned magic: a work that presents itself as a system for communicating with and through spirits, using angelic names and ritual procedures derived from the Solomonic tradition, but which modern scholars (particularly Thomas Ernst, in a 1998 article) have demonstrated contains in its first two books a sophisticated polyalphabetic cipher hidden within the apparently magical instructions. Book III may contain genuinely magical content.</p>

<h2>The Hidden Cipher</h2>
<p>Books I and II of the <em>Steganographia</em> describe procedures for transmitting messages through the medium of named spirits: apparently, by performing a ritual addressed to the spirit of the hour and sending the spirit with a message, a practitioner could communicate with a distant correspondent. Thomas Ernst demonstrated that the actual mechanism is a substitution cipher: the spirit names encode the key to decrypt the message hidden in the apparent ritual text, and the "magic" is entirely cryptographic. This makes the <em>Steganographia</em> a foundational text in the history of cryptography — the first systematic treatment of polyalphabetic substitution in the Western tradition — disguised as a magical work.</p>
<p>Whether Trithemius intended the disguise (presenting cryptography as magic to provide cover for a genuinely practical communication technology) or whether he embedded the ciphers within an existing magical framework remains debated. Either way, the text exemplifies the instability of the boundary between magic and natural philosophy in the Renaissance: a system that looks like spirit-working turns out to be an ingenious mathematical technique. The <em>Steganographia</em> was placed on the Index of Prohibited Books in 1609, three years after its printing — too late, in any case, to suppress its influence on the cryptographic tradition.</p>""",

"the_magus_barrett": """<h2>Overview</h2>
<p>Francis Barrett's <em>The Magus, or Celestial Intelligencer; Being a Complete System of Occult Philosophy</em> (London: Lackington Allen and Co., 1801) is the most ambitious English-language compendium of occult philosophy produced in the early nineteenth century and a crucial text in the transmission of Renaissance learned magic from its early modern manuscript and print forms into the Victorian occult revival. Barrett compiled and republished large portions of the 1651 English translation of Agrippa's <em>De occulta philosophia</em>, alongside material from Peter d'Abano's <em>Heptameron</em>, mediaeval lapidary traditions, and other sources, presenting them as a comprehensive and still-applicable system of magical knowledge.</p>

<h2>Contents and Sources</h2>
<p>The three-book structure follows Agrippa's: Book I covers natural magic (occult properties of things, the four elements, alchemical principles); Book II covers magnetism, the Kabbalah, and the construction of talismans and magical seals; Book III covers celestial intelligences and demonology, with a catalogue of demons and their seals derived from the Goetic tradition. The striking copperplate engravings — particularly the demon portraits, each shown in a distinctive form — were influential on subsequent visual representations of demonic beings in the occult tradition.</p>
<p>Barrett also advertised himself as a teacher of the occult sciences and sought to attract private students, suggesting that the book was meant to serve both as an encyclopedic reference and as a prospectus for his teaching. His audience was the educated but non-specialist English reader interested in occult subjects — a market that expanded substantially through the nineteenth century. Owen Davies's <em>Grimoires</em> (2009) situates <em>The Magus</em> in the longer history of magical publication; the book's place as a bridge between early modern learned magic and the Victorian occult revival (the Golden Dawn, Aleister Crowley) makes it an important transitional text.</p>""",

"unlocked_books": """<h2>Overview</h2>
<p>Benedek Láng's <em>Unlocked Books: Manuscripts of Learned Magic in the Medieval Libraries of Central Europe</em> (Pennsylvania State University Press, 2008) extends the systematic study of magical manuscripts in institutional library collections — pioneered for England by Kieckhefer, Klaassen, and Page — to the libraries of Hungary, Austria, Poland, and Bohemia. The result substantially expands the geographic scope of medieval magic scholarship and demonstrates that the learned magical tradition was a genuinely pan-European phenomenon with significant regional variation.</p>

<h2>Findings and Significance</h2>
<p>Láng's survey of Central European library collections reveals that magical manuscripts were present in significant quantities in the major institutional libraries of the region: the royal library at Buda, the chapter libraries of Esztergom and Krakow, the university libraries of Vienna and Prague. The types of magical material represented span the full range of the European learned tradition: astrological and geomantic texts, the Ars Notoria, Solomonic conjuration, natural magic, and miscellaneous practical magical material.</p>
<p>The book's title reflects its central argumentative point: the magical manuscripts were "unlocked" — that is, accessible in regular library collections, available to any reader with access to the institution, not hidden in restricted or clandestine locations. This accessibility suggests that the social reality of magical manuscript possession and circulation was more open than the theological rhetoric of condemnation implies. Readers who consulted a magical text in a chapter library were not necessarily engaging in transgressive behaviour; they were using the resources of a learned library in the same way as they would use other technical or philosophical texts. Láng's findings complement Klaassen's for England and Page's for monastic contexts, establishing the "open library" character of medieval magical manuscript culture as a European-wide phenomenon.</p>""",

}


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    updated = 0
    for slug, html in CONCEPT_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM concepts WHERE slug=?", (slug,)).fetchone()
        if row:
            conn.execute("UPDATE concepts SET definition_long=? WHERE slug=?", (html, slug))
            print(f"  concept: {slug} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING concept: {slug}")

    for pid, html in PERSON_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM persons WHERE person_id=?", (pid,)).fetchone()
        if row:
            conn.execute("UPDATE persons SET bio_html=? WHERE person_id=?", (html, pid))
            print(f"  person: {pid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING person: {pid}")

    for tid, html in TEXT_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM texts WHERE text_id=?", (tid,)).fetchone()
        if row:
            conn.execute("UPDATE texts SET analysis_html=? WHERE text_id=?", (html, tid))
            print(f"  text: {tid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING text: {tid}")

    conn.commit()
    print(f"\nUpdated {updated} entries.")
    conn.close()


if __name__ == "__main__":
    main()
