import sqlite3, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from common import DB_PATH

CONCEPT_ENRICHMENTS = {
    "ars_notoria": """<h2>The Ars Notoria: Angelic Memory and Divine Knowledge</h2>
<p>The <em>Ars Notoria</em> (Notory Art) constitutes one of the most distinctive traditions within medieval learned magic, presenting itself not as demonic conjuration but as a divinely sanctioned method for acquiring wisdom, memory, and intellectual illumination through prayer, fasting, and the contemplation of complex figures known as <em>notae</em>. The text claims Solomonic authorship, asserting that the art was revealed to Solomon by the angel Pamphilos (or similar angelic intermediaries) and subsequently transmitted through select lineages. Its core premise—that concentrated spiritual discipline combined with sacred diagrams could engraft the liberal arts directly into the practitioner's mind—gave it an unusual hybrid character situated between legitimate religious devotion and condemned necromancy.</p>
<p>The Notory Art's historical trajectory illustrates the contested boundaries of licit and illicit knowledge in medieval Europe. Thomas Aquinas condemned it explicitly in his <em>Summa theologiae</em> (II-II, q. 96), arguing that it relied on unknown figures and unfamiliar orations whose efficacy could only derive from implicit demonic compacts. William of Auvergne similarly rejected it, while acknowledging its claim to angelic rather than demonic origin. Despite such condemnations, manuscripts proliferated throughout the thirteenth through fifteenth centuries, often accompanied by elaborate <em>notae</em>: geometrical figures, inscribed with sacred names in Latin, Hebrew, and pseudo-Hebrew scripts, which practitioners were instructed to gaze upon during extended prayer cycles. The association with Solomon lent the tradition a veneer of scriptural authority that complicated straightforward dismissal.</p>
<p>Scholarly analysis, particularly the work of Julien Véronèse and Claire Fanger, has situated the <em>Ars Notoria</em> within the broader context of clerical culture and the medieval university. The art's professed goal—mastery of the seven liberal arts—reflects the anxieties and ambitions of a learned class for whom intellectual achievement carried both spiritual and professional significance. The blend of liturgical prayer forms with exotic diagrams suggests compilation by clerics who were deeply embedded in ecclesiastical culture yet drawn to explore the outer limits of what prayer and sacred image might accomplish. The tradition fed into later developments, including John of Morigny's visionary <em>Liber florum celestis doctrine</em> and various Renaissance magical synthesis projects.</p>""",

    "exorcism": """<h2>Exorcism: Ecclesiastical Authority and the Expulsion of Evil Spirits</h2>
<p>Exorcism—the formal expulsion of demonic presences from persons, places, or objects through authorized ritual speech and action—occupied a complex position in medieval religious and magical culture. As an official sacramental rite performed by ordained clergy, exorcism belonged squarely within the legitimate institutional apparatus of the Church. The minor order of exorcist existed as a formal clerical grade, and episcopal liturgical books provided standardized formulae for the expulsion of demons from catechumens, the blessing of water and salt, and the healing of possessed individuals. Yet the same conceptual framework that legitimized ecclesiastical exorcism also underwrote a vast popular and semi-learned tradition of protective and healing rituals that ecclesiastical authorities viewed with deep suspicion.</p>
<p>The theological rationale for exorcism rested on patristic and scriptural foundations: Christ's own expulsions of demons in the Gospels established both the reality of demonic possession and the efficacy of divine authority wielded through proper agents. Augustine's demonology, refined through centuries of scholastic commentary, held that demons were real spiritual entities subject to divine command but capable of harming humans through permitted affliction. Aquinas and his contemporaries elaborated sophisticated accounts of demonic psychology and the mechanisms by which adjuration, prayer, and the invocation of sacred names could compel compliance. This theoretical apparatus simultaneously supported official exorcism and provided conceptual resources for practitioners of learned magic who appropriated the same command-idiom in their conjuration texts.</p>
<p>The boundary between legitimate exorcism and illicit conjuration was perpetually contested. Critics like William of Auvergne and Jean Gerson drew attention to the structural similarity between the Church's own rites and the formulae in condemned magical texts: both employed divine names, commanded spirits in the name of Christ and the Trinity, and claimed angelic assistance. The grimoire tradition extensively borrowed ecclesiastical ritual forms—the <em>Sworn Book of Honorius</em> and the <em>Munich Manual</em> both drew on exorcistic prayer conventions—producing texts that their compilers may have regarded as extensions of legitimate clerical power rather than demonic trafficking. This ambiguity persisted into the early modern period, when debates over witchcraft, possession, and exorcistic authority became entangled with confessional conflicts between Protestants and Catholics.</p>""",

    "mathematical_arts": """<h2>Mathematical Arts: Arithmetic, Geometry, and Their Occult Extensions</h2>
<p>The mathematical arts—arithmetic, geometry, music, and astronomy, constituting the quadrivium of the medieval university curriculum—occupied an ambiguous position in discussions of magic and natural philosophy. On one hand, these disciplines represented the highest form of rational inquiry into natural order, foundational to both scholastic education and practical sciences such as surveying, medicine, and calendar calculation. On the other hand, the manipulation of number, figure, and proportion carried persistent associations with divination, astrological prediction, and the secret operations of nature that troubled ecclesiastical authorities and generated accusations of demonic involvement.</p>
<p>Arithmetic magic took several forms. Numerological speculation—the attribution of sacred or cosmic significance to specific numbers—pervaded both biblical commentary and practical magical texts. The divine names in Hebrew were subjected to gematria (letter-number equivalences), yielding numerical values thought to encode cosmic secrets. Magical squares (<em>kamea</em>), arrangements of numbers summing equally in all directions, were associated with planetary powers and inscribed on amulets. Geometry entered magical practice through the construction of ritual diagrams, circles, triangles, and pentagrams believed to bind or channel spiritual forces. The <em>Ars Notoria</em>'s elaborate <em>notae</em> blended geometric form with sacred inscription, while the grimoire tradition prescribed precise geometrical configurations for spirit-summoning circles.</p>
<p>The condemnation of divinatory mathematics—geomancy, pyromancy, and related arts—by authorities from Isidore of Seville to Etienne Tempier's 1277 Paris condemnations reflected anxiety about the slippage between licit mathematical inquiry and illicit prophetic or demonic knowledge. Thinkers like Roger Bacon sought to rehabilitate mathematical sciences by grounding them in natural causation: the influence of celestial configurations on terrestrial matter was, in his account, a subject for natural philosophy rather than superstition. Nicole Oresme's critiques of astrology similarly attempted to police the boundary between legitimate mathematical astronomy and its astrological extensions. These debates established the contested epistemological terrain within which Renaissance figures like John Dee would pursue ambitious programs uniting mathematics, natural philosophy, and spiritual communication.</p>""",
}

PERSON_ENRICHMENTS = {
    "peter_abelard": """<h2>Peter Abelard (1079–1142): Logic, Theology, and the Boundaries of Inquiry</h2>
<p>Peter Abelard stands as one of the most intellectually combative and personally dramatic figures of the twelfth-century renaissance. Born near Nantes to a minor noble family that valued learning, Abelard abandoned his inheritance to pursue the new scholastic philosophy emerging in the cathedral schools of northern France. His mastery of logic—then the cutting edge of intellectual culture—brought him to Paris, where he challenged and defeated his teacher William of Champeaux in public disputation, establishing himself as the preeminent dialectician of his generation. His school at Mont Sainte-Geneviève drew students from across Europe, making him the most sought-after master of his era.</p>
<p>Abelard's contributions to the intellectual history relevant to magic and natural philosophy were primarily methodological. His <em>Sic et Non</em> (c. 1120) assembled contradictory authorities on 158 theological questions, demonstrating through sheer juxtaposition that received tradition required critical interpretation rather than passive reception—a method that empowered subsequent thinkers to subject natural phenomena, including magical claims, to rational scrutiny. His ethical philosophy, particularly his emphasis on intention as the determinant of moral character, had implications for assessments of magical practice: was an act sinful because of its external form or because of the practitioner's interior orientation toward demonic powers? This question would recur throughout later debates about the moral status of magical arts.</p>
<p>Abelard's turbulent life—his secret marriage to Heloise, his castration by her uncle's hired men, his subsequent monastic career, and his repeated condemnations at the Councils of Soissons (1121) and Sens (1140) at the instigation of Bernard of Clairvaux—made him a symbol of the tensions between intellectual innovation and ecclesiastical authority. Though not himself a practitioner or theorist of magic, his logical method and his willingness to subject theological tradition to critical analysis helped create the scholastic culture in which natural philosophy and demonological theory were elaborated with unprecedented rigor.</p>""",

    "theysolius": """<h2>Theysolius: Legendary Magician and Attributed Author</h2>
<p>Theysolius represents one of the more obscure attributed authorities in the medieval magical corpus, a figure whose historical reality is uncertain and whose significance lies primarily in his role as a legitimating name attached to particular texts. The <em>Liber Theysolius</em>, a Latin magical compilation associated with this name, belongs to the tradition of texts claiming transmission from ancient wisdom figures—a strategy common to the grimoire genre as well as to alchemical and astrological literature. By invoking an exotic, semi-legendary sage as original author, compilers signaled the text's claim to ancient authority while insulating it from immediate contemporary accountability.</p>
<p>The practice of pseudepigraphical attribution in medieval magic drew on multiple models: biblical figures like Solomon and Raziel, ancient philosophers like Aristotle and Apollonius of Tyana, and semi-legendary sages like Hermes Trismegistus and, in this case, Theysolius. Such attributions were not necessarily understood as deliberate fabrications; medieval textual culture often accepted the transmission of ancient wisdom through chains of unnamed intermediaries, and the claim that a text ultimately derived from an ancient wise man carried cultural weight regardless of the chain's verifiability. The specific content attributed to Theysolius—ritual procedures, spirit names, and operational instructions characteristic of the learned magic tradition—places this compilation within the broader experimental magic literature of the twelfth through fourteenth centuries.</p>
<p>Scholarly recovery of texts attributed to marginal figures like Theysolius has been part of a broader project to map the full range of the medieval Latin magical corpus beyond its canonical exemplars. Manuscript catalogues and critical editions of minor texts have gradually revealed the scope and variety of this literature, demonstrating that named authorities like Theysolius functioned within a recognizable economy of legitimation in which ancient, exotic, or divine origin served to authorize otherwise suspect practices. The study of such figures illuminates the sociology of magical textual production as much as the content of any particular text.</p>""",

    "ulrich_molitor": """<h2>Ulrich Molitor (c. 1442–1507): Legal Humanist and Skeptic of Witchcraft</h2>
<p>Ulrich Molitor was a German jurist and legal humanist whose 1489 treatise <em>De lamiis et phitonicis mulieribus</em> (On Witches and Female Soothsayers) represents a significant early contribution to debates about witchcraft that would intensify dramatically over the following decades. Written in the form of a dialogue and illustrated with woodcuts depicting witches engaged in various supposed activities, Molitor's text engaged directly with the questions raised by the <em>Malleus Maleficarum</em> (1487) while adopting a notably skeptical position on the reality of witches' powers. His legal training and humanist sensibilities led him to question whether the feats attributed to witches—flight, metamorphosis, weather-working—could be literally real or were rather diabolical illusions and melancholic delusions.</p>
<p>Molitor's argument drew on the canon <em>Episcopi</em>, the influential ninth-century ecclesiastical text which had long asserted that beliefs about nocturnal flight and transformation were illusory—the product of demonic deception rather than actual supernatural events. Against demonologists who were increasingly arguing that the <em>Episcopi</em>'s skepticism had been superseded by accumulated evidence of witch activity, Molitor maintained that God would not permit demons to possess such comprehensive power over creation. This position aligned with a tradition of qualified skepticism about witch powers that persisted alongside the more credulous demonological consensus emerging in the late fifteenth century.</p>
<p>The visual apparatus of Molitor's text—its woodcut illustrations depicting stereotypical witch activities—is as significant as its arguments. These images circulated widely and contributed to the visual iconography of the witch, even as the text they illustrated maintained skeptical positions about witch powers. This paradox illustrates the complexity of the early modern witch debate, where visual, literary, legal, and theological discourses operated on partially independent tracks, sometimes reinforcing and sometimes contradicting each other. Molitor's work thus occupies an important position in the historiography of witchcraft as evidence of the diversity of learned opinion before the hardening of consensus in the sixteenth century.</p>""",

    "herman_gollancz": """<h2>Herman Gollancz (1852–1930): Scholar of Hebrew and the Magical Tradition</h2>
<p>Herman Gollancz was a British rabbi and scholar of Semitic languages whose edition of the <em>Sepher Maphteah Shelomoh</em> (Book of the Key of Solomon) and other related texts made important contributions to the scholarly study of Jewish magical literature and its relationship to the broader Western grimoire tradition. Working in the late nineteenth and early twentieth centuries, Gollancz represented a generation of Jewish scholars who brought rigorous philological methods to the study of Hebrew and Aramaic texts that had been either ignored or sensationalized by earlier generations of Christian Hebraists.</p>
<p>His editorial work on Solomonic magical texts required navigating the complex manuscript traditions of Hebrew grimoires, which existed in multiple recensions reflecting centuries of copying, translation, and adaptation. The Hebrew Solomonic tradition—including the <em>Mafteah Shelomoh</em>, the <em>Sepher ha-Razim</em>, and related compilations—occupied an important position in the history of Western magic because it represented both an independent Jewish magical tradition and a potential source (through Latin translation) for European learned magic. Establishing reliable texts of these works was therefore significant not only for Jewish studies but for understanding the transmission channels through which Jewish magical concepts entered medieval Christian culture.</p>
<p>Gollancz's scholarship exemplified the broader professionalization of Jewish studies in Britain and Europe during the late Victorian and Edwardian periods, a development that transformed the academic study of Jewish texts from a largely Christian theological enterprise into a philologically rigorous discipline practiced by Jewish and non-Jewish scholars alike. His contributions to magical text studies remain relevant to contemporary scholarship, which continues to investigate the multilingual, multicultural transmission networks through which magical knowledge circulated across the medieval Mediterranean and European worlds.</p>""",

    "johannes_hartlieb": """<h2>Johannes Hartlieb (c. 1400–1468): Court Physician and Expositor of Forbidden Arts</h2>
<p>Johannes Hartlieb was a Bavarian court physician and author who served the Wittelsbach dynasty and produced one of the most significant vernacular treatments of magic in fifteenth-century Germany. His <em>Buch aller verbotenen Kunst, Unglaubens und der Zauberei</em> (Book of All Forbidden Arts, Superstition, and Sorcery, c. 1456) provided a systematic vernacular taxonomy of magical practices organized around the traditional schema of the seven forbidden arts—nigromancy, geomancy, hydromancy, aeromancy, pyromancy, chiromancy, and spatulamancy—supplemented by discussions of other condemned practices including witchcraft and demonic compacts.</p>
<p>Hartlieb's text is particularly valuable for historians because it was written for a courtly lay audience rather than for academic theologians, reflecting the dissemination of anti-magical discourse beyond the Latin-literate clerical and university world. His patron, the Margrave Johann von Brandenburg, received a text that combined moralizing condemnation with practical description, giving readers enough information about magical practices to recognize and avoid them while making the material accessible through vernacular German prose rather than scholastic Latin. This pedagogical strategy—explaining in order to condemn—characterized much early vernacular demonological literature and inadvertently preserved detailed descriptions of magical practices.</p>
<p>As a physician, Hartlieb occupied a professional position at the intersection of natural philosophy, medicine, and magic. Medical practitioners of the fifteenth century regularly encountered questions about the boundary between natural cures, learned magic, and popular healing practices, and Hartlieb's exposition of forbidden arts likely drew on his professional experience with cases where patients had sought magical remedies. His work thus illuminates both the learned discourse about magic and the social reality of magical practice in late medieval German urban and courtly culture, providing a perspective that complements the more abstract theoretical treatments produced by theologians and inquisitors.</p>""",

    "david_porreca": """<h2>David Porreca: Scholar of Hermes Trismegistus and Medieval Magic</h2>
<p>David Porreca is a contemporary scholar whose research has contributed significantly to understanding the reception of Hermetic texts in medieval Europe, particularly the figure of Hermes Trismegistus as an attributed authority in philosophical, astrological, and magical literature. His work situates the medieval Hermes within the broad tradition of pseudepigraphical attribution through which ancient wisdom figures were invoked to legitimize learned texts of uncertain or composite origin, examining how particular texts came to be associated with Hermes and what this association meant to their medieval readers and users.</p>
<p>Porreca's scholarship addresses the complex question of Hermes' identity and function in medieval intellectual culture. Unlike the Renaissance recovery of Greek Hermetic texts that Frances Yates analyzed in her foundational work, the medieval Hermes was primarily known through Latin translations of Arabic astrological and talismanic texts—particularly the <em>Picatrix</em> and <em>Liber Hermetis</em>—rather than through the philosophical Corpus Hermeticum that became central to Renaissance Neoplatonism. This medieval Hermes was above all an astrologer and sage of natural powers, not the mystic theologian of Ficino's synthesis. Understanding this distinction is essential for accurate histories of Hermetic tradition that avoid anachronistically projecting Renaissance categories onto medieval materials.</p>
<p>His contributions to the study of medieval magic place him within a generation of scholars who have significantly expanded and revised the historical understanding of learned magic's textual foundations. By attending carefully to the specific textual traditions—manuscripts, translations, attributions, and readership—through which magical knowledge circulated, researchers like Porreca have replaced earlier, more impressionistic accounts of a unified "Hermetic tradition" with a more nuanced picture of multiple, partially overlapping textual lineages with distinct histories and audiences.</p>""",

    "johann_weyer": """<h2>Johann Weyer (1515–1588): Physician, Demonologist, and Skeptic</h2>
<p>Johann Weyer (also Wier or Wierus) was a Dutch physician who studied under Heinrich Cornelius Agrippa and became one of the most significant early voices for skepticism about witchcraft accusations, primarily through his landmark <em>De praestigiis daemonum et incantationibus ac veneficiis</em> (On the Illusions of Demons, 1563). Weyer's arguments rested not on denial of the reality of demons—he fully accepted a traditional demonological framework—but on the claim that the women accused of witchcraft were typically mentally ill, elderly, or melancholic individuals whom demons deceived into believing they had made pacts and committed the impossibilities described by inquisitors. In his view, the real agents of harm were the demons themselves, not their deluded victims.</p>
<p>Weyer's medical training shaped his intervention fundamentally. Drawing on humoral pathology and emerging clinical observation, he diagnosed many supposed witches as suffering from conditions recognizable as melancholia (depression), senile dementia, or other mental disorders that made them susceptible to diabolical delusion. This medicalization of witchcraft belief did not challenge the theological framework of demonology but redirected its focus from human culpability to demonic agency, arguing that the proper response to alleged witches was medical care rather than execution. The implicit argument—that learned prosecutors were being manipulated by the very demons they claimed to prosecute—gave his skepticism theological as well as clinical teeth.</p>
<p>Weyer's work provoked fierce opposition, most notably from Jean Bodin, who wrote a detailed rebuttal (<em>De la démonomanie des sorciers</em>, 1580) attacking Weyer's credentials, arguments, and motives. The Weyer-Bodin controversy represents a key moment in early modern demonological debate, crystallizing opposed positions on the reality of witch powers, the validity of confessions, and the appropriate judicial response to accusations. Despite his skepticism about witch trials, Weyer himself believed in demons, sorcerers (as opposed to witches), and the reality of diabolical compacts—distinctions that complicate any simple narrative of him as a proto-rationalist pioneer of mental health advocacy.</p>""",
}

TEXT_ENRICHMENTS = {
    "arbatel_de_magia_veterum": """<h2>Arbatel de Magia Veterum (1575): Olympic Spirits and Christian Theurgy</h2>
<p>The <em>Arbatel de Magia Veterum</em> (Arbatel Concerning the Magic of the Ancients) is a short but influential magical text published in Basel in 1575, notable for its unusual attempt to integrate magic into a framework of Christian piety and ethical self-cultivation. Unlike the grimoire tradition's focus on the practical compulsion of spirits for specific goals, the Arbatel presents magic as a path of spiritual wisdom requiring moral preparation, prayer, and submission to divine will. Its seven Olympic spirits—Aratron, Bethor, Phaleg, Och, Hagith, Ophiel, and Phul, each governing a planetary sphere—are presented less as beings to be commanded than as ministers of divine providence whose assistance flows naturally to those who live virtuously.</p>
<p>The text's structure reflects its distinctive theological orientation. Rather than the operational instructions, spirit names, and binding formulae typical of learned magic compilations, the Arbatel offers a series of aphorisms about the proper attitude and conduct of the aspiring magus, interspersed with descriptions of the Olympic spirits' powers and the conditions under which they might be invoked. The emphasis on divine permission, ethical worthiness, and the magician's submission to God as prerequisite for successful magic represents a significant departure from much of the earlier grimoire tradition, though the same framework of planetary spirits and their hierarchies appears across many magical texts.</p>
<p>The Arbatel exercised considerable influence on later magical thought, particularly in German Protestant contexts where it circulated as a relatively accessible introduction to magical philosophy. Its integration of magical practice with Christian ethics made it less obviously condemned than texts featuring demonic conjuration, and it was read alongside works like the <em>Heptameron</em> and attributed works of Agrippa by practitioners seeking a theologically defensible approach to spirit contact. Modern scholars including Christopher Lehrich and Stephen Skinner have situated it within the broader tradition of Renaissance Christian Kabbalah and theurgical magic that sought to reframe occult practice as an extension of legitimate religious devotion rather than a rival to it.</p>""",

    "ars_almadel": """<h2>Ars Almadel: Angelic Conjuration through the Wax Tablet</h2>
<p>The <em>Ars Almadel</em> constitutes one of the five books typically assembled in the seventeenth-century compilation known as the <em>Lemegeton</em> or Lesser Key of Solomon, though it circulated independently in earlier manuscript traditions. Its distinguishing feature is its method of angelic invocation: the practitioner constructs a wax tablet (almadel) engraved with divine names and symbols, lights candles upon it, and invokes angels associated with specific chora or quarters of the heavens. Unlike the demonic conjuration of the Goetia, the Almadel presents itself as a form of angelic magic seeking benevolent assistance with healing, knowledge, and protection from a class of angelic beings divided into four celestial regions.</p>
<p>The text's origins are obscure, with manuscript versions appearing in the later medieval period. Its title derives from Arabic <em>al-mandal</em>, a term associated with a class of divinatory and magical mirror or surface practices, suggesting a transmission history involving Arabic magical literature. The specific angelic names and the fourfold division of celestial regions connect it to broader traditions of Jewish and Christian angel lore elaborated in texts like the <em>Sepher ha-Razim</em> and the <em>Liber Razielis</em>, which similarly assigned angels to cosmic zones and described procedures for invoking their assistance.</p>
<p>The Almadel's compilation into the Lemegeton placed it within a systematized presentation of Solomonic magic that became influential in seventeenth-century England and subsequently in the modern occult revival. The Lemegeton assembly—combining the demonic Goetia with the Theurgia Goetia, Pauline Art, Almadel, and Notory Art—created a comprehensive manual of spirit magic that purported to cover the full range of spiritual beings from demons to angels, all framed within Solomonic authority. This compilation strategy reflects the early modern consolidation of previously dispersed magical texts into integrated systems, a process paralleled in contemporary publications like the <em>Heptameron</em> and the various editions of the Key of Solomon.</p>""",

    "ars_goetia": """<h2>Ars Goetia: The Seventy-Two Demons of Solomon</h2>
<p>The <em>Ars Goetia</em> (or simply the Goetia) is the first and most famous book of the seventeenth-century compilation known as the <em>Lemegeton</em> or Lesser Key of Solomon. It presents a systematic catalogue of seventy-two demons whom Solomon allegedly bound under his seal and confined in a brass vessel, together with detailed descriptions of each spirit's appearance, rank, powers, and the method of compelling it to appear and perform service. The spirits are organized hierarchically into kings, dukes, princes, marquises, presidents, earls, and knights, with each rank commanding specified numbers of lesser spirits and possessing particular areas of competence ranging from knowledge of hidden things to the teaching of arts and sciences to the creation of illusions.</p>
<p>The catalogue's origins lie in earlier medieval demonological literature. Several of the spirit names and their attributed powers show connections to the Jewish <em>Testament of Solomon</em>, to Arabic magical compilations, and to the expanding demonological encyclopaedias assembled by late medieval learned magic practitioners. The specific list of seventy-two, however, appears to crystallize in the sixteenth century, with manuscript versions circulating before the compilation of the Lemegeton. Johann Weyer's <em>Pseudomonarchia Daemonum</em> (1577), appended to his <em>De praestigiis daemonum</em>, provided an early printed list of these spirits that served as a source for subsequent compilations including the Goetia itself.</p>
<p>The Goetia became enormously influential in the modern Western magical tradition following Aleister Crowley and Samuel Liddell Mathers' edition of 1904, which combined the manuscript text with Crowley's extended commentary and additional material. This edition transformed a seventeenth-century manuscript compilation into a foundational text of twentieth-century ceremonial magic. Historical scholarship, including the work of Joseph Peterson and Daniel Harms, has subsequently worked to reconstruct the earlier manuscript traditions and disentangle the authentic seventeenth-century text from later accretions, establishing the Goetia's place within the broader history of Solomonic magic rather than treating it primarily through the lens of modern occultism.</p>""",

    "ars_paulina": """<h2>Ars Paulina: Angelic Governors of Hours and Degrees</h2>
<p>The <em>Ars Paulina</em> forms the third book of the <em>Lemegeton</em> compilation and represents a sophisticated integration of astrological and angelic lore. The text describes two classes of angels: those governing the twenty-four hours of the day (Book One), and those governing the 360 degrees of the zodiac (Book Two). Unlike the demonic conjuration of the Goetia, the Pauline Art claims to operate through angels who are benevolent ministers of the celestial order, accessible to practitioners who know their proper names and the astrological conditions under which they exert influence. The text attributes its transmission to the apostle Paul, citing Paul's account in 2 Corinthians of being "caught up to the third heaven"—an attribution that claimed apostolic authority for practices that the institutional Church would otherwise condemn.</p>
<p>The text's astrological framework connects it to the broader tradition of astrological magic elaborated in texts like the <em>Picatrix</em> and the writings of Thabit ibn Qurra. The assignment of angels to specific hours and zodiacal degrees reflects the medieval understanding of celestial influence as operating through hierarchically ordered spiritual beings who transmitted planetary or stellar virtue to the sublunary world. This conceptual framework allowed magical practitioners to present their operations as working in harmony with—rather than against—the divinely ordained cosmic order, since invoking the angel of a particular celestial configuration was ostensibly different from commanding demons.</p>
<p>The Pauline Art's place within the Lemegeton compilation illustrates the synthetic character of seventeenth-century learned magic: the assembler drew together texts of diverse origin—demonic conjuration, angelic invocation, talismanic magic, the Notory Art—and presented them as components of a unified Solomonic system. This synthetic presentation was itself a form of intellectual legitimation, suggesting that the various operations constituted parts of a coherent magical philosophy rather than a miscellaneous collection of techniques. The attribution to Paul, like the attribution to Solomon elsewhere in the compilation, served to anchor the entire system in ancient sacred authority.</p>""",

    "book_of_oberon": """<h2>Book of Oberon: English Fairy Magic and Spirit Conjuration</h2>
<p>The <em>Book of Oberon</em> is a substantial late sixteenth-century English magical compilation named for Oberon, the king of the fairies, whose invocation appears among its many spirit conjurations. The manuscript, held at the Folger Shakespeare Library, represents one of the most comprehensive surviving examples of Elizabethan practical magic, combining material from multiple traditions: Solomonic conjuration in the continental learned magic tradition, fairy lore drawn from English popular culture, astrological medicine, and experimental procedures drawn from various natural magical sources. Its juxtaposition of learned and popular elements makes it an invaluable witness to the actual practice environment of Elizabethan magical culture.</p>
<p>The inclusion of fairy conjuration alongside demonic conjuration and angelic invocation reflects the particular character of English magical culture, in which the category of fairy overlapped with but was distinct from the continental categories of demon and spirit. English fairies occupied an ambiguous ontological position: neither straightforwardly demonic nor clearly angelic, they were nonetheless powerful beings accessible to practitioners with appropriate knowledge and ritual technique. The appearance of Oberon—better known from literary contexts including Shakespeare's <em>A Midsummer Night's Dream</em> and the medieval romance <em>Huon of Bordeaux</em>—in a practical magical text illustrates the porous boundary between literary and operational magical traditions in the Elizabethan period.</p>
<p>The scholarly edition of the <em>Book of Oberon</em> by Daniel Harms, James Clark, and Joseph Peterson (2015) made this important manuscript accessible to researchers and practitioners alike. Their work situates the compilation within the broader context of Elizabethan magical culture as illuminated by studies like Frank Klaassen's examination of manuscript magic and the broader scholarship on occultism in Renaissance England. The <em>Book of Oberon</em> provides crucial evidence for the social and cultural context of magical practice—who compiled magical texts, what they hoped to achieve, and how they navigated the relationship between learned magic, popular belief, and official condemnation.</p>""",

    "book_of_oberon_edition": """<h2>The Book of Oberon: A Sourcebook of Elizabethan Magic (2015 Edition)</h2>
<p>The modern scholarly edition of the <em>Book of Oberon</em>, published by Llewellyn in 2015 and edited by Daniel Harms, James R. Clark, and Joseph H. Peterson, represents a major contribution to the history of Elizabethan magical culture. The editors transcribed and annotated the previously unstudied Folger Shakespeare Library manuscript (MS V.b.26), a late sixteenth-century English magical compilation of roughly 300 pages covering spirit conjuration, astrological medicine, fairy lore, and experimental magic. Their editorial work made accessible a primary source that substantially enriches understanding of how learned magic actually operated in the hands of practitioners rather than in the abstract discussions of theologians and demonologists.</p>
<p>The edition's scholarly apparatus—introductions, footnotes, glossaries, and comparative references to parallel texts—situates the manuscript within the context of late sixteenth-century English magical culture. The editors trace the manuscript's sources, identifying material derived from continental learned magic traditions (Solomonic conjuration, astrological medicine) alongside characteristically English elements (fairy conjuration, charms in the vernacular tradition). This comparative work illuminates the processes of textual transmission and cultural adaptation through which a broadly European learned magical tradition was transformed into something distinctively Elizabethan.</p>
<p>The publication history of the edition itself reflects the contemporary landscape of magical text scholarship, where academic presses and popular occult publishers both compete for and sometimes collaborate on the audience for historical magical texts. The Llewellyn edition, while produced to high scholarly standards, was published by a firm primarily serving practitioners of contemporary paganism and magic rather than academic historians. This positioning illustrates the complex relationship between historical scholarship on magic and contemporary magical practice—a relationship in which historical research serves simultaneously as academic contribution and as resource for living traditions that claim historical roots.</p>""",

    "book_of_soyga": """<h2>Book of Soyga: Alphabetic Tables and Angelic Secrets</h2>
<p>The <em>Book of Soyga</em> (also known as <em>Aldaraia sive Soyga vocor</em>) is a sixteenth-century Latin magical manuscript whose contents center on a set of complex alphabetic tables—36 matrices each containing 36 rows of 36 letters—believed to encode divine and angelic secrets. The text was famously owned by John Dee, who in 1583 asked the angel Uriel through his scryer Edward Kelley to explain the tables' significance; Uriel reportedly said that only the angel Michael could explain them and that the original was given to Adam in Paradise. This anecdote, recorded in Dee's diaries, has made the Soyga particularly resonant in the history of early modern esotericism.</p>
<p>The manuscript's scholarly fortunes changed dramatically when Jim Reeds, a mathematician at Bell Labs, cracked the algorithm generating the Soyga's tables in 1994—demonstrating that they were produced by a systematic procedure involving a keyword, a specific alphabet, and a recursive generation rule. Reeds' analysis, published in a paper circulated within Dee scholarship, showed that the tables were not random or arbitrary but encoded according to a consistent method, though the specific magical significance of the content remains unclear. This computational analysis illustrated how modern mathematical tools can illuminate aspects of historical magical texts that traditional philological methods cannot address.</p>
<p>Deborah Harkness's research on John Dee brought renewed scholarly attention to the Soyga as part of her investigation of Dee's magical projects and his relationship to Elizabethan learned culture. The text exemplifies the category of magical manuscript that circulated among educated practitioners in the sixteenth century—learned enough to require Latin literacy and mathematical sophistication, yet concerned with operations (angelic communication, access to divine secrets) that placed it firmly outside the bounds of orthodox religious practice. Its association with Dee connects it to the broader project of Enochian magic and the Elizabethan search for pristine angelic knowledge.</p>""",

    "buch_aller_verbotenen_kunst": """<h2>Buch aller verbotenen Kunst (c. 1456): Vernacular Taxonomy of Forbidden Arts</h2>
<p>Johannes Hartlieb's <em>Buch aller verbotenen Kunst, Unglaubens und der Zauberei</em> (Book of All Forbidden Arts, Superstition, and Sorcery, c. 1456) stands as one of the most important vernacular German treatments of magic from the fifteenth century. Written for Margrave Johann von Brandenburg, the text provided a systematic overview of forbidden arts in accessible German prose, making previously Latin-encoded knowledge about magic—both its condemnation and its description—available to a literate lay audience at the courts and in the towns of the German-speaking world. Its combination of moral condemnation with practical description made it simultaneously a warning against magical practice and an inadvertent handbook of its forms.</p>
<p>Hartlieb organized his exposition around the seven forbidden arts: nigromancy, geomancy, hydromancy, aeromancy, pyromancy, chiromancy, and spatulamancy (scapulomancy). This schema, derived from classical and medieval encyclopaedic tradition, gave the text a systematic character that distinguished it from less organized popular accounts of magical practices. Each art received a description of its procedures and goals alongside condemnation of its demonic basis and harm to practitioners. The enumeration and description of these arts—even in the context of condemnation—served to define and stabilize the category of "forbidden knowledge" for vernacular readers who would otherwise have had access only to fragmented oral and informal accounts.</p>
<p>The text's production context—a court physician writing for a noble patron—illuminates important aspects of fifteenth-century magical culture. The Wittelsbach court, like other major German noble establishments, was an environment where astrology, alchemy, and related practices coexisted with orthodox religious devotion, and where interest in the boundaries of natural and supernatural knowledge was genuine rather than merely prurient. Hartlieb's own career as a physician and court intellectual suggests that the <em>Buch aller verbotenen Kunst</em> engaged with these questions from a position of professional expertise, not merely clerical condemnation—making his vernacular taxonomy a document of early German humanism as much as of demonological literature.</p>""",

    "de_divinatione_daemonum": """<h2>De Divinatione Daemonum: Augustine on Demonic Foreknowledge</h2>
<p>Augustine of Hippo's <em>De divinatione daemonum</em> (On the Divination of Demons, c. 406–411) is a short but foundational text in the medieval theology of demonic knowledge, addressing the question of how demons appear to predict the future without possessing genuine foreknowledge. Written in response to pagan challenges concerning the apparent failure of traditional oracles and the apparent success of demonic soothsayers, the text elaborates a framework for understanding demonic knowledge that would prove enormously influential on subsequent medieval and early modern demonological thinking.</p>
<p>Augustine's argument centers on the claim that demons possess three natural advantages over humans that allow them to appear prophetic without actually knowing future contingencies: they have subtle, swift bodies that allow them to travel quickly and gather information unavailable to slow-moving humans; they have vast experience accumulated over long lifespans that allows them to recognize causal patterns and predict their likely outcomes; and they can perceive and interpret signs in nature—weather, stellar configurations, animal behavior—that humans either cannot read or cannot process quickly enough to be useful. These advantages produce apparent prophecy without requiring genuine foreknowledge, which Augustine holds belongs to God alone.</p>
<p>The text's importance for the history of magic lies in its establishment of a coherent theological account of how demonic divination works that avoids both the extremes of dismissing divinatory phenomena as mere illusion and conceding to demons genuine divine attributes. Subsequent medieval thinkers—Aquinas, Albertus Magnus, William of Auvergne—elaborated and refined Augustine's account, producing increasingly sophisticated demonological theories that grappled with the empirical appearance of successful magical prediction while maintaining the theological principle of divine sovereignty over the future. The <em>De divinatione daemonum</em> thus anchors a continuous tradition of theological reasoning about the powers and limits of demonic knowledge that shaped assessments of magical practice throughout the medieval period.</p>""",

    "de_imaginibus": """<h2>De Imaginibus: Thabit ibn Qurra and Talismanic Magic</h2>
<p>The text known in Latin as <em>De imaginibus</em> (On Images) and attributed to the ninth-century Sabian mathematician and astronomer Thabit ibn Qurra represents one of the most influential transmissions of Arabic talismanic magic into the medieval Latin West. The text provides instructions for creating astrological talismans—images, figures, or inscribed objects—at specific celestial conjunctions to capture and channel planetary or stellar influences for a variety of practical goals including healing, protection, and the influencing of persons and events. Its detailed operational instructions, combined with astrological rationale, made it a key source for Latin authors seeking to engage with image magic within a natural philosophical framework.</p>
<p>The text's attribution to Thabit ibn Qurra, while questioned by modern scholars, reflects the medieval strategy of anchoring magical texts in authoritative ancient or prestigious near-contemporary names. Thabit's genuine reputation as a mathematician and astronomer of the first rank—he translated Greek mathematical texts into Arabic and made original contributions to astronomy and number theory—lent credibility to a text making bold claims about celestial influence. Whether or not Thabit wrote anything like the text attributed to him, the attribution circulated widely and influenced the text's reception as legitimate natural philosophy rather than condemned superstition.</p>
<p>The <em>De imaginibus</em> occupies a central place in Nicole Weill-Parot's important study of "addressative" magic—that is, magic based on the idea that images or objects can be addressed to specific spiritual or celestial entities capable of conferring power. Her analysis situates the text within the debate about whether image magic relies on natural celestial causation (and is thus philosophically defensible) or on the implicit invocation of spiritual beings (and is thus condemned as demonic). This debate, which runs through the entire medieval treatment of talismanic and astrological magic, gave the <em>De imaginibus</em> its controversial significance: it was both a resource for those who sought to develop a natural philosophical account of magic and a target for those who insisted that any such account merely obscured underlying demonic dependency.</p>""",

    "de_occultis_operibus_naturae": """<h2>De Occultis Operibus Naturae: Aquinas on Hidden Natural Powers</h2>
<p>Thomas Aquinas's letter <em>De occultis operibus naturae</em> (On the Hidden Works of Nature, c. 1270) addresses a question fundamental to both natural philosophy and the theology of magic: what are the limits of natural causation, and how should we distinguish between genuine natural powers, miraculous divine intervention, and demonic illusion? Written in response to a question about the marvelous powers attributed to stones, herbs, and related substances in medieval natural magic literature, the text develops a framework for understanding "occult qualities"—genuine causal powers embedded in natural substances by the celestial influences that formed them—that significantly shaped subsequent medieval and Renaissance natural philosophy.</p>
<p>Aquinas's central argument draws on the Aristotelian account of form and the theory of celestial influence to explain how material substances can possess powers exceeding their obvious elemental composition. Just as a magnet attracts iron through a power that cannot be reduced to its elemental qualities of earth, water, fire, and air, so other substances may possess hidden powers (virtutes occultae) conferred by the specific celestial configuration present at their formation. These powers are genuinely natural, operating through efficient causation rather than through the mediation of spiritual beings—a crucial distinction for Aquinas, who wanted to preserve a space for legitimate natural magic (or "natural philosophy applied") separate from the demonic magic he condemned.</p>
<p>The text's influence extends through the subsequent debates about natural versus demonic magic that characterized both scholastic theology and Renaissance natural philosophy. Marsilio Ficino's theory of spiritus and his account of how talismans capture celestial influence drew on the same conceptual framework, as did the natural magic programs of Giovanni Battista della Porta and Giambattista della Porta. The occult qualities concept provided a vocabulary and a philosophical rationale for investigating hidden natural powers that remained productive until the mechanical philosophy's rejection of occult causation in the seventeenth century—and even then, the debate about what counted as genuine natural causation versus hidden spiritual agency retained the conceptual shape Aquinas had given it.</p>""",

    "fourth_book_occult_philosophy": """<h2>Fourth Book of Occult Philosophy (1559): Spurious Agrippa and Demonic Magic</h2>
<p>The text known as the <em>Fourth Book of Occult Philosophy</em>, first published in 1559 and falsely attributed to Heinrich Cornelius Agrippa, represents an important episode in the history of Renaissance magical publishing. Appearing several years after Agrippa's death, the text purported to provide the practical operational instructions that Agrippa had supposedly withheld from his genuine three-volume <em>De Occulta Philosophia</em>—constituting the "fourth book" that would complete the published trilogy with actual procedures for summoning spirits. Modern scholarship has conclusively demonstrated that the text is not by Agrippa; it draws instead on the <em>Heptameron</em> attributed to Peter of Abano and other sources, compiled by an unknown hand who exploited Agrippa's prestigious name to market a practical grimoire.</p>
<p>The spurious Fourth Book illustrates broader dynamics in early modern magical publishing. Agrippa's genuine <em>De Occulta Philosophia</em> had achieved wide circulation and considerable prestige as the most systematic philosophical treatment of Renaissance learned magic; attaching a practical companion piece to that prestigious name created an immediately marketable product for readers seeking operational guidance. The association also provided a measure of philosophical legitimation for content that, standing alone, might have been more obviously condemned as a practical grimoire rather than natural philosophy.</p>
<p>The text's contents include instructions for conjuring spirits using circles, fumigations, and divine names, as well as a version of the Heptameron's system for calling angels of the hours and planetary spirits. Its publication contributed to the early modern consolidation of the Solomonic and theurgical magic traditions into accessible printed form, a process that transformed what had been a manuscript culture of specialized clerical practitioners into a printed literature accessible to anyone literate in Latin. This transformation had complex effects: it democratized access to learned magic while simultaneously making it easier for authorities to identify and condemn specific texts and practices.</p>""",

    "grimorium_verum": """<h2>Grimorium Verum: The True Grimoire and Its Hierarchy of Spirits</h2>
<p>The <em>Grimorium Verum</em> (True Grimoire) is an eighteenth-century magical text, first published purportedly in Memphis in 1817 (though earlier manuscript versions likely exist) and attributed to "Alibek the Egyptian." Despite its relatively late appearance in print, the text draws on earlier magical traditions—particularly the Solomonic and demonic conjuration literature of the sixteenth and seventeenth centuries—and has attracted significant scholarly and practitioner interest because of its frank presentation of demonic magic without the apologetic framing found in texts like the Arbatel. The <em>Grimorium Verum</em> presents itself as providing access to real demonic powers for practical ends, without much attempt to disguise this character under philosophical or theological legitimation.</p>
<p>The text's spirit hierarchy is distinctive: rather than the seventy-two demons of the Goetia or the planetary angels of more celestially-oriented texts, the <em>Grimorium Verum</em> organizes its spirits under three principal demons (Lucifer, Beelzebuth, and Astaroth) with subordinate spirits possessing specific practical competences. This organizational scheme reflects the demonological systematizing characteristic of grimoire literature while presenting it in a more baldly operational register than texts claiming philosophical foundations. The practical focus—obtaining specific results through specific demons—aligns the text with the tradition of "experimental" or "practical" magic that bypassed theoretical justification in favor of tested procedures.</p>
<p>Jake Stratton-Kent's modern scholarly edition and study of the <em>Grimorium Verum</em> (2009) has brought this text to new scholarly attention, situating it within the broader tradition of grimoire literature and arguing for its connections to earlier, possibly ancient, magical traditions. While Stratton-Kent's arguments have been received with varying degrees of scholarly acceptance, his work exemplifies the contemporary intersection of academic historical research and living magical practice that characterizes much current scholarship on grimoire texts, where critical engagement with historical evidence coexists with interest in the texts as functional magical resources.</p>""",

    "heptameron": """<h2>Heptameron seu Elementa Magica: Planetary Angels and Ritual Hours</h2>
<p>The <em>Heptameron seu Elementa Magica</em> (Heptameron, or Elements of Magic), attributed to Peter of Abano (c. 1250–1316) though likely composed by a later author, is one of the most widely circulated practical magical texts of the Renaissance period. Organized around the seven days of the week and the angels governing each day's hours, the text provides detailed instructions for summoning angels through properly constructed circles, appropriate fumigations, and specific divine and angelic names. Its combination of celestial organization, ritual precision, and Solomonic authority made it a foundational reference for practical ceremonial magic in the fifteenth through seventeenth centuries.</p>
<p>The attribution to Peter of Abano—the prominent Italian physician and philosopher whose <em>Conciliator</em> and other works made him a leading figure in the Latin reception of Arabic natural philosophy—is almost certainly pseudepigraphical, exploiting his established reputation as a learned investigator of hidden natural powers. Peter's genuine work engaged seriously with astrological medicine and occult qualities, making him a plausible attributed author for a text claiming that planetary angels could be summoned through celestially synchronized ritual. Whether or not he wrote anything resembling the Heptameron, the attribution placed the text's practical magic within a framework of natural philosophical investigation rather than mere superstition.</p>
<p>The text's practical instructions are detailed and systematic: for each day and hour, it specifies the governing angel, the appropriate circle construction, the names to be used in invocation, and the fumigations suitable for the planetary hour. This systematic completeness—covering all days, all hours, all planets—gave the text a comprehensive character that made it useful as a practical reference. Its wide circulation in manuscript and early printed editions (often appended to editions of Agrippa's <em>De Occulta Philosophia</em> or published with the spurious Fourth Book) made it one of the most accessible and influential practical magic texts of the Renaissance period, exercising formative influence on the later Solomonic tradition.</p>""",

    "liber_de_angelis": """<h2>Liber de Angelis: Medieval Angel Magic and Practical Conjuration</h2>
<p>The <em>Liber de Angelis</em> (Book of Angels) is a medieval Latin magical compilation preserved in several manuscript versions from the fourteenth and fifteenth centuries, providing practical instructions for invoking and working with angels for a variety of purposes including healing, protection, acquiring knowledge, and influencing persons and events. The text occupies the contested territory between legitimate Christian veneration of angels and condemned magical conjuration, claiming divine and angelic sanction for its procedures while providing operational instructions whose practical orientation connects it to the broader learned magic tradition.</p>
<p>The text draws on the rich medieval tradition of angelology that assigned specific names, powers, and spheres of responsibility to vast hierarchies of angels derived from Jewish, Christian, and ultimately Babylonian and Persian cosmological speculation. The association of specific angels with days, hours, planets, and zodiacal signs—elaborated in texts like the <em>Sepher ha-Razim</em>, the <em>Heptameron</em>, and countless liturgical and paraliturgical sources—provided practitioners with a systematic framework for identifying which angel to address for which purpose and when. The <em>Liber de Angelis</em> applied this angelological knowledge in explicitly operational directions, providing the names, seals, and ritual procedures for actual invocation.</p>
<p>Scholarly work on texts like the <em>Liber de Angelis</em> has been part of a broader effort to map the full range of medieval learned magical literature beyond its canonical exemplars. Researchers including Julien Véronèse, Claire Fanger, and Frank Klaassen have demonstrated that the medieval magical corpus encompasses a far greater variety of texts—in terms of content, purpose, and intended audience—than earlier scholarship recognized. The <em>Liber de Angelis</em> contributes to this picture by providing evidence for the persistence and practical application of angel magic traditions in contexts where practitioners sought benevolent spiritual assistance rather than the compulsion of demons.</p>""",

    "liber_experimentorum": """<h2>Liber Experimentorum: The Experimental Magic Tradition</h2>
<p>The term <em>Liber Experimentorum</em> (Book of Experiments) designates a category of medieval Latin magical text rather than a single fixed work; multiple compilations bearing this or similar titles (also <em>experimenta</em>, <em>probata</em>) circulated in manuscript from the thirteenth century onward, sharing a common format of practical recipes and procedures for magical operations validated by the claim that they had been "tried and tested" (experimentata). This genre represents one of the most practically oriented sectors of the learned magic tradition, focused less on theoretical justification than on operational efficacy and the transmission of techniques that supposedly worked.</p>
<p>The experimenta tradition occupied a complex position in the taxonomy of learned magic. On one hand, it shared with natural magic literature the format of practical recipes and the appeal to empirical validation; on the other hand, many experimenta involved procedures—invocations of spirits, use of divine names, precise ritual protocols—that could not easily be reduced to natural causation. Frank Klaassen's research on this tradition has emphasized its characteristic ambivalence: experimenta manuscripts often juxtapose material from different magical registers without apparent concern for their theoretical compatibility, reflecting the practical priorities of their compilers over systematic theoretical coherence.</p>
<p>The audience for experimenta literature appears to have been considerably broader than for more theoretically elaborate magical texts. The recipe format, the vernacular alongside Latin versions, and the focus on concrete achievable goals suggest compilation and use by practitioners ranging from learned clerics seeking professional advantages (memory, eloquence, favor with powerful persons) to more modest users seeking healing, protection, or practical assistance in everyday matters. This breadth of audience makes experimenta compilations valuable evidence for the social distribution of magical practice across medieval Europe, demonstrating that learned magic was not confined to elite philosophical practitioners but participated in a wider culture of practical problem-solving through ritual technique.</p>""",

    "liber_juratus_honorii": """<h2>Liber Juratus Honorii: The Sworn Book of Honorius</h2>
<p>The <em>Liber Juratus Honorii</em> (Sworn Book of Honorius), also known as the <em>Liber Sacer</em>, is one of the most ambitious and complex magical texts of the medieval period, claiming to represent the distilled essence of the entire magical tradition assembled by a council of master magicians at the instigation of the angel Hocroel. The text's elaborate frame narrative presents it as the product of a congress of ninety magic masters who, threatened by papal and episcopal persecution, decided to preserve their knowledge in a single book to be sworn to secrecy and transmitted only to worthy initiates. This origin legend—itself a sophisticated piece of legitimating fiction—gives the text a self-conscious sense of representing a persecuted tradition of authentic wisdom.</p>
<p>The text's content reflects its synthetic ambitions: it includes a comprehensive theory of the created order, detailed instructions for achieving a vision of God (the beatific vision) through sustained magical practice, a lengthy ritual for summoning angels and spirits of the four directions, extensive lists of divine names, and practical operations for a wide range of goals. The beatific vision section is particularly distinctive, presenting the acquisition of divine knowledge as the highest goal of magical practice—a goal that claims to transcend mere practical magic and participate in the tradition of Christian mysticism. This theological ambition distinguishes the Sworn Book from purely operational texts and connects it to the learned magic tradition's persistent aspiration to reconcile magical practice with Christian spiritual aspiration.</p>
<p>Gösta Hedegård's critical edition (2002) established a reliable Latin text based on manuscript comparison and provided the scholarly foundation for subsequent analysis. Researchers including Julien Véronèse and Sophie Page have situated the Sworn Book within the broader context of clerical learned magic and the contested transmission of magical knowledge in medieval Europe. The text's claim to represent an endangered tradition preserved against persecution resonates with actual historical circumstances—the repeated condemnation of magical texts by councils, bishops, and papal authority—suggesting that its frame narrative, however fictive in its specifics, reflects genuine anxiety about the survival of this kind of knowledge.</p>""",

    "liber_lunae": """<h2>Liber Lunae: The Book of the Moon and Lunar Magic</h2>
<p>The <em>Liber Lunae</em> (Book of the Moon) is a Latin magical text drawing on Arabic lunar magic traditions, providing instructions for working with the twenty-eight mansions of the moon to achieve a variety of practical goals. The lunar mansions—divisions of the moon's monthly circuit through the zodiac—were associated in Arabic astronomical-magical literature with specific angels, spirits, and influences that could be engaged through appropriately timed ritual operations. The Latin <em>Liber Lunae</em> belongs to the substantial body of Arabic magical literature translated into Latin during the twelfth and thirteenth centuries that brought this tradition into the Western European learned magic corpus.</p>
<p>The lunar mansion system represented a comprehensive framework for timing magical operations according to the moon's position in its cycle, providing an accessible celestial calendar for practitioners who might lack the expertise to calculate planetary positions but could track the moon's progress through the familiar zodiacal signs. Each mansion received a name (often Arabic or pseudo-Arabic in the Latin versions), an associated spirit or angel, and a specification of the operations for which it was favorable or unfavorable. This systematic organization made the <em>Liber Lunae</em> a practical reference tool for integrating astrological timing into magical operations of all kinds.</p>
<p>The text's transmission history reflects the multilingual, multicultural character of medieval magical literature. Arabic originals were translated into Latin through the same networks that transmitted astronomical, mathematical, and medical texts from Islamic to Christian Europe, with the Spanish translation schools of the twelfth century playing a particularly important role. The integration of Arabic lunar magic into Latin learned magic produced hybrid texts that combined Islamic angelological and cosmological frameworks with Christian ritual idioms, creating the characteristic synthetic character of medieval European learned magic. Scholars including David Pingree and Charles Burnett have documented these transmission processes, tracing the specific routes through which Arabic magical concepts entered the Latin tradition.</p>""",

    "liber_theysolius": """<h2>Liber Theysolius: An Attributed Magical Compilation</h2>
<p>The <em>Liber Theysolius</em> is a Latin magical text attributed to the otherwise obscure figure of Theysolius, belonging to the tradition of medieval learned magic compilations that claimed ancient authority through pseudepigraphical attribution. Like many texts in this genre, the Liber Theysolius draws on diverse sources—spirit lists, ritual procedures, divine name sequences, and operational instructions—assembled under a single attributed authority to constitute a usable magical reference. The text's content situates it within the broader experimental magic tradition of the thirteenth through fifteenth centuries.</p>
<p>The compilation's significance lies partly in what it reveals about the practices of magical text production and transmission in medieval Europe. Compilations like the Liber Theysolius were assembled by practitioners who drew on available sources—other magical texts, oral traditions, astrological lore, angelological speculation—and organized them under convenient attributed authorities. The resulting texts were neither simple copies of sources nor entirely original compositions, but products of a creative compilation process that was itself a recognized form of learned activity. The attribution to Theysolius, like attributions to Solomon, Hermes, or Apollonius elsewhere, served to anchor this compiled material in claimed ancient wisdom.</p>
<p>Scholarly recovery of texts like the Liber Theysolius has been part of the broader project, undertaken by researchers including Frank Klaassen and Richard Kieckhefer, to document the full range of medieval magical literature beyond the canonical texts most frequently discussed. Manuscript catalogues, critical editions, and comparative studies have gradually mapped the scope of this literature, revealing a much larger and more diverse corpus than earlier scholarship recognized. Minor texts like the Liber Theysolius contribute to this picture by providing evidence for the variety of practices, traditions, and attributed authorities that populated the medieval magical imagination beyond its most famous exemplars.</p>""",

    "magic_in_medieval_manuscripts": """<h2>Magic in Medieval Manuscripts (2010): A Visual and Textual Survey</h2>
<p>Sophie Page's <em>Magic in Medieval Manuscripts</em> (2010), published by the British Library, provides an accessible yet scholarly introduction to magical texts and their manuscript contexts through the British Library's extensive collections. The volume combines analysis of magical content with attention to the material and visual dimensions of magical manuscripts—their scripts, illustrations, diagrams, and physical form—demonstrating how the study of manuscripts as objects, rather than merely as vehicles for textual content, can illuminate the practices and communities that produced and used them. Page's expertise in medieval magic and manuscript culture makes the volume both an authoritative scholarly resource and an effective guide for general readers encountering this material for the first time.</p>
<p>The book's coverage ranges from the Anglo-Saxon period through the late Middle Ages, examining texts in Latin, Middle English, and other vernaculars. It addresses the full spectrum of magical literature from theoretical demonology and natural magic to practical grimoires and popular charms, situating each within its historical and cultural context. Particular attention is paid to the visual elements of magical manuscripts: the elaborate diagrams of the Ars Notoria, the spirit seals of Solomonic texts, the astronomical tables of astrological magic, and the illustrated charms of vernacular tradition. These visual components are integral to the magical function of the texts themselves, not merely decorative additions.</p>
<p>Page's approach illustrates a broader methodological turn in the study of medieval magic toward attention to the material dimensions of textual transmission. Rather than treating manuscripts as neutral containers for textual content, scholars in this tradition examine the physical properties of manuscripts—parchment type, binding, marginal annotations, signs of use—as evidence for how texts were read, stored, and transmitted. This material philology has revealed important information about the social contexts of magical text production and use, suggesting audiences and practices that analysis of content alone would miss. The British Library's collections, rich in magical manuscripts of all periods and traditions, make them an ideal platform for this kind of investigation.</p>""",

    "magic_of_rogues": """<h2>Magic of Rogues: The Underworld of Late Medieval Magic</h2>
<p>The study of what might be called "rogue magic"—magical practices operating outside the learned clerical tradition, in the spaces of urban popular culture, traveling entertainers, confidence men, and social margins—reveals dimensions of medieval and early modern magical culture that the learned tradition's self-representation often conceals. Richard Kieckhefer's analysis in <em>Magic in the Middle Ages</em> and related work, along with studies by Michael Bailey and others, has attended to the intersection of learned and popular magic in social contexts where the boundaries between legitimate and condemned practice were negotiated in everyday life rather than in academic treatises.</p>
<p>The figure of the professional magician—the itinerant practitioner who offered magical services for payment, sometimes drawing on genuine learned texts and sometimes fabricating claims to knowledge—occupies an important but elusive place in the history of magic. Such figures appear in court records, in satirical literature, and in moralizing condemnations, but rarely left self-descriptions that would allow reconstruction of their actual practices. The overlap between their operations and those of more respectable practitioners (court astrologers, university-trained physicians, learned clerics who wrote magical texts) was considerable, suggesting that the social boundary between legitimate and illegitimate magic was less about the content of practices than about the social position and institutional affiliation of practitioners.</p>
<p>The study of rogue magic intersects with broader social histories of poverty, migration, gender, and religious marginality in medieval and early modern Europe. Women healers, cunning folk, itinerant charm-sellers, and others who operated outside institutional structures of learning and ecclesiastical authority practiced forms of magic that drew on the same cosmological assumptions as learned magic while operating through different social channels. Understanding this dimension of magical culture requires sources—court records, ecclesiastical visitiation documents, folk narrative collections—that complement the learned texts typically studied by historians of magic, producing a more complete picture of magic as a social and cultural phenomenon.</p>""",

    "monas_hieroglyphica": """<h2>Monas Hieroglyphica (1564): John Dee's Symbol of Universal Harmony</h2>
<p>John Dee's <em>Monas Hieroglyphica</em> (Hieroglyphic Monad, 1564), dedicated to Maximilian II of Bohemia and published in Antwerp, presents an elaborate interpretation of a single symbol—the "monad"—that Dee claimed encoded the principles of all knowledge including mathematics, astronomy, alchemy, and celestial magic. The symbol itself combined elements from several traditional astronomical and alchemical signs (those of the sun, moon, the elements, and the fire of Aries) into a single hieroglyphic figure that Dee believed expressed fundamental truths about the structure of reality. The text's dense, allusive prose and its engagement with Cabalistic number theory, Pythagorean mathematics, and symbolic alchemy make it one of the most difficult and contested texts in the history of Renaissance esotericism.</p>
<p>Dee's ambitions for the Monas were extraordinary: he believed he had discovered a universal symbolic language that would reunite the fragmented knowledge of humanity, reveal the hidden correspondences binding the created order, and potentially serve as the basis for a reformed natural philosophy integrating mathematics, observation, and esoteric insight. The text's reception was mixed: some contemporaries regarded it as profound, while others found it incomprehensible. William Gilbert reportedly dismissed it as obscure; the Elizabethan mathematician Thomas Digges found mathematical value in it. The text's engagement with continental Cabalistic and Hermetic traditions suggests that Dee intended it for an audience of learned Europeans familiar with those traditions rather than for general readership.</p>
<p>The <em>Monas Hieroglyphica</em> has attracted substantial scholarly attention as a document of Dee's intellectual ambitions and his engagement with Renaissance esotericism. Nicholas Clulee's study of Dee's natural philosophy situates the Monas within Dee's larger intellectual project of reforming learning through mathematical and symbolic investigation. Deborah Harkness's work further connects the Monas to Dee's subsequent angelic conversations, suggesting that the symbolic program of the Monad provided a conceptual framework that Dee later pursued through spirit communication. The text thus occupies a pivotal position in Dee's intellectual biography, between his earlier natural philosophical work and his later more explicitly magical and prophetic projects.</p>""",

    "mysteriorum_libri": """<h2>Mysteriorum Libri: John Dee's Angelic Conversations</h2>
<p>John Dee's <em>Mysteriorum Libri</em> (Books of Mysteries), together with related diaries and records, documents one of the most remarkable projects of spirit communication in the history of Western esotericism. Beginning in 1583 and continuing intermittently until the early 1590s, Dee and his scryer Edward Kelley conducted hundreds of sessions in which Kelley gazed into a crystal or obsidian mirror (the "shewstone") and reported communications from angels who identified themselves variously as Uriel, Michael, Gabriel, Nalvage, and others. These communications were recorded in elaborate detail by Dee himself, producing a voluminous archive of angelic dictations that included a new language (Enochian), a system of tables and calls for communicating with celestial beings, and prophecies about European politics and the imminent end of the world.</p>
<p>The Dee-Kelley sessions operated within a specific theological framework: Dee understood himself not as a sorcerer but as a pious Christian philosopher seeking authentic divine communication in the tradition of the biblical prophets and the ancient patriarchs who had received divine wisdom directly from God. His angels were presented not as the demons of the grimoire tradition but as genuine celestial beings conveying authentic heavenly knowledge to a chosen recipient. This self-presentation allowed Dee to pursue what was functionally spirit communication while maintaining his sense of himself as a legitimate religious and philosophical investigator.</p>
<p>Deborah Harkness's groundbreaking study <em>John Dee's Conversations with Angels</em> (1999) provided the first comprehensive scholarly analysis of the angelic diaries, situating them within the intellectual, religious, and political context of Elizabethan England and continental European esotericism. Her analysis demonstrated that the diaries are neither records of deliberate fraud (as some have argued) nor evidence of Dee's credulity, but products of a sophisticated intellectual project that engaged seriously with contemporary questions about the nature of knowledge, divine communication, and the reformation of learning. The Dee-Kelley sessions represent a culminating expression of the Renaissance magical tradition's aspiration to recover pristine ancient wisdom through direct spiritual contact.</p>""",

    "oration_dignity_man": """<h2>Oration on the Dignity of Man (c. 1486): Pico della Mirandola and Human Freedom</h2>
<p>Giovanni Pico della Mirandola's <em>Oratio de hominis dignitate</em> (Oration on the Dignity of Man, c. 1486/1487), though never delivered as planned—it was written as the introduction to 900 theses Pico proposed to debate in Rome before the project was condemned—became one of the most celebrated texts of Italian Renaissance humanism and remains central to understanding Renaissance magical philosophy. The Oration's famous opening, in which God addresses Adam and declares him a being of undetermined nature who may freely choose to ascend toward the divine or descend toward the bestial, articulated a vision of human dignity founded on freedom and self-determination that resonated deeply with Renaissance magical ambitions.</p>
<p>The Oration's significance for the history of magic lies in its framework for human agency in relation to the cosmos. If humans are uniquely self-forming beings who can choose to ascend through the celestial hierarchies toward mystical union with the divine, then magical practice—understood as the discipline through which this ascent is accomplished—takes on a different character than in earlier frameworks. Rather than transgressing proper human limits by seeking demonic aid or presuming on divine knowledge, the Renaissance mage described by Pico is exercising the essential human capacity for self-transformation, rising through natural, mathematical, and Cabalistic disciplines toward the highest form of philosophical life.</p>
<p>The proposed 900 theses that the Oration was to introduce drew explicitly on Jewish Kabbalah as a resource for Christian theology and philosophical magic, arguing that Cabalistic interpretation of Scripture confirmed the truth of Christianity while providing resources for practical spiritual ascent. The condemnation of thirteen of these theses by a papal commission in 1487 forced Pico into temporary exile and contributed to the cautious, apologetic register in which subsequent Renaissance magicians often presented their work. The Oration, never published in Pico's lifetime, circulated in manuscript and appeared in print posthumously, becoming foundational for both Renaissance Neoplatonism and the long tradition of humanist celebration of human freedom and self-creation.</p>""",

    "polygraphia_trithemius": """<h2>Polygraphia (1518): Trithemius and the Science of Cryptography</h2>
<p>Johannes Trithemius's <em>Polygraphia</em> (1518), published posthumously, represents one of the earliest systematic treatments of cryptography in the Western tradition. Building on his earlier and more controversial <em>Steganographia</em>, the <em>Polygraphia</em> provided a comprehensive system for secret writing based on multiple substitution alphabets—a polyalphabetic cipher of considerable sophistication for its time. Unlike the <em>Steganographia</em>, whose system of secret communication was embedded within a framework of spirit communication that attracted charges of demonic magic, the <em>Polygraphia</em> presented its system in more transparent terms as a practical art of secret writing for diplomatic and administrative use.</p>
<p>The relationship between cryptography and magic in Trithemius's work reflects a broader early modern fascination with hidden communication, secret writing, and the transmission of knowledge beyond the reach of ordinary perception. The same intellectual environment that produced systems of magical signs and characters—notarikon, temurah, and other Hebrew Cabalistic letter arts; the characters and seals of grimoire magic—also produced systematic cryptographic analysis. Both traditions assumed that meaning could be encoded in surface appearances that concealed deeper significance, and both developed systematic methods for encoding and decoding such hidden meaning. Trithemius's movement between magical and cryptographic registers was thus less paradoxical than it might appear: both served his interest in concealed communication.</p>
<p>The modern significance of the <em>Polygraphia</em> lies primarily in its place in the history of cryptography, where Trithemius is recognized as a pioneer of polyalphabetic substitution. The Trithemius cipher, a systematic progression through alphabetic substitutions, became foundational for subsequent cryptographic development including the Vigenère cipher. In the history of magic, the <em>Polygraphia</em> is significant as a demonstration that the same intellectual resources—systematic analysis of letter combinations, attention to surface and depth in textual meaning—could be applied to both magical and cryptographic purposes, illustrating the complex relationship between Renaissance learned magic and the emerging natural sciences of the sixteenth century.</p>""",

    "sixth_and_seventh_books_of_moses": """<h2>Sixth and Seventh Books of Moses: Kabbalistic Magic and Popular Tradition</h2>
<p>The <em>Sixth and Seventh Books of Moses</em> is an eighteenth-century German magical compilation that presents itself as the continuation of the Pentateuch—the five books attributed to Moses—providing the secret magical knowledge that Moses supposedly possessed but withheld from public scripture. First printed in German in the 1780s and repeatedly reprinted thereafter, the text synthesizes learned Kabbalistic material, divine names, seals, and practical magic instructions within a frame that claims Mosaic authority for its contents. This attribution strategy represents a late example of the pseudepigraphical tradition that had long legitimated magical texts by attaching them to biblical figures.</p>
<p>The text achieved remarkable cultural reach, spreading far beyond its German origins through immigration and diaspora networks. German immigrants to Pennsylvania brought it to North America in the eighteenth and nineteenth centuries, where it became foundational for the Pennsylvania German <em>Pow-Wow</em> tradition of folk magic. More dramatically, it was carried to West Africa and the Caribbean through the slave trade and colonial networks, where it was integrated into syncretic religious and magical traditions including Hoodoo, Obeah, and various Afro-Caribbean spiritual practices. This global trajectory—from German printing house to African American conjure tradition—illustrates the extraordinary mobility of printed magical texts and the creative adaptations they underwent as they crossed cultural boundaries.</p>
<p>Scholarly study of the Sixth and Seventh Books of Moses has been enriched by ethnographic and folklore research on its reception communities alongside historical research on its textual origins. Sabina Magliocco and other folklorists have documented its persistence in living traditions, while historians of print culture have traced its publication history and textual evolution. The text's significance lies as much in its reception and adaptation as in its original content: its transformations as it moved from German learned magic to Pennsylvania folk practice to African American conjure tradition demonstrate how magical texts function as cultural resources that communities reshape to meet their specific needs and cosmological frameworks.</p>""",
}

def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    updated = 0

    for slug, html in CONCEPT_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM concepts WHERE slug=?", (slug,)).fetchone()
        if row:
            conn.execute("UPDATE concepts SET definition_long=? WHERE slug=?", (html, slug))
            print(f"  concept: {slug} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING concept: {slug}")

    for person_id, html in PERSON_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM persons WHERE person_id=?", (person_id,)).fetchone()
        if row:
            conn.execute("UPDATE persons SET bio_html=? WHERE person_id=?", (html, person_id))
            print(f"  person: {person_id} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING person: {person_id}")

    for text_id, html in TEXT_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM texts WHERE text_id=?", (text_id,)).fetchone()
        if row:
            conn.execute("UPDATE texts SET analysis_html=? WHERE text_id=?", (html, text_id))
            print(f"  text: {text_id} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING text: {text_id}")

    conn.commit()
    print(f"\nUpdated {updated} entries.")
    conn.close()

if __name__ == "__main__":
    main()
