"""
Enrich batch 7: remaining concepts + persons (batch A).
"""
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import DB_PATH


CONCEPT_ENRICHMENTS = {

"amulets": """<h2>Definition</h2>
<p>Hybrid Term. An amulet (from Latin <em>amuletum</em>, possibly connected to Arabic <em>hamala</em>, to carry) is a physical object worn or carried for protective or beneficial purposes, whose efficacy is attributed to its material, form, inscribed text, or the circumstances of its production rather than to any ordinary mechanical property. Amulets differ from talismans in emphasis — amulets are typically protective, worn on the body, and relatively simple; talismans are more commonly operative (aimed at achieving specific ends), more elaborately produced under astrological conditions, and often not worn — though the boundary is fluid and contested in both the primary sources and the scholarly literature.</p>

<h2>Types and Materials</h2>
<p>Medieval amulet production covered an enormous range: inscribed parchment strips worn in leather pouches (phylacteries); rings with carved gemstones; metal discs or plates bearing divine names; herbs, stones, and animal parts with specific properties; and written texts of prayers or Gospel passages deployed as protective objects. Don Skemer's <em>Binding Words: Textual Amulets in the Middle Ages</em> (Pennsylvania State University Press, 2006) is the most comprehensive study of the textual amulet tradition, documenting how written texts — from simple transcriptions of the opening of John's Gospel to complex Solomonic seal-sequences — were produced and used as material protective objects across the medieval period.</p>
<p>Gideon Bohak's <em>Ancient Jewish Magic</em> (Cambridge, 2008) provides the essential background for the Jewish amulet tradition: Hebrew and Aramaic amulets on metal lamellae, on papyrus, and in incantation bowls, bearing divine names, angelic seals, and protective formulas, document a continuous tradition from the late antique period through the medieval Genizah texts. The overlapping between Jewish amulet practice and the Latin and Greek amulet traditions reflects the shared magical culture of the Mediterranean world.</p>

<h2>Theological Status</h2>
<p>Amulets occupied an ambiguous theological position. The use of divine names, Gospel texts, or prayers as protective objects could be construed as a form of legitimate religious practice (trusting in the power of God's word) or as superstition (attributing magical efficacy to the material object rather than to God). Thomas Aquinas's <em>Summa theologiae</em> II-II, q. 96, a. 4 allows the wearing of written divine names and scriptural texts when the wearer's trust is placed in God rather than in any special power of the writing itself; he condemns amulets that include unknown characters, unintelligible words, or content suggesting demonic cooperation. This nuanced position left wide scope for practical pastoral tolerance of amulet use while maintaining a theoretical boundary against explicitly magical objects.</p>""",

"charms": """<h2>Definition</h2>
<p>Actor Term. A charm (from Latin <em>carmen</em>, a song, verse, or incantation; Old English <em>gealdor</em>, enchantment) is a verbal formula — spoken, sung, or written — whose repetition produces a desired effect: healing, protection, causing harm, or binding. Charms are the most widespread and socially distributed form of magical practice in medieval and early modern Europe, appearing at every social level from village healing to royal courts, and across the entire period from late antiquity to the early modern era. The term overlaps with "spell," "incantation," and "adjuration" but tends to be used for simpler, less formally ritualized formulas than the elaborate conjurations of the learned grimoire tradition.</p>

<h2>Charm Tradition and Its Study</h2>
<p>Medieval charms survive in enormous numbers: hundreds of vernacular charms in Old English, Middle English, Low German, Old Norse, and other languages are preserved in manuscript collections, often alongside medical recipes and herbal prescriptions. The charm tradition is overwhelmingly practical: formulas for healing specific ailments (stanching blood, curing fever, removing worms from animals), for protection against specific dangers (theft, attack, storm), and for productivity (making butter churn, bees swarm to a hive). Lea Olsan's work on Middle English medical charms and the essays collected in Karen Louise Jolly's <em>Popular Religion in Late Saxon England</em> (1996) provide the most systematic analysis of the English charm tradition.</p>
<p>The theological status of charms was contested but their practical prevalence was acknowledged even by their critics. Penitentials from the sixth century onward list charm-use among the practices for which priests were expected to impose penances, while simultaneously noting that similar-sounding practices (reciting the Pater Noster over a sick person, anointing with blessed oil) were orthodox. The boundary between a charm and a prayer was often a matter of context, authorization, and the identity of the agent invoked rather than of the verbal formula itself.</p>

<h2>Scholarship</h2>
<p>Lea Olsan's work on medical charms in medieval manuscripts is the foundational analysis of the English tradition. For Anglo-Saxon England, Karen Louise Jolly's <em>Popular Religion in Late Saxon England</em> (University of North Carolina Press, 1996) and the essays in her edited volumes provide essential context. Tony Hunt's <em>Popular Medicine in Thirteenth-Century England</em> (Brewer, 1990) documents vernacular charm traditions. For Continental Europe, Don Skemer's <em>Binding Words</em> (2006) and the essays in Sophie Page and Catherine Rider (eds.), <em>The Routledge History of Medieval Magic</em> (2019) provide broad coverage.</p>""",

"familiar_spirit": """<h2>Definition</h2>
<p>Actor Term (primarily English usage). A familiar spirit, or simply "familiar," designates a supernatural entity — demon, spirit, or ambiguous being — that serves a witch or magician in a close, ongoing relationship, typically assisting with magical operations in exchange for some form of sustenance or compact. The concept is most prominent in early modern English witchcraft literature and trial records, where familiars are typically described as small animals (cats, toads, dogs, mice, ferrets) that suckle from a "witch's mark" on the accused's body. The familiar concept in this specific form is distinctively English; Continental European witchcraft literature tends to use different frameworks (the demonic pact, the sabbath) rather than the domestic animal familiar.</p>

<h2>Origins and Development</h2>
<p>The animal familiar in English witchcraft literature emerges primarily in trial records from the 1560s onward and is elaborated in witchcraft pamphlets and trial accounts through the seventeenth century. Emma Wilby's <em>Cunning Folk and Familiar Spirits: Shamanistic Visionary Traditions in Early Modern British Witchcraft and Magic</em> (Sussex Academic Press, 2005) provides the most sustained scholarly analysis, arguing that the animal familiar concept has deep roots in the visionary and spirit-companion traditions of folk healing — cunning folk also claimed familiar spirits, understood as fairy or spirit helpers — that were reinterpreted in demonological terms as the trials proceeded.</p>
<p>In learned magic, the category of familiar spirit overlaps with the concept of the "personal spirit" or "daemon" in Neoplatonic and Hermetic tradition: every human being has a guiding spirit (the classical <em>daimon</em> or <em>genius</em>) that can be cultivated and consulted. The Solomonic tradition of binding specific named demons to serve the magician provides a related but distinct framework. John Dee's angel communicants occupy yet another category: rational, personal, angelic beings in ongoing relationship with the practitioner. The category of "familiar spirit" in English law (the Witchcraft Act of 1563 explicitly prohibited "entertaining, employing, feeding or rewarding" a familiar spirit) was broad enough to cover all these variants.</p>""",

"neoplatonism_and_magic": """<h2>Definition</h2>
<p>Analyst Term. "Neoplatonism and magic" designates the relationship between the philosophical tradition of Plotinus, Iamblichus, Proclus, and Pseudo-Dionysius and the magical practices — theurgy, ritual, talisman-making, spirit-working — that were embedded in some branches of that tradition and that shaped Renaissance learned magic through Ficino's recovery and promotion of Neoplatonic philosophy. The relationship is complex because Neoplatonism is not a single tradition: Plotinus himself was sceptical about ritual efficacy, while Iamblichus and Proclus endorsed theurgy (ritual operations aimed at union with the divine) as a higher form of philosophical practice than purely intellectual contemplation.</p>

<h2>Plotinus and the Problem of Efficacy</h2>
<p>Plotinus's <em>Enneads</em> acknowledge that magical operations can produce real effects — they exploit the natural sympathies that connect all things through the world-soul — but Plotinus himself was unimpressed by this. The wise man, he argued, would not use such techniques because they operate on the lower soul and distract from the intellectual ascent toward the One. The sage is "immune to magic" precisely because he has detached himself from the sympathetic network that makes magic possible.</p>
<p>Iamblichus, in his <em>De mysteriis</em> (a response to Porphyry's letter to Anebo questioning whether theurgy worked), defended ritual as essential to the philosopher's ascent: purely intellectual philosophy cannot achieve union with the divine because the divine transcends intellect; it is through theurgy — ritual acts that mirror the divine order and invoke divine response — that the philosopher completes his ascent. Iamblichus's defence of theurgy provided the philosophical grounding for practical magical ritual that Ficino and subsequent Renaissance magicians drew on.</p>

<h2>Renaissance Reception</h2>
<p>D.P. Walker's <em>Spiritual and Demonic Magic from Ficino to Campanella</em> (1958) identifies the tension between Plotinian naturalism and Iamblichan theurgy as the central philosophical problem for Renaissance Neoplatonism: Ficino needed Iamblichan theurgy to explain how his astral magic worked, but Iamblichan theurgy shaded into demonic magic as Christian theologians defined it. The resolution Ficino attempted — claiming natural (Plotinian) rather than theurgic (Iamblichan) efficacy for his procedures — was philosophically unstable but practically necessary. Brian Copenhaver's work on Ficino's sources and Wouter Hanegraaff's on Western esotericism provide the most recent accounts of this relationship.</p>""",

"pentacle_magic": """<h2>Definition</h2>
<p>Hybrid Term. In the Solomonic grimoire tradition, "pentacles" (<em>pentacula</em>, also called lamens, sigils, or pentagrammata) are geometric or symbolic figures — typically circles containing divine names, astrological symbols, planetary characters, and/or spirit seals — inscribed on parchment, paper, or metal and attributed with power over specific spirits or for specific magical operations. The term combines actor usage (practitioners made and used pentacles as material ritual objects) and analyst function (scholars classify them as distinctive artefacts of the Solomonic tradition).</p>

<h2>The Clavicula Salomonis Pentacles</h2>
<p>The <em>Clavicula Salomonis</em> (Key of Solomon) devotes major sections of its second book to the pentacles: forty-four pentacles keyed to the seven planets, each with a specific figure, a set of divine and spirit names inscribed within it, and a brief account of its use and efficacy. The figures are circular, typically divided into segments containing names in Hebrew and Latin, astrological symbols, and geometric patterns. Each planetary set (seven pentacles of Saturn, seven of Jupiter, etc.) addresses a specific range of operations appropriate to that planet. The pentacle is not merely symbolic but operative: the practitioner holds or displays it during conjuration, and its possession is understood to give authority over the spirits within the relevant planetary domain.</p>
<p>Joseph Peterson's edition of the <em>Key of Solomon</em> (Weiser, 2004) documents the manuscript variation in the pentacle figures, showing that different manuscript families reproduce substantially different figures under the same names — suggesting that the figures were copied and modified without access to a stable original, and that their specific content was less important than their ritual function as material signatures of Solomonic authority.</p>

<h2>Relationship to Seals and Characters</h2>
<p>Pentacles overlap with "seals" (spirit-specific sigils attributed to individual named demons or angels, as in the <em>Lemegeton Ars Goetia</em>) and "characters" (the generic term for magical graphic signs). The broader category of magical figure-work — including magic circles, geometric diagrams, and ritual drawings — is treated by Frank Klaassen in <em>The Transformations of Magic</em> (2013) as a key feature distinguishing the learned grimoire tradition from popular magical practice, which generally used simpler verbal formulas rather than elaborate graphic systems.</p>""",

"rosicrucian_movement": """<h2>Definition</h2>
<p>Analyst Term. The Rosicrucian movement designates the early seventeenth-century cultural phenomenon initiated by the anonymous publication of three manifestos — <em>Fama Fraternitatis</em> (1614), <em>Confessio Fraternitatis</em> (1615), and <em>Chymische Hochzeit Christiani Rosencreutz anno 1459</em> (Chemical Wedding, 1616) — purporting to announce the existence of a secret fraternity of learned brothers (<em>Fratres Rosae Crucis</em>) founded by the legendary "Christian Rosenkreuz" who had gained wisdom from Arabic and Eastern sources in the fifteenth century. The manifestos called for a universal reformation of arts, sciences, and religion, combining Hermetic, Paracelsian, and Protestant themes.</p>

<h2>The Manifestos and Their Context</h2>
<p>The <em>Fama Fraternitatis</em> narrated the life and posthumous discovery of Christian Rosenkreuz: born in 1378, he travelled to Morocco, Damascus, and Fez, absorbing Arabic wisdom; returning to Europe, he founded a fraternity of eight brothers dedicated to healing the sick freely and preparing for a general reformation. His tomb, discovered 120 years after his death in perfect preservation, contained books, instruments, and a preserved body — the symbolism of hidden wisdom waiting for the right moment to be disclosed. The manifestos provoked an enormous response: over two hundred pamphlets were published between 1614 and 1620 by writers seeking to contact or join the fraternity.</p>
<p>Frances Yates's <em>The Rosicrucian Enlightenment</em> (1972) linked the manifestos to the Palatine court of Frederick V and Elizabeth Stuart and to a network of Hermetic reformers including Michael Maier, Robert Fludd, and Johann Valentin Andreae (the likely author of the <em>Chemical Wedding</em>). Yates argued that the Rosicrucian movement was a coherent political and intellectual programme connecting Hermetic magic, early modern science (Francis Bacon), and Protestant utopianism. This reading has been contested: subsequent scholars have found the Rosicrucian connection to Bacon and early science much looser than Yates claimed, and the fraternity itself may never have had more than imaginary existence.</p>

<h2>Legacy</h2>
<p>The Rosicrucian tradition persisted through the seventeenth and eighteenth centuries in various forms, contributing to Freemasonry and the broader tradition of secret society esotericism. By the late nineteenth century, formal Rosicrucian orders existed in Europe and North America. The Hermetic Order of the Golden Dawn's degree structure drew on Rosicrucian symbolism. Christopher McIntosh's <em>The Rosicrucians: The History, Mythology and Rituals of an Esoteric Order</em> (Weiser, 1997) provides the most accessible scholarly overview.</p>""",

"sortilege": """<h2>Definition</h2>
<p>Actor Term (from Latin <em>sors</em>, lot, and <em>legere</em>, to choose). Sortilege is divination by the casting of lots — the use of random or apparently random procedures (dice, marked sticks, cards, the random opening of a book) to generate an answer to a question or guidance for a decision. It is one of the oldest and most cross-culturally widespread divinatory practices, attested from ancient Mesopotamia (the casting of clay tablets) through the Roman <em>sortes Vergilianae</em> (divination from randomly opened passages of Virgil) and the medieval <em>sortes sanctorum</em> (divination from randomly opened Scripture or liturgical books).</p>

<h2>Medieval Practice and Condemnation</h2>
<p>Sortilege was consistently condemned in medieval canon law as a form of divination forbidden by Scripture (Acts 1:26, the casting of lots to choose Matthias, was treated as a one-time divinely sanctioned exception, not a model for general practice) and by the patristic tradition. Penitentials from the sixth century onward prescribed penances for various forms of sortilege. The canonical condemnation, transmitted through Gratian's <em>Decretum</em>, was clear. Nevertheless, the practice was widespread: lot-casting appeared in ecclesiastical contexts (choosing among candidates for office, dividing property), in medical contexts (determining lucky or unlucky days for treatment), and in popular magical contexts (answering questions about thieves, lost property, or future marriages).</p>
<p>The <em>sortes sanctorum</em> — divination by randomly opening Scripture — occupied a particularly ambiguous position: it used a sacred object (the Bible) and invoked divine providence rather than demonic assistance, making it hard to condemn straightforwardly. Some churchmen tolerated it as a pious appeal to God's guidance; others condemned it as presuming to direct divine power toward trivial ends. The theological debate over whether apparently random events could serve as vehicles for divine communication was never definitively resolved.</p>

<h2>Scholarship</h2>
<p>Michael Clanchy's work on medieval literacy and Don Skemer's <em>Binding Words</em> (2006) both touch on sortilege in the context of written and material divination. For the broader theological debate, see the relevant sections of Kieckhefer's <em>Magic in the Middle Ages</em> and Bailey's <em>Magic and Superstition in Europe</em>.</p>""",

"suffumigation": """<h2>Definition</h2>
<p>Actor Term. Suffumigation (from Latin <em>suffumigatio</em>, fumigation from below) designates the burning of aromatic substances — incense, resins, herbs, animal parts — as part of a magical or ritual operation. In the Solomonic and astrological magic traditions, suffumigation serves two related functions: it creates an appropriate atmospheric environment for the spirit being invoked (some spirits are said to require specific aromatic substances to enable their manifestation), and it concentrates specific celestial or elemental influences in the ritual space (since materials correspond sympathetically to specific planets and their associated spirits).</p>

<h2>Theory and Practice</h2>
<p>The theory of suffumigation in the astrological magic tradition is rooted in the correspondence system: each planet has associated plants, minerals, and animal substances with which it resonates sympathetically through the world-soul and the ray-system described by al-Kindi. The <em>Picatrix</em> provides the most extensive system: each of the twenty-eight lunar mansions and each of the seven planets has associated fumigations specified in careful detail, and the choice of the correct fumigation is as important as the timing and the image for the success of a talisman operation.</p>
<p>Marsilio Ficino's <em>De vita coelitus comparanda</em> (1489) incorporates suffumigation into its system of astral medicine: the philosopher who wants to attract solar <em>spiritus</em> should burn solar fumigations (amber, mastic, cinnamon, saffron) in his living space, in addition to wearing solar colours, eating solar foods, and surrounding himself with solar music. The suffumigation here is part of a total environmental programme for adjusting the practitioner's pneumatic composition.</p>

<h2>Scholarly Coverage</h2>
<p>The fullest account of suffumigation in the medieval magical tradition appears in the relevant sections of David Pingree's edition of the <em>Picatrix</em> (Warburg Institute, 1986) and in the Attrell-Porreca English translation (Penn State, 2019). Sophie Page's <em>Magic in the Cloister</em> (2013) and Frank Klaassen's work on English magical manuscripts also document the appearance of fumigation instructions in practical magic texts.</p>""",

"vernacular_grimoire_tradition": """<h2>Definition</h2>
<p>Analyst Term. The "vernacular grimoire tradition" designates magical texts composed or compiled in vernacular languages — Middle English, Middle French, Middle High German, Italian, Spanish — rather than in the Latin that dominated learned magical writing through most of the medieval period. The emergence of vernacular grimoires reflects the broader expansion of vernacular literacy in the thirteenth through fifteenth centuries and the growing market for practical knowledge texts outside the clerical Latin-literate community.</p>

<h2>Examples and Range</h2>
<p>The vernacular tradition encompasses a wide range of texts and social contexts. At the learned end, vernacular translations and adaptations of Latin magical texts (the <em>Clavicula Salomonis</em> in French, Italian, and English; portions of the <em>Picatrix</em> in Castilian; astrological magic texts in German) brought sophisticated learned magic to readers with less Latin. At the popular end, the vernacular charm collections (the English "receipts," French "experiments," German <em>Zauberbücher</em>) address a lower social level, providing healing formulas, protective charms, and simple love or harm magic in accessible language.</p>
<p>The <em>Book of Oberon</em> (Folger Shakespeare Library MS V.b.26), edited by Harms, Clark, and Peterson (2015), exemplifies the Elizabethan vernacular tradition: a miscellany in English combining Solomonic conjuration (including the fairy spirit Oberon) with simpler practical magic in a single compilation, suggesting a practitioner who worked in both registers. Johannes Hartlieb's <em>Buch aller verbotenen Kunst</em> (c.1456) — written in German at the request of the Margrave of Brandenburg — provides a vernacular account of the seven prohibited arts (including chiromancy, geomancy, and nigromancy) that serves both as an encyclopedia of forbidden knowledge and as a warning against it.</p>

<h2>Scholarship</h2>
<p>Owen Davies's <em>Grimoires: A History of Magic Books</em> (2009) traces the vernacular tradition's development into the early modern chapbook grimoire market. Frank Klaassen's <em>The Transformations of Magic</em> (2013) documents the manuscript context of vernacular magical texts in medieval England. The essays in Katelyn Mesler and others' work on vernacular encyclopedism provide broader context for the expansion of vernacular technical literature.</p>""",

"licit_and_illicit_knowledge": """<h2>Definition</h2>
<p>Analyst Term. "Licit and illicit knowledge" designates the boundary that medieval and early modern intellectual culture drew between forms of inquiry that were permissible within Christian orthodoxy and forms that were condemned as superstition, demonic magic, or presumptuous curiosity. The boundary was not fixed: it was actively contested by natural philosophers, theologians, practitioners, and inquisitors throughout the medieval period, and its shifting location is a major theme in the historiography of medieval magic and natural philosophy.</p>

<h2>The Boundary in Theological Thought</h2>
<p>The primary theological tool for drawing the boundary was Augustine's analysis of <em>superstitio</em> as giving to creatures what belongs to God, refined by Aquinas's systematic treatment in <em>Summa theologiae</em> II-II, qq. 92–96. Any inquiry that presupposed demonic assistance — whether explicitly (through conjuration) or implicitly (through using means that could only work through demonic power) — was illicit. Inquiry into natural causes, however hidden, was in principle licit: the philosopher who studied the occult properties of stones, the mechanism of celestial influence, or the hidden sympathies connecting distant things was pursuing legitimate knowledge, provided the operations he derived from that knowledge did not require demonic cooperation.</p>
<p>The practical negotiation of this boundary was complex and context-dependent. The same text (the <em>Picatrix</em>, for instance) could be read as natural philosophy (by a university-trained natural philosopher interested in celestial influence theory) or as demonic magic (by an inquisitor applying the condemnation of divination and spirit-working). The same operation (a talisman made under a specific planetary configuration) could be defended as natural magic or condemned as demonic image magic depending on whether it explicitly addressed planetary spirits as personal agents.</p>

<h2>Scholarly Framework</h2>
<p>Richard Kieckhefer's <em>Magic in the Middle Ages</em> (1989) provides the clearest account of how the boundary was negotiated in medieval learned culture. Frank Klaassen's <em>The Transformations of Magic</em> (2013) traces how the boundary shifted across two centuries in the English manuscript tradition. Nicolas Weill-Parot's concept of addressative magic provides the most precise analytical tool for locating where specific operations fall relative to the licit/illicit boundary in the context of astrological image magic.</p>""",

"manuscript_miscellany": """<h2>Definition</h2>
<p>Analyst Term. A manuscript miscellany is a codex containing texts of diverse genres, subjects, and purposes — typically assembled by one or more scribes over a period of time rather than designed as a unified work. The miscellany format is significant for the history of magic because magical texts most commonly survive not as standalone grimoires but as components of miscellanies that also contain medical recipes, astronomical tables, grammatical texts, devotional material, or other practical content. Understanding the manuscript context of a magical text — what it is bound with, in what order, with what marks of use — is essential for interpreting its social function.</p>

<h2>Significance for Magic History</h2>
<p>Frank Klaassen's foundational methodological contribution in <em>The Transformations of Magic</em> (2013) is precisely the insistence on reading magical texts within their manuscript context rather than in isolation. A conjuration formula appearing in a manuscript alongside medical recipes and astrological tables tells a different story about its intended use than the same formula appearing in a dedicated necromantic handbook. The former suggests a practitioner who treated magical procedures as one technology among several for achieving practical ends; the latter suggests a more specialized and committed engagement with the learned magical tradition.</p>
<p>Sophie Page's <em>Magic in the Cloister</em> (2013) uses codicological analysis — examining the physical construction of manuscripts, the identity and sequence of texts they contain, and the marks of ownership and use — to establish how magical texts functioned within the libraries and reading practices of English monastic and collegiate institutions. Her work demonstrates that monks and canons possessed and used magical texts in ways that made sense within their broader intellectual and devotional practices, rather than as transgressive departures from orthodoxy.</p>

<h2>Examples</h2>
<p>The Munich Manual (Bayerische Staatsbibliothek Clm 849), edited by Kieckhefer (<em>Forbidden Rites</em>, 1997), is a miscellany containing medical material alongside demonic conjuration. The Sloane manuscripts in the British Library contain important magical texts amid large and varied collections. British Library MS Sloane 3824 is a good example of the kind of early modern magical miscellany — combining astrology, Solomonic magic, and practical medical-magical material — that characterizes the English learned magic tradition.</p>""",

"print_culture_and_magic": """<h2>Definition</h2>
<p>Analyst Term. "Print culture and magic" designates the transformation of the magical tradition that resulted from the shift from manuscript to print as the primary medium of text production and distribution, a process beginning with the hand press in the 1450s and continuing through the nineteenth century's steam-powered mass printing. The introduction of print did not simply disseminate existing magical texts more widely; it changed what kinds of texts were produced, who could access them, how they were read, and what authority and social meaning they carried.</p>

<h2>The First Wave: Learned Magic in Print</h2>
<p>The earliest printed magical texts appeared in contexts that minimized their transgressive character. Ficino's <em>De vita</em> (1489) appeared under Medici patronage as a work of natural philosophy. Agrippa's <em>De occulta philosophia</em> (1531) was printed openly in Cologne. Giovanni Battista della Porta's <em>Magia naturalis</em> (1558, expanded 1589) became one of the century's best-sellers by framing natural magic as applied natural philosophy. The grimoires most resistant to print were those involving explicit demonic conjuration: the <em>Clavicula Salomonis</em>, the <em>Lemegeton</em>, the <em>Munich Manual</em> — these circulated in manuscript throughout the sixteenth century because their content risked legal and ecclesiastical prosecution.</p>

<h2>The Chapbook Revolution</h2>
<p>The decisive popular transformation came in the seventeenth and especially eighteenth century, when cheaper printing methods enabled a mass market for practical magic pamphlets. Owen Davies's <em>Grimoires: A History of Magic Books</em> (Oxford, 2009) provides the most comprehensive account: the French <em>Grand Albert</em>, <em>Petit Albert</em>, and <em>Dragon Rouge</em>; the German <em>Sechste und Siebente Buch Mosis</em>; and their English and American equivalents created a grimoire market aimed at literate artisans, tradespeople, and rural practitioners. The chapbook grimoire is not simply a diluted version of the learned tradition but a distinctively popular form adapted to different needs and social contexts.</p>

<h2>Modern Occult Publishing</h2>
<p>The Victorian occult revival — Mathers, Waite, Crowley, the Theosophical Society — created a new genre of scholarly-occult edition that bridged academic and practitioner audiences. The twentieth-century paperback occult market (Llewellyn, Weiser, Ibis Press) and the internet have extended this further. Joseph Peterson's Esoteric Archives (online from 1997) represents the digital equivalent: rigorous scholarly editions made freely available to a global audience of both historians and practitioners.</p>""",

}


PERSON_ENRICHMENTS = {

"arnald_of_villanova": """<h2>Life</h2>
<p>Arnald of Villanova (c.1240–1311) was a Catalan physician, theologian, and spiritual writer who served as physician to three popes (Nicholas IV, Boniface VIII, and Clement V) and to the Aragonese royal family, while simultaneously producing an extraordinary range of works on medicine, alchemy, astrology, and Joachite prophecy that brought him into conflict with Parisian theologians and eventually with the Inquisition. Born probably in Valencia, he studied medicine at Montpellier and Naples, where he learned Arabic and had access to the latest Arabic medical literature. He translated several Arabic medical texts, including works of Avicenna's school, into Latin.</p>

<h2>Medicine, Astrology, and Magic</h2>
<p>Arnald's medical works — including his <em>Regimen sanitatis ad regem Aragonum</em>, his commentaries on Avicenna, and his treatise on poisons — engaged seriously with astrological medicine: the timing of medical interventions by planetary configurations, the use of lapidary and herbal remedies keyed to celestial influence, and the production of medical images and talismans. His engagement with astrological image magic brought him into the same contested territory as Albertus Magnus and Pietro d'Abano: the question of whether specific medical procedures worked through natural celestial causes or required demonic assistance.</p>
<p>Nicolas Weill-Parot's work on addressative image magic treats Arnald's engagement with the Picatrix tradition and with astrological talisman-making as an important case study in the negotiation of the licit/illicit boundary at the interface of medicine and magic. Arnald accepted the naturalistic theory of celestial influence in medicine while resisting the explicitly addressative elements of astrological magic that would have put him clearly outside orthodox bounds.</p>

<h2>Prophecy and Condemnation</h2>
<p>Arnald's most controversial works were his Joachite prophetic writings, in which he predicted the imminent coming of Antichrist and the end of the present ecclesiastical order. These writings were condemned at Paris in 1300 and brought him into ongoing conflict with the Dominicans and the Parisian theological faculty. His connections to the Franciscan Spirituals and to the Valencian Beguins complicated his relationship with the papacy even as he served as personal physician to three popes. He died at sea in 1311 before a planned second confrontation with the theological authorities.</p>""",

"cecco_d_ascoli": """<h2>Life</h2>
<p>Francesco Stabili, known as Cecco d'Ascoli (c.1257–1327), was an Italian astrologer, physician, and poet from Ascoli Piceno in the Marche, who became a professor of astrology at Bologna and physician to Charles of Calabria in Florence. He was burned at the stake in Florence on 16 September 1327 — the most dramatic example in the fourteenth century of a university-trained natural philosopher condemned for heretical astrological claims. His execution illustrates with unusual clarity the limits of what the medieval university could tolerate in the name of natural philosophy.</p>

<h2>Works and Condemnation</h2>
<p>Cecco's principal works are his commentary on John of Sacrobosco's <em>De sphaera</em> (a standard university astronomy text) and <em>L'Acerba</em>, a vernacular encyclopedic poem on cosmology, natural philosophy, and astrology that remained unfinished at his death. His commentary on the <em>Sphaera</em> was condemned at Bologna in 1324 for including discussions of astral determinism and related matters that the theological faculty found heretical: specifically, the claim that specific celestial configurations at the moment of Christ's conception and birth determined his nature and fate — a position that could be construed as denying the freedom of the Incarnation.</p>
<p>After his first condemnation (he was required to recant and fined), Cecco continued in his astrological work. His second condemnation, in Florence, was more severe: the inquisitor Accursio Bonfantini found him guilty of relapse into heresy and of affirming doctrines that effectively denied free will and reduced human affairs to celestial determination. Cecco was burned. His case is significant for the history of magic because it shows that astrological determinism — when applied to sacred history — could attract capital punishment even for a university-trained philosopher with noble patronage. Paola Zambelli's work on Cecco and the Florentine condemnation provides the most thorough scholarly analysis.</p>""",

"giovanni_battista_della_porta": """<h2>Life</h2>
<p>Giovanni Battista della Porta (c.1535–1615) was a Neapolitan polymath — natural philosopher, dramatist, cryptographer, and agronomist — whose <em>Magia naturalis</em> (1558, expanded to twenty books in 1589) became one of the best-selling books of the sixteenth century and the most widely read Renaissance definition of natural magic as a branch of legitimate natural philosophy. Born into a noble family near Naples, della Porta had the leisure and connections to pursue natural philosophical inquiry without institutional employment, though he also founded one of the earliest scientific societies, the <em>Academia Secretorum Naturae</em> (Academy of the Secrets of Nature), in Naples around 1560.</p>

<h2>Magia naturalis and Natural Philosophy</h2>
<p>The <em>Magia naturalis</em> defines natural magic in its preface as the practical summit of natural philosophy — the knowledge that, having understood nature's hidden causes, puts them to work in producing remarkable effects. The twenty-book expansion of 1589 ranges across: sympathies and antipathies in nature; the occult properties of plants, animals, and minerals; the production of new plant varieties; cosmetics and perfumes; distillation; explosives and pyrotechnics; magnetism; optics (including the camera obscura); hydraulics; pneumatics; and remedies against poisons. The work combines genuine natural observation with received Aristotelian and Neoplatonic theory and outright legend, all presented in a confident empirical tone that made it accessible and exciting to a lay readership.</p>
<p>Della Porta was investigated by the Inquisition in 1574 — his Academy was closed, apparently on suspicion of magical practices — and required to modify some of his claims in subsequent editions. Despite this, his self-presentation as a natural philosopher rather than a magician was broadly accepted: <em>Magia naturalis</em> circulated without the restrictions that surrounded more explicitly demonic texts, and Francis Bacon cited della Porta in discussing natural magical phenomena.</p>

<h2>Other Works</h2>
<p>Della Porta's <em>De humana physiognomonia</em> (1586) was the most comprehensive Renaissance study of physiognomy. His <em>Phytognomica</em> (1588) applied the doctrine of signatures to plants. His comedies and tragicomedies — <em>La Clizia</em>, <em>La Fantesca</em>, <em>La Sorella</em> — were performed across Italy and translated into several European languages. His work on cryptography influenced Johannes Trithemius. For the history of science, his camera obscura description in <em>Magia naturalis</em> is historically important, though the priority between della Porta and other early modern opticians is disputed.</p>""",

"honorius_of_thebes": """<h2>The Legendary Figure</h2>
<p>Honorius of Thebes is a legendary magical authority rather than a historical person: a figure to whom the <em>Sworn Book of Honorius</em> (<em>Liber juratus Honorii</em>) and related magical texts are attributed, presented as a master magician who compiled the surviving essence of a vast magical library and established the fraternal oath of secrecy that preserved it against papal persecution. The text's framing narrative — ninety masters of magic assembling to protect their tradition against ecclesiastical attack — has no historical basis but provides the legal and social self-understanding of the tradition it represents.</p>

<h2>The Sworn Book of Honorius</h2>
<p>The <em>Sworn Book of Honorius</em> is a Latin magical text probably compiled in the thirteenth century, combining the programme of the Ars Notoria (seeking divine knowledge through prayer and contemplation) with explicit spirit conjuration and a series of operations for achieving the beatific vision. Its central feature — the Seal of God (<em>Sigillum Dei</em>), a complex geometric figure combining divine names, angelic seals, and astrological symbols — was understood as the supreme magical talisman, conferring authority over all spirits. John Dee's obsession with the Sigillum Dei (he commissioned a large wax seal based on a version of the figure in 1582) demonstrates the continuing influence of the Honorian tradition in the Elizabethan period.</p>
<p>The text attributes its origin to Honorius, son of Euclid, Master of the Theban School — a fantastical genealogy designed to give it intellectual authority (Euclid as mathematical wisdom) and exotic provenance (Thebes as ancient Egyptian learning). The fraternal oath that opens the text — each member of the original ninety swears to transmit the book to no more than three persons, and those three must be men of good character — frames the text as a consciously counter-cultural preservation of forbidden knowledge. Gösta Hedegård's critical edition (2002) and Joseph Peterson's English translation (2016) are the scholarly standards.</p>""",

"hugh_of_saint_victor": """<h2>Life</h2>
<p>Hugh of Saint-Victor (c.1096–1141) was the most important theologian and biblical exegete of the Parisian abbey of Saint-Victor, a house of Augustinian canons that was one of the principal intellectual centres of twelfth-century Europe. Born possibly in Saxony (his origins are uncertain), he spent his career at Saint-Victor, where he wrote an extraordinary range of works on theology, biblical exegesis, philosophy, and the classification of the arts and sciences.</p>

<h2>The Didascalicon and the Classification of Magic</h2>
<p>Hugh's <em>Didascalicon de studio legendi</em> (c.1120s) — a guide to reading and learning — contains the most systematic twelfth-century classification of the arts and sciences, including a treatment of the "mechanical arts" (practical skills) and, crucially, an account of the "adulterate arts" — divination and magic — that defined their status for subsequent generations. Hugh distinguished between legitimate inquiry into hidden natural causes (which he approved) and the arts that sought to penetrate the future or command spirits through illicit means (which he condemned). His taxonomy of divination — augury, auspicy, haruspicy, and various forms of sortilege — drew on Isidore but integrated it into a more philosophical framework.</p>
<p>For the history of magic, Hugh is important as an early twelfth-century voice insisting on the distinction between natural philosophy (which can study hidden causes) and magic (which transgresses into demonic territory). His classification influenced the subsequent scholastic discussion: the Victorine tradition's integration of natural inquiry with theological propriety provided one model for how learned magic could be discussed and evaluated within an orthodox framework. Richard Southern's <em>Scholastic Humanism and the Unification of Europe</em> and the relevant sections of Winthrop Wetherbee's work on twelfth-century Platonism provide the intellectual context.</p>""",

"isidore_of_seville": None,  # Already done in batch 6

"john_of_salisbury": """<h2>Life</h2>
<p>John of Salisbury (c.1115/20–1180) was an English humanist scholar and ecclesiastical administrator who studied in Paris under Peter Abelard, Robert of Melun, William of Conches, and — most importantly for his intellectual formation — Thierry of Chartres, before serving as secretary to Archbishop Theobald and then Thomas Becket of Canterbury. He witnessed the murder of Becket in 1170 and ended his career as Bishop of Chartres (1176–1180). He was the most accomplished Latinist of his generation in northern Europe and the best witness to the intellectual culture of the Paris schools in the 1130s–40s.</p>

<h2>The Policraticus and Magic</h2>
<p>John's <em>Policraticus sive de nugis curialium et vestigiis philosophorum</em> (Statesman's Book, 1159), a wide-ranging treatise on political philosophy, contains important material on divination and magic in Books I–II. John distinguishes legitimate from illegitimate forms of divination with considerable sophistication, drawing on classical sources (Cicero's <em>De divinatione</em>) alongside patristic authorities. He is familiar with Arabic astrological categories and with the debate over whether celestial influence can legitimately serve as a basis for natural prognostication.</p>
<p>John's own experience of magic is personal and sceptical: he describes (I.11) how as a child he was used by a priest who attempted to see spirits in a polished nail or basin through a boy's eyes — an experience John found unproductive and disturbing. This autobiographical account makes him one of the few medieval writers to describe a magical operation from personal experience, however sceptical. For the history of magic, John is important as a twelfth-century voice engaging with astrological and divinatory theory before the main Arabic transmission had been fully absorbed, and as evidence for the persistence of practical magical experiment alongside learned theological discussion.</p>""",

"francis_barrett": """<h2>Life</h2>
<p>Francis Barrett (fl. 1780–1810) was an English astrologer, alchemist, and occultist whose one published work, <em>The Magus, or Celestial Intelligencer</em> (London, 1801), compiled and republished a large portion of Cornelius Agrippa's <em>De occulta philosophia</em> alongside material from other magical sources, presenting it to a Regency-era English audience as a comprehensive guide to occult philosophy and practice. Almost nothing is known of Barrett's life beyond what the book reveals: he advertised himself as a teacher of occult sciences and alchemy in London, offering private instruction.</p>

<h2>The Magus</h2>
<p><em>The Magus, or Celestial Intelligencer</em> (1801) is a compilation in three books drawing heavily on the 1651 English translation of Agrippa's <em>De occulta philosophia</em>, on Peter de Abano's <em>Heptameron</em>, on Francis Bacon, and on other sources. Book I covers natural magic; Book II covers magnetism, cabala, and talismans; Book III covers celestial intelligences and demonology, including a catalogue of demons with their sigils derived from the Goetic tradition. The book was illustrated with striking engravings of demon portraits that became influential in the subsequent occult tradition.</p>
<p><em>The Magus</em> occupies an interesting historical position: it appears at the cusp between the older tradition of learned magical compilation and the nineteenth-century occult revival. Published thirty years before the major Romantic-era occult revival texts, it anticipates the Victorian interest in Hermetic and Solomonic magic while still using the eighteenth-century format of the encyclopedic compilation. Aleister Crowley owned a copy; the book's demon portraits influenced the Golden Dawn's visual magical culture. Owen Davies's <em>Grimoires</em> (2009) provides the context for Barrett's work within the history of magical publication.</p>""",

"paracelsus": """<h2>Life</h2>
<p>Theophrastus Bombastus von Hohenheim, known as Paracelsus (1493/4–1541), was a Swiss-German physician, alchemist, and natural philosopher whose rejection of Galenic medical orthodoxy and advocacy of chemical medicine initiated one of the most significant revolutions in early modern European medicine. Born near Einsiedeln in Switzerland, he had a peripatetic education — studying at various universities without, apparently, completing a formal degree — and spent decades travelling across Europe, the Near East, and possibly further, claiming to have learned medicine from miners, midwives, and local healers rather than from academic physicians.</p>

<h2>Magic, Alchemy, and Natural Philosophy</h2>
<p>Paracelsus's relationship to magic is complex. He rejected the Neoplatonic-Hermetic learned magic of Ficino and Agrippa as too speculative and insufficiently grounded in practical knowledge of nature, while simultaneously developing a natural philosophy pervaded by magical assumptions: the doctrine of signatures (each plant bears marks indicating its medicinal use), the concept of the <em>arcanum</em> (the hidden essence of each thing), and the influence of celestial bodies on the composition and properties of minerals and herbs. His alchemical theory — that the three principles of mercury, sulphur, and salt constitute all things, replacing the four Aristotelian elements — had profound implications for natural magic: if all things are constituted by these principles, the alchemist who can manipulate them can change and heal all things.</p>
<p>Paracelsus's followers — the Paracelsians — created a movement in sixteenth and seventeenth century natural philosophy and medicine that intersected at many points with learned magic. The concept of the <em>magnale</em> (a term Paracelsus used for the hidden causal forces that connect things at a distance), the Paracelsian theory of sympathies and antipathies, and the doctrine of <em>iliaster</em> (primal matter animated by the world-soul) all share theoretical territory with Neoplatonic natural magic. The Rosicrucian manifestos of 1614–1616 drew on Paracelsian medicine as one of their sources; Robert Fludd's Hermetic philosophy synthesized Paracelsianism with Hermeticism.</p>""",

"reginald_scot": None,  # Already done in batch 5

}


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    updated = 0
    for slug, html in CONCEPT_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM concepts WHERE slug=?", (slug,)).fetchone()
        if row:
            conn.execute("UPDATE concepts SET definition_long=? WHERE slug=?", (html, slug))
            print(f"  concept: {slug} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING concept: {slug}")

    for pid, html in PERSON_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM persons WHERE person_id=?", (pid,)).fetchone()
        if row:
            conn.execute("UPDATE persons SET bio_html=? WHERE person_id=?", (html, pid))
            print(f"  person: {pid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING person: {pid}")

    conn.commit()
    print(f"\nUpdated {updated} entries.")
    conn.close()


if __name__ == "__main__":
    main()
