"""
Enrich batch 2: Solomonic and scholasticism core entries,
plus reception-section key figures and texts.
"""
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import DB_PATH


CONCEPT_ENRICHMENTS = {

"solomonic_magic": """<h2>Definition</h2>
<p>Actor Term (used by historical practitioners) and Analyst Term (used by historians). "Solomonic magic" designates the broad tradition of ritual magic attributed to King Solomon, encompassing conjuration manuals, spirit-binding procedures, pentacles, seals, and adjurations that claim Solomonic origin or authority. The term derives from a cluster of pseudepigraphic attribution: texts that position their procedures as revealed by Solomon himself, transmitted through angelic intermediaries (Raziel, Michael), or discovered in his tomb or treasury. This attribution strategy gave the tradition its characteristic claim to pre-Christian, divinely sanctioned authority.</p>

<h2>Historical Development</h2>
<p>The earliest attestations of Solomonic magical authority appear in first-century Jewish and Greek sources. Josephus (<em>Antiquities</em> 8.2.5) describes Solomon exorcising demons using a ring and root of the plant baaras. The <em>Testament of Solomon</em>, probably composed in Greek between the first and fifth centuries CE, narrates how Solomon bound demons to construct the Temple, obtaining from each demon its name, rank, and the angel capable of thwarting it — the foundational template of the spirit catalogue. The Dead Sea Scroll <em>Songs of the Maskil</em> and the magical papyri (PGM) attest related traditions of angelic and demonic naming.</p>
<p>In Arabic and Islamic tradition, Solomon (Sulayman) is a prophet-king granted power over jinn, wind, and animals by divine command (Qurʾan 27:15–44, 34:12–14). Islamic magical compilations drew on Qurʾanic Sulayman traditions to authorize procedures closely parallel to the Latin and Hebrew Solomonic texts. The transmission of astrological image magic from Arabic sources to Latin Europe (via the twelfth-century translation movement) brought Solomonic conjuration elements into the Latin learned magical tradition.</p>
<p>The major Latin Solomonic grimoires — the <em>Clavicula Salomonis</em> (Key of Solomon), the <em>Lemegeton</em> (comprising Ars Goetia, Ars Theurgia-Goetia, Ars Paulina, Ars Almadel, and Ars Notoria), the <em>Sworn Book of Honorius</em>, and the <em>Hygromanteia</em> — represent the medieval Latin crystallization of the tradition. These texts share structural features: framing narratives of Solomonic discovery or transmission, lists of spirits with names, ranks, seals, and powers, ritual preparation procedures (fasting, prayer, ritual purity, construction of magical instruments), and conjuration texts invoking divine and Solomonic authority to compel spirit obedience.</p>

<h2>Scholarly Analysis</h2>
<p>Pablo Torijano's <em>Solomon the Esoteric King</em> (Brill, 2002) provides the most comprehensive treatment of how the biblical Solomon became a magical authority across Jewish, Christian, and Islamic sources. Gideon Bohak's <em>Ancient Jewish Magic</em> (Cambridge, 2008) situates the earliest Solomonic traditions within the broader context of Jewish magical practice. Richard Kieckhefer's <em>Magic in the Middle Ages</em> (1989) and <em>Forbidden Rites</em> (1997) treat the medieval Latin tradition. For the early modern period, Frank Klaassen's <em>The Transformations of Magic</em> (2013) tracks how Solomonic texts circulated and were transformed in medieval England.</p>""",

"demonology": """<h2>Definition</h2>
<p>Hybrid Term. Demonology designates both the historical study of demons conducted by theologians, philosophers, and learned magicians (actor-usage: the discipline of knowing demons) and the modern scholarly subdiscipline that studies such historical accounts (analyst-usage). In the medieval and early modern periods, demonology was a serious theological enterprise with practical stakes: if demons were real, what were their powers and limitations? Could they create genuine effects or only illusions? Could they be compelled by human art? These questions bore directly on the legal and theological assessment of magic, witchcraft, and popular protective ritual.</p>

<h2>Historical Development</h2>
<p>Christian demonology inherited a complex legacy from Jewish angelology, Neoplatonic daemon theory, and Pauline pneumatology. Augustine of Hippo's treatment of demons in <em>De civitate Dei</em> (VIII–X) and <em>De divinatione daemonum</em> established the foundational claims: demons are real, fallen angels with limited but genuine causal powers; they can appear to predict the future because they have better sensory equipment and faster movement than humans; they can cause apparent wonders but not true miracles; and all traffic with demons — even seemingly beneficial consultation — is illicit because it involves worship of beings other than God.</p>
<p>Medieval scholastic demonology elaborated this framework. Thomas Aquinas's <em>Summa theologiae</em> (especially the Treatise on Angels in the <em>Prima Pars</em> and the discussion of superstition in <em>Secunda secundae</em> qq. 92–96) provided the authoritative synthesis: demons are intellectual substances, created good but fallen through pride; their powers are real but limited by divine permission; they can affect material things (weather, disease, illusion) but cannot override free will or create genuine miracles. This framework licensed a highly specific taxonomy: natural effects (even extraordinary ones) remained within the domain of natural philosophy; genuinely miraculous effects belonged to God; demonic effects occupied a middle category of apparent wonder or <em>praestigium</em>.</p>
<p>The witch trials of the fifteenth and sixteenth centuries generated a new genre of demonological treatise — from the <em>Malleus Maleficarum</em> (1486) through Bodin's <em>Démonomanie des sorciers</em> (1580), Remy's <em>Demonolatreiae</em> (1595), and del Rio's <em>Disquisitionum magicarum</em> (1599–1600) — that elaborated the concept of the demonic pact and the witches' sabbath as legal and theological categories. These texts are less concerned with the learned magical tradition (with which they overlap) than with the prosecution of popular magic understood as diabolical alliance.</p>

<h2>Scholarly Resources</h2>
<p>Stuart Clark's <em>Thinking with Demons: The Idea of Witchcraft in Early Modern Europe</em> (1997) provides the fullest analysis of early modern demonological thought as an intellectual system. Michael Bailey's <em>Battling Demons</em> (2003) traces the construction of the witch-sabbath concept in the fifteenth century. For the scholastic tradition, see Jan Machielsen (ed.), <em>The Science of Demons: Early Modern Authors Facing Witchcraft and the Devil</em> (2020). For ancient and Jewish demonology, Gideon Bohak and the relevant sections of Philip Alexander's work remain essential.</p>""",

"pseudepigraphy": """<h2>Definition</h2>
<p>Analyst Term. Pseudepigraphy (from Greek <em>pseudepigraphos</em>, "falsely inscribed") designates the attribution of a text to an author who did not write it — a practice that, in the ancient and medieval worlds, served functions quite different from modern literary fraud. In the contexts most relevant to the history of magic, pseudepigraphic attribution to figures such as Solomon, Hermes Trismegistus, Aristotle (via the <em>Secretum Secretorum</em>), or Moses provided the attributed text with an authority it could not claim on its own merits: the antiquity, wisdom, royal power, or prophetic status of the named author transferred to the text and legitimated its contents.</p>

<h2>Functions in the Magical Tradition</h2>
<p>Solomonic pseudepigraphy is the most important instance in the history of the grimoire. Texts such as the <em>Testament of Solomon</em>, the <em>Clavicula Salomonis</em>, the <em>Key of Solomon</em>, the <em>Lemegeton</em>, and dozens of subsidiary texts claim to preserve the actual magical knowledge of the biblical king — the names and seals he used to bind demons in the construction of the Temple, the rings and pentacles with which he controlled spirits, the adjurations he taught to his sons or to Roboam. This attribution strategy accomplished several things simultaneously: it provided a pre-Christian, divinely sanctioned ancestry for procedures that might otherwise appear demonic; it anchored the text in biblical history, making its authority hard to dismiss without impugning Solomon himself; and it supplied the practitioner using the text with a vicarious identification with Solomon's royal, priestly authority.</p>
<p>Hermetic pseudepigraphy (attributing texts to Hermes Trismegistus) served parallel functions in the natural-philosophical magical tradition. The <em>Corpus Hermeticum</em>, the <em>Asclepius</em>, the <em>Emerald Tablet</em>, and the <em>Picatrix</em> all claim ancient Egyptian or Hermetic authority. The 1463 Ficinian translation of the <em>Corpus Hermeticum</em> launched a tradition that lasted until Casaubon's 1614 philological dating of the texts to the first three centuries CE.</p>

<h2>Scholarship</h2>
<p>Pablo Torijano's <em>Solomon the Esoteric King</em> (2002) is the primary analysis of Solomonic pseudepigraphy as a cross-cultural phenomenon. For Hermetic pseudepigraphy, Garth Fowden's <em>The Egyptian Hermes</em> (1986) and Brian Copenhaver's introduction to his <em>Hermetica</em> translation (1992) are foundational. John Monfasani has written on Aristotelian pseudepigraphy. For the broader phenomenon in late ancient and medieval literary culture, see Michael Stone, David Aune, and the entries in the standard encyclopedias of pseudepigraphy.""",

"scholastic_classification": """<h2>Definition</h2>
<p>Analyst Term. "Scholastic classification" designates the taxonomic projects by which medieval university theologians and natural philosophers organized, categorised, and evaluated the phenomena associated with magic, divination, and the occult. Beginning with Isidore of Seville's <em>Etymologiae</em> (c.623–636) and elaborated through William of Auvergne, Albertus Magnus, Thomas Aquinas, and Nicole Oresme, scholastic classification created the conceptual vocabulary — the distinctions between natural and demonic causes, between superstition and legitimate scientific inquiry, between licit and illicit operations — that structured both the condemnation and the partial defence of learned magic in medieval and early modern Europe.</p>

<h2>The Classical Framework</h2>
<p>Isidore's <em>Etymologiae</em> VIII.9 provided the canonical taxonomy of forbidden arts: <em>magi</em> (magicians), <em>malefici</em> (evildoers), <em>mathematici</em> (astrologers), <em>haruspices</em>, <em>augures</em>, <em>pythones</em> (spirit-speakers), <em>astrologi</em>, and <em>sortilegi</em> (diviners by lot). Each term receives an etymology and a brief account of its nature. This list, transmitted through Rabanus Maurus and Burchard of Worms into the twelfth and thirteenth centuries, provided the starting point for all subsequent scholastic discussion.</p>
<p>The crucial twelfth-century elaboration came from authors engaging with newly translated Arabic natural philosophy. John of Salisbury's <em>Policraticus</em> (c.1159) distinguished legitimate and illegitimate divination and showed familiarity with Arabic astrological categories. The translation of al-Kindi's <em>De radiis</em> and the pseudo-Aristotelian <em>Secretum Secretorum</em> introduced naturalistic accounts of magical causation through stellar rays and occult qualities that complicated the Isidorean taxonomy.</p>
<p>William of Auvergne's <em>De legibus</em> and <em>De universo</em> (c.1230s) provided the first systematic scholastic treatment of natural magic in its Arabist form, distinguishing natural powers (admissible) from demonic cooperation (always forbidden). Albertus Magnus's natural philosophical corpus — <em>De mineralibus</em>, the <em>Speculum astronomiae</em> — developed the distinction further, arguing for a category of legitimate astral image magic operating through purely natural celestial causes. Aquinas in the <em>Summa theologiae</em> (Secunda secundae, qq. 92–96) provided the most authoritative synthesis, condemning all magical operations that required demonic cooperation while admitting the reality of natural occult powers.</p>

<h2>University Condemnations and Their Effect</h2>
<p>The Parisian condemnations of 1270 and 1277 under Bishop Étienne Tempier imposed institutional limits on scholastic natural philosophy that reshaped the classification problem. By condemning astrological determinism and related propositions, Tempier forced subsequent natural philosophers to be more careful about how they articulated the relationship between celestial influence and terrestrial events — which in turn affected how they could discuss the natural basis of magical causation. Nicolas Weill-Parot's studies of "addressative" image magic in the context of the condemnations have clarified how these institutional pressures shaped the subsequent development of scholastic classification.</p>""",

"learned_magic": """<h2>Definition</h2>
<p>Analyst Term. "Learned magic" designates the magical practices, texts, and traditions associated with literate, educated practitioners — primarily clergy, university graduates, and court-connected scholars — as opposed to the protective charms, folk healing practices, and oral traditions associated with popular or village magic. The distinction is an analyst category: historical actors did not use the term "learned magic," and the boundary between learned and popular practice was permeable in both directions (charms circulated in written form; grimoires informed popular healing practice). Nevertheless, the analytical distinction captures something real about the different social contexts, material conditions (expensive manuscripts, specialized instruments), and theoretical ambitions of the grimoire tradition.</p>

<h2>Characteristics</h2>
<p>Learned magic in the medieval period is characterised by several features that distinguish it from popular magical practice. First, it is primarily textual: it depends on written books (grimoires, magical treatises, experiment collections) that require literacy, often in Latin, for their use. Second, it is theoretically self-aware: learned magical texts typically provide or assume a theoretical framework — Neoplatonic, Aristotelian, or astrological — that explains why the procedures work. Third, it tends toward systematic elaboration: the spirit catalogues, the hierarchies of angels and demons, the tables of planetary correspondences that characterise Solomonic and astrological magic represent a drive toward comprehensive ordering that is characteristic of scholastic and university culture. Fourth, it is socially ambitious: learned magicians presented themselves as operating at the top of a hierarchy of knowledge, not as village healers or cunning folk.</p>

<h2>Social History</h2>
<p>Richard Kieckhefer's <em>Magic in the Middle Ages</em> (1989) proposed the concept of the "clerical underworld" to describe the social milieu of learned magic: a penumbra of clergy, university students, and court-connected intellectuals who circulated practical magic texts alongside more respectable learned works. Frank Klaassen's <em>The Transformations of Magic</em> (2013) provides the most systematic evidence-based account of this milieu in the medieval English context. Sophie Page's <em>Magic in the Cloister</em> (2013) documents the specific role of monastic libraries and scribal culture in preserving and transmitting magical texts.</p>
<p>The boundaries between learned magic and natural philosophy were contested throughout the medieval and early modern periods. Scholars like Albertus Magnus and Roger Bacon included discussions of magical phenomena within their natural philosophical works, both expanding the domain of admissible enquiry and policing its borders by distinguishing natural from demonic causes. This ongoing negotiation between learned magic and natural philosophy is a central theme of Klaassen's work and of Nicolas Weill-Parot's studies of scholastic engagement with image magic.</p>""",

}


PERSON_ENRICHMENTS = {

"richard_kieckhefer": """<h2>Life and Scholarship</h2>
<p>Richard Kieckhefer is a historian of medieval religion and magic at Northwestern University, where he taught for over three decades before retirement. His scholarship has been central to establishing the history of medieval magic as a legitimate and rigorous subdiscipline of medieval studies, combining careful archival work with broad synthetic analysis. He received his doctoral training at the University of Texas at Austin and has published across the history of medieval religion, spirituality, and the relationship between official theology and popular practice.</p>

<h2>Major Works</h2>
<p><em>Magic in the Middle Ages</em> (Cambridge University Press, 1989; revised edition 2000) is Kieckhefer's most widely read work and the standard introduction to the field. The book surveys the full range of medieval magical practice — from village charms and protective amulets through learned necromancy — and introduces the crucial analytical distinction between "common tradition" (widely shared magical practices embedded in everyday life) and "specific tradition" (the specialized learned magic of the educated clergy and university-trained). Kieckhefer's concept of the "clerical underworld" — the social milieu of clergy and university students who circulated practical magic manuscripts alongside more respectable texts — has been widely adopted and debated.</p>
<p><em>Forbidden Rites: A Necromancer's Manual of the Fifteenth Century</em> (Penn State University Press, 1997) offers an edition, translation, and analysis of the Munich Manual (Clm 849), a Latin necromantic handbook from the 1440s. The edition is a model of how to approach a practical magic manuscript: Kieckhefer situates the text in its manuscript context, analyses its ritual structure and theoretical assumptions, and uses it to illuminate the social world of learned clerical magic. The book is essential reading for anyone working on the Latin grimoire tradition.</p>
<p>His edited volume <em>Conjuring Spirits: Texts and Traditions of Medieval Ritual Magic</em> (Penn State, 1994), co-edited with Claire Fanger, assembled key essays on medieval ritual magic and helped define the field's scope and methods. <em>Theology in Stone: Church Architecture from Byzantium to Berkeley</em> (2004) represents his parallel work on medieval religious culture. His work on medieval devotion and mysticism (<em>Unquiet Souls: Fourteenth-Century Saints and their Religious Milieu</em>, 1984; <em>Mystics and Miracles</em>, 2015) provides the broader religious-historical context within which the history of magic is properly situated.</p>""",

"frank_klaassen": """<h2>Life and Scholarship</h2>
<p>Frank Klaassen is a historian of medieval magic and learned culture at the University of Saskatchewan. His research focuses on the practical ritual magic texts of medieval England — the manuscripts that circulated among literate clergy and university-trained practitioners — and on what their content and manuscript contexts reveal about the culture of learned magic in the later Middle Ages. He studied at the University of Toronto and completed his doctorate there.</p>

<h2>The Transformations of Magic</h2>
<p><em>The Transformations of Magic: Illicit Learned Magic in the Later Middle Ages</em> (Penn State University Press, 2013) is Klaassen's major monograph and the most rigorous systematic study of the English learned magic manuscript tradition. The book surveys approximately 270 manuscripts containing ritual magic material, providing a quantitative foundation for generalizations about what types of magic circulated, in what social contexts, and how the tradition changed between c.1300 and c.1500. Klaassen identifies two transformations: a shift in some parts of the tradition toward more explicit demonic conjuration, and a counter-trend of naturalization in which ritual operations were increasingly framed within the idiom of scholastic natural philosophy and celestial influence theory.</p>
<p>The book's methodological contribution — the systematic manuscript survey rather than focus on a few canonical texts — was influential in subsequent grimoire scholarship, demonstrating that the selection bias of printed editions had significantly distorted earlier accounts of what medieval learned magic actually looked like.</p>

<h2>Other Work</h2>
<p>Klaassen has edited and introduced key primary texts in the medieval magic corpus. His edition (with Christopher Phillips) of the Ars Notoria tradition and his contributions to Claire Fanger's <em>Invoking Angels</em> (Penn State, 2012) expand the manuscript base for understanding angelic magic in the medieval period. He has also published on the relationship between learned magic and early modern print culture, on the transition from manuscript to print in the magical tradition, and on the Solomonic attribution as a legitimating strategy.</p>""",

"albert_magnus_entry": """<h2>Life</h2>
<p>Albertus Magnus (c.1200–1280) — Albert of Cologne, Albert the Great — was the most encyclopedic natural philosopher of the thirteenth century and the teacher of Thomas Aquinas at Cologne and Paris. Born in Lauingen on the Danube, he entered the Dominican Order around 1223 and studied and taught at Paris from 1240, before moving to the Cologne studium generale (1248), where he remained the dominant intellectual figure for decades. He served briefly as Bishop of Regensburg (1260–1262) but returned to Cologne for the remainder of his career.</p>

<h2>Natural Philosophy and Magic</h2>
<p>Albert's massive natural philosophical project — an attempt to paraphrase and comment on the entire Aristotelian corpus, supplemented with Arabic sources — made him the primary conduit through which Arabist natural philosophy, including the doctrines of occult qualities, astral influence, and image magic, entered systematic Latin scholastic discussion. His <em>De mineralibus</em> (c.1262) treats the occult properties of stones and metals with a naturalistic framework that acknowledges their reality while declining to appeal to demonic causes. His commentaries on the pseudo-Aristotelian <em>De causis</em> and on Dionysius the Areopagite also bear on questions of magical causation.</p>
<p>The <em>Speculum astronomiae</em>, whose attribution to Albert has been debated (Nicolas Weill-Parot argues against it; others maintain it), is the most systematic scholastic treatment of the boundary between legitimate and illegitimate magic in the thirteenth century. It distinguishes three categories of astrological image magic: fully licit images (talismans operating through natural celestial causes, analogous to medicinal plants), potentially licit images (whose licitness depends on whether demonic invocation is involved), and clearly illicit images (requiring demonic names and pact). This tripartite classification remained influential through the fourteenth century.</p>

<h2>Pseudo-Albertine Literature</h2>
<p>Albert's enormous authority generated a substantial pseudo-Albertine literature: practical magic texts circulated under his name as a legitimating attribution. The <em>Liber aggregationis</em> (Secrets of Albertus Magnus), <em>De virtutibus herbarum</em>, and <em>Experimenta Alberti</em> are the most widely circulated of these pseudo-attributions. Their circulation under Albert's name represents the same pseudepigraphic strategy visible in the Solomonic tradition: attributing practical magic to an authoritative figure domesticates its transgressive potential.</p>""",

"thomas_aquinas": """<h2>Life</h2>
<p>Thomas Aquinas (1225–1274), born into a noble family at Roccasecca near Aquino in southern Italy, entered the Dominican Order in 1244, studied under Albertus Magnus at Cologne (1248–1252), and spent his career teaching at Paris and in Italy. He died at the monastery of Fossanova while travelling to the Council of Lyon. He was canonized in 1323 and declared a Doctor of the Church in 1567; his <em>Summa theologiae</em> was placed alongside the Bible on the altar at the Council of Trent. His theology and philosophy dominated the Catholic university curriculum from the thirteenth century to the twentieth.</p>

<h2>Scholastic Demonology and Magic</h2>
<p>Aquinas's treatment of magic appears principally in three locations: the <em>Prima Pars</em> of the <em>Summa theologiae</em> (on angels and demons as intellectual substances with limited causal powers), the <em>Secunda secundae</em> (qq. 92–96, on superstition, divination, and the pact with demons), and his shorter treatise <em>De occultis operibus naturae</em> (On the Occult Works of Nature), which addresses the natural philosophical limits of non-supernatural causation.</p>
<p>The <em>Summa theologiae</em> II-II, qq. 92–96 provide the most systematic scholastic condemnation of divination and magic as illicit forms of inquiry. Aquinas distinguishes superstition (which attributes to creatures — stars, images, demons — what belongs to God alone) from legitimate religious practice. Divination is always illicit when it involves implicit or explicit demonic pact; the desire to know the future by consulting anything other than legitimate causes or divine revelation is in itself a turning toward demonic power, even if the practitioner does not explicitly intend it. This framework made even passive or "natural" divination theologically suspect, and shaped the Inquisition's approach to magical practice for centuries.</p>
<p>On the natural philosophical side, <em>De occultis operibus naturae</em> argues that natural things can have properties exceeding ordinary causation (occult qualities) that produce apparently marvellous effects without supernatural intervention. This argument, against those who too quickly attributed unusual natural phenomena to demonic agency, licensed a domain of natural magical phenomena that could be studied and used without moral hazard. Combined with the condemnation of demonic magic, this position creates the characteristic Thomistic double gesture: nature can produce marvels; but any operation that requires demonic cooperation is illicit regardless of the intended end.</p>""",

"roger_bacon": """<h2>Life</h2>
<p>Roger Bacon (c.1214/20–1292) studied at Oxford and Paris, entered the Franciscan Order probably in the 1250s, and spent periods under house restriction at Paris, apparently because of his controversial promotion of an experimental, mathematically-based natural philosophy and his attacks on the established university curriculum. His three major works — the <em>Opus maius</em>, <em>Opus minus</em>, and <em>Opus tertium</em> — were written at the request of Pope Clement IV (1265–1268) and represent a systematic programme for the reform of Christian education through the integration of mathematics, languages, optics, and experimental science.</p>

<h2>Magic and Experimental Science</h2>
<p>Bacon occupies a complex position in the history of learned magic. His works contain some of the most sophisticated engagement with the theory of magical causation in the thirteenth century — his account of the power of celestial influence, the action of the imagination, and the mechanism of "opus manus" (art or skill) that produces marvellous effects — alongside some of the most aggressive naturalization of magical phenomena. Bacon consistently argued that apparently magical effects could be explained through natural philosophy properly understood: through knowledge of celestial influences, optical phenomena, and the hidden properties of things.</p>
<p>His concept of <em>scientia experimentalis</em> (experimental science) as the crown of the philosophical sciences was explicitly connected to the production of marvellous effects: knowledge of the secret causes of things gave the philosopher the ability to produce effects that would strike the ignorant as magical. At the same time, Bacon drew a sharp distinction between legitimate philosophical investigation and demonic magic: the latter, he argued, was inferior to the former because it depended on cooperation with deceptive spiritual agents rather than true knowledge of natural causes. Lynn Thorndike's assessment of Bacon in his <em>History of Magic and Experimental Science</em> (vol. 2, 1923) remains the most extensive treatment, though subsequent scholarship (especially by David Lindberg) has refined the picture considerably.</p>""",

}


TEXT_ENRICHMENTS = {

"testament_of_solomon": """<h2>Overview</h2>
<p>The <em>Testament of Solomon</em> is a Greek pseudepigraphic text, probably composed between the first and fifth centuries CE, that narrates how King Solomon, aided by a magic ring given by the archangel Michael, summoned and interrogated demons, learning their names, their functions, the afflictions they cause, and the angels capable of thwarting them. The demons are then set to work constructing the Temple in Jerusalem. The text is the earliest systematic demonology in Greek and the foundational text of the Solomonic grimoire tradition: its framework of named demons bound to named angels, organized by Solomonic authority, provides the template replicated across two millennia of magical literature.</p>

<h2>Structure and Contents</h2>
<p>The narrative frame has Solomon receive a ring from Michael, inscribed with a pentagram, that gives him power over demons. He then successively summons thirty-six demons (later expanded in some manuscript traditions), each of whom reveals his name and the specific affliction he causes. Typical entries follow a pattern: the demon appears, reveals his name (often etymologized or pun-connected to his function), describes the diseases or misfortunes he inflicts, and reveals the angel whose name, written or spoken, can neutralize him. Some entries include planetary associations, gemstone affinities, and brief ritual instructions.</p>
<p>The text exists in several manuscript recensions of varying length and arrangement: McCown identified five principal recensions in his 1922 critical edition. The most important manuscripts are in the Bibliothèque nationale de France and the Vienna National Library. Dennis Duling's translation in Charlesworth's <em>Old Testament Pseudepigrapha</em> (Doubleday, 1983) is the standard English version.</p>

<h2>Historical Significance</h2>
<p>The <em>Testament of Solomon</em> is significant for several reasons. First, as a demonological text, it represents the earliest comprehensive name-catalogue of demons with individual attributes — a structure replicated in the <em>Ars Goetia</em> (part of the <em>Lemegeton</em>), the <em>Book of Abramelin</em>, and dozens of medieval and early modern grimoires. Second, as a pseudepigraphic text, it establishes the attribution strategy that would legitimise the entire subsequent Solomonic corpus: magical knowledge is Solomonic in origin, transmitted by divine gift (Michael's ring), and serves ultimately to build the Temple — that is, to serve God's purposes. Third, its composite nature — drawing on Jewish, Christian, pagan Greek, and possibly Egyptian elements — makes it evidence for the multicultural magical milieu of the late antique Mediterranean.</p>""",

"clavicula_salomonis": """<h2>Overview</h2>
<p>The <em>Clavicula Salomonis</em> (Key of Solomon) is the most widely circulated and extensively copied of the medieval and early modern Solomonic grimoires, surviving in over one hundred manuscripts in Latin, Italian, Hebrew, French, and English, ranging from the fourteenth century to the nineteenth. It is attributed to Solomon himself or to the transmission from Solomon to his son Roboam, and presents itself as a comprehensive practical manual for the conjuration of spirits, the construction of magical implements, and the performance of a wide range of ritual operations.</p>

<h2>Structure and Contents</h2>
<p>The text is typically organized in two books. Book I covers the practical ritual operations: how to conjure spirits to achieve specific ends (finding hidden treasures, obtaining love, causing invisibility, healing disease, inflicting harm). Book II covers the preparation of the magician and his instruments: the days and hours of the planets under which various operations should be conducted, the making and consecration of the magic circle, the pentacles attributed to the seven planets (each accompanied by a figure and a conjuration), the preparation of magical tools (knife, wand, lamen, robe, etc.), and the ritual of suffumigation and prayer.</p>
<p>The manuscript tradition is enormously complex. Joseph Peterson's online edition (Esoteric Archives) documents over fifty Latin and vernacular manuscripts; his printed edition (Weiser, 2004) provides the most thorough textual analysis available. S.L. Mathers's 1889 edition, based on British Museum manuscripts, was the first modern printed edition and shaped the occult revival's understanding of the text, though it combined several divergent manuscript families without adequate documentation.</p>

<h2>Historical Development</h2>
<p>The earliest datable manuscripts of the <em>Clavicula Salomonis</em> are from the fourteenth century; the text clearly assembled over a long period from multiple source traditions, incorporating elements of older Solomonic demonology, astrological image magic, and ritual prayer. The Hebrew <em>Mafteah Shelomoh</em> (Key of Solomon) tradition is related but may represent an independent development rather than a simple translation from Latin. The Arabic tradition of Solomonic conjuration (Solomon as Sulayman, master of jinn) provides a parallel context rather than a direct source. Frank Klaassen's work on the medieval English manuscript tradition and Pablo Torijano's on the ancient background remain the principal scholarly frameworks.</p>""",

"sepher_ha_razim": """<h2>Overview</h2>
<p>The <em>Sepher ha-Razim</em> (Book of Mysteries) is a Hebrew magical handbook whose compilation is usually dated to the Geonic period (sixth to tenth centuries CE), though it draws on material that is almost certainly earlier — some scholars detect traditions going back to the Second Temple period. It is attributed to Noah, who received it from the angel Raziel, transmitted it through Shem, Abraham, Isaac, Jacob, Moses, and ultimately Solomon, who used it in the construction of the Temple. This chain of transmission connects the text to the Solomonic authority framework while locating its ultimate origin in antediluvian divine revelation.</p>

<h2>Structure and Contents</h2>
<p>The text is organized around the seven heavens, each presided over by a named angelic prince and populated by named angelic servants whose functions and the periods of their activity are specified. For each heavenly realm, the text provides: the names of the ruling angel and his subordinates, the days and hours of their activity, adjurations invoking them, and specific practical procedures (prescriptions for achieving various ends through the proper invocation of the appropriate heaven's angels). Operations range from healing and protection through love magic, invisibility, and the harming of enemies.</p>
<p>The standard critical edition is Mordecai Margalioth's 1966 Hebrew text. Michael Morgan's English translation (Scholars Press, 1983) made the text accessible to non-Hebrew readers and remains the standard English version. The text is a key document for the history of Jewish magical practice and provides essential context for understanding the relationship between Jewish angel magic and the Latin and Greek Solomonic tradition.</p>

<h2>Significance</h2>
<p>The <em>Sepher ha-Razim</em> is significant for several reasons. Its hierarchical organization of named angels by heavenly sphere anticipates the spirit catalogues of the medieval Solomonic grimoires. Its adjuration formulas — commands addressed to named spirits invoking God's authority — provide the direct precedent for the Latin conjuration literature. Its attribution to Noah and Raziel rather than Solomon marks a distinct tradition of antediluvian revealed magic that parallels the Solomonic tradition without being identical to it. Gideon Bohak's <em>Ancient Jewish Magic</em> (2008) situates it within the wider context of Jewish magical practice.</p>""",

"summa_theologiae": """<h2>Overview</h2>
<p>The <em>Summa theologiae</em> of Thomas Aquinas, composed between approximately 1265 and 1274 at Paris, Naples, and Rome (left incomplete at his death in 1274), is the most systematic and authoritative synthesis of medieval scholastic theology and the work that dominated Catholic theological education from the fourteenth century through the Second Vatican Council. For the history of magic, two sections are of primary importance: the treatment of angels and demons in the <em>Prima Pars</em> (qq. 50–64, 106–114) and the discussion of superstition, divination, and forbidden arts in the <em>Secunda secundae</em> (qq. 92–96).</p>

<h2>Angels, Demons, and Causal Powers</h2>
<p>In the <em>Prima Pars</em>, Aquinas treats angels as pure intellectual substances, created good by God, some of whom fell through pride — the demons. As intellectual substances, both angels and demons have real causal powers: they can move bodies, affect the imagination and senses, influence the passions, and produce what appear to be marvellous effects through their superior knowledge of natural causes and their capacity to move matter more rapidly than human agents. However, they cannot override free will (because the will is moved only by the intellect and by God), and they cannot perform genuine miracles (which are reserved to God alone). The demonic wonders described in scripture are either real natural effects produced through superior knowledge, or illusions (praestigia) affecting only the senses or imagination.</p>
<p>This framework — demons as real agents with limited natural powers — was not merely theological but had direct practical implications for how inquisitors, theologians, and natural philosophers assessed magical claims. A phenomenon could be miraculous (divine), natural (explicable through natural causes), or diabolical (a real effect produced through demonic cooperation or a demonic illusion). Aquinas's framework licensed the investigation of natural causes without immediately condemning them as demonic, while insisting that any operation requiring demonic cooperation was illicit.</p>

<h2>Superstition and the Forbidden Arts</h2>
<p>The <em>Secunda secundae</em>, qq. 92–96 define superstition (Latin <em>superstitio</em>) as a species of irreligion: the attribution to creatures of what belongs to God alone, or the worship of God in an improper manner. Divination (<em>divinatio</em>) is the attempt to know hidden or future things by means of creatures — stars, spirits, lots, dreams — rather than through divine revelation or legitimate causal reasoning. Aquinas condemns all forms of divination as implicitly or explicitly involving demonic pact, even when the practitioner does not consciously intend this: the desire to obtain occult knowledge from spiritual agents that are not God constitutes a tacit invitation to demonic assistance.</p>
<p>Observations (<em>observationes</em>) — magical rituals using material objects, words, or procedures — are similarly condemned when they operate through demonic agency rather than natural causes. However, Aquinas acknowledges that some material things have natural occult powers (occult qualities) that can produce unusual effects without supernatural intervention; his <em>De occultis operibus naturae</em> (a brief treatise addressed to a soldier) develops this naturalistic alternative more fully.</p>""",

}


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    updated = 0
    for slug, html in CONCEPT_ENRICHMENTS.items():
        row = conn.execute("SELECT id FROM concepts WHERE slug=?", (slug,)).fetchone()
        if row:
            conn.execute("UPDATE concepts SET definition_long=? WHERE slug=?", (html, slug))
            print(f"  concept: {slug} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING concept: {slug}")

    for pid, html in PERSON_ENRICHMENTS.items():
        row = conn.execute("SELECT id FROM persons WHERE person_id=?", (pid,)).fetchone()
        if row:
            conn.execute("UPDATE persons SET bio_html=? WHERE person_id=?", (html, pid))
            print(f"  person: {pid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING person: {pid}")

    for tid, html in TEXT_ENRICHMENTS.items():
        row = conn.execute("SELECT id FROM texts WHERE text_id=?", (tid,)).fetchone()
        if row:
            conn.execute("UPDATE texts SET analysis_html=? WHERE text_id=?", (html, tid))
            print(f"  text: {tid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING text: {tid}")

    conn.commit()
    print(f"\nUpdated {updated} entries.")
    conn.close()


if __name__ == "__main__":
    main()
