"""
Enrich batch 5: concepts and selected persons (solomonic/scholasticism focus).
"""
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import DB_PATH


CONCEPT_ENRICHMENTS = {

"adjuration": """<h2>Definition</h2>
<p>Actor Term (from Latin <em>adjurare</em>, to swear by, to compel by oath). The adjuration is the ritual speech act by which a practitioner compels a spirit — demon, angel, or ambiguous intermediate being — to appear, obey, or depart, typically by invoking divine names, Solomonic authority, or binding oaths sworn in God's name. It differs from prayer (<em>oratio</em>), which petitions; from invocation, which calls; and from suffumigation or physical rite, which acts materially. The adjuration is the central operative verbal mode of the Solomonic grimoire tradition.</p>

<h2>Structure and Examples</h2>
<p>A typical adjuration follows a recognizable pattern: address to the spirit by name and title; statement of the divine authority by which the practitioner speaks ("I adjure you by the living God, by the God of Abraham, Isaac, and Jacob, by the seal of Solomon..."); specification of what the spirit is commanded to do; and often a threat of what angel or divine name will punish the spirit's non-compliance. The spirit catalogues of the <em>Testament of Solomon</em>, the <em>Clavicula Salomonis</em>, and the <em>Lemegeton</em> organize their material around adjuration formulas keyed to specific spirits.</p>
<p>Jewish adjuration (Hebrew <em>hashba'ah</em>) appears in the <em>Sepher ha-Razim</em>, the magical papyri, and Geonic-period amulet texts analysed by Gideon Bohak (<em>Ancient Jewish Magic</em>, 2008). The Arabic tradition of Solomonic adjuration is preserved in texts studied by Pablo Torijano (<em>Solomon the Esoteric King</em>, 2002). The Latin tradition, from the <em>Clavicula Salomonis</em> through the Munich Manual's conjuration rituals (Kieckhefer, <em>Forbidden Rites</em>, 1997), represents the medieval crystallization of this tradition.</p>

<h2>Theological Status</h2>
<p>The adjuration of spirits was theologically contested: the adjuration of demons was universally condemned as an implicit demonic pact; the adjuration of angels was more ambiguous. The <em>Ars Notoria</em> addresses prayers to God and angels in ways that blend petition and adjuration; its condemnation by Thomas Aquinas turned partly on the question of whether the formulas addressed divine power or presupposed demonic assistance. Richard Kieckhefer's analysis of the Munich Manual distinguishes levels of coerciveness in the conjuration formulas as evidence for the spectrum of relations with spirits that practitioners imagined.</p>""",

"angelic_invocation": """<h2>Definition</h2>
<p>Hybrid Term. Angelic invocation designates ritual operations aimed at communicating with, receiving knowledge from, or obtaining assistance from angels — as distinct from demonic conjuration, which compels demons through binding oaths. The distinction was theologically significant but practically unstable: many operations in the learned magical tradition invoked beings whose angelic or demonic status was unclear, and the boundary between legitimate prayer addressed to God through angelic mediation and illicit spirit-working was a persistent site of theological dispute.</p>

<h2>The Ars Notoria Tradition</h2>
<p>The <em>Ars Notoria</em> (Notory Art) is the primary learned example of angelic invocation framed as pious practice. Its programme of prayer, fasting, and contemplation of the <em>notae</em> — geometric figures accompanied by divine names and Greek magical syllables — claims to secure angelic infusion of knowledge (the liberal arts, languages, wisdom) without any demonic involvement. Thomas Aquinas condemned the system in <em>Summa theologiae</em> II-II, q. 96, arguing that the <em>notae</em> and non-Latin syllables could have no natural relationship to the knowledge they claimed to confer, and therefore presupposed demonic rather than angelic assistance.</p>
<p>John of Morigny's <em>Liber visionum</em> (c.1304–1314), edited by Claire Fanger and Nicholas Watson (Penn State, 2015), records a practitioner who used the <em>Ars Notoria</em>, received visionary condemnation of it from the Virgin Mary, and produced a revised system of Marian angel invocation intended to be free of diabolical contamination — illustrating how practitioners navigated the theological boundary from within.</p>

<h2>Ficino and Neoplatonic Spirit-Working</h2>
<p>Marsilio Ficino's <em>De vita coelitus comparanda</em> (1489) operates in a related but distinct register: the Neoplatonic <em>daimones</em> and planetary spirits invoked through astral medicine and music are not precisely either angels or demons in the Christian sense, but intermediary beings of the Neoplatonic hierarchy. D.P. Walker's <em>Spiritual and Demonic Magic</em> (1958) analyses the instability of this framework: Ficino's sources (Iamblichus, Proclus) included genuine daemon-invocation, and the naturalization he attempted did not fully separate his operations from demonic magic as Christian theologians defined it.</p>""",

"characters_and_seals": """<h2>Definition</h2>
<p>Actor Term. "Characters" (<em>characteres</em>) and "seals" (<em>sigilla</em>) designate the non-alphabetic graphic signs — geometric figures, symbolic images, combinations of letters and lines — attributed to specific spirits or celestial powers in the Solomonic and astrological magic traditions. Each named spirit in the major grimoires is assigned a unique seal or character by which it can be summoned, bound, or dismissed; the practitioner who traces or inscribes the correct seal exercises authority over the corresponding spirit. Characters and seals appear on rings, lamens (ritual breastplates), pentacles, and the pages of magical books.</p>

<h2>Origins and Types</h2>
<p>The category encompasses several distinct but related types of symbol. Planetary "camea" (magic squares) and their derived characters appear in Agrippa's <em>De occulta philosophia</em> II, derived ultimately from Arabic astrological sources. The individual spirit seals of the <em>Lemegeton Ars Goetia</em> — one for each of the seventy-two demons — have no obvious geometric derivation; they appear to be traditional, transmitted through the manuscript chain. The pentacles of the <em>Clavicula Salomonis</em> are typically circular figures containing divine names, astrological symbols, and geometric patterns consecrated to specific planetary operations. The "notae" of the <em>Ars Notoria</em> are elaborate composite figures combining letter-forms, geometric elements, and images, for which no simple derivation has been established.</p>
<p>Thomas Aquinas condemned characters and seals used in magical contexts: because they bear no natural relationship to the effects they are supposed to produce, they must operate through demonic cooperation (<em>Summa theologiae</em> II-II, q. 96, a. 2). This condemnation was standard in subsequent scholastic theology. Practitioners responded either by embedding characters within naturalistic frameworks (deriving them from planetary squares and thus from celestial influence) or by claiming their authority derived from divine revelation (the Solomonic attribution strategy).</p>

<h2>Scholarship</h2>
<p>Frank Klaassen's <em>The Transformations of Magic</em> (2013) analyses the role of characters and seals in medieval English magical manuscripts, showing how their presence or absence, and the frameworks used to explain them, varied across manuscript traditions. Sophie Page's <em>Magic in the Cloister</em> (2013) documents their appearance in institutional library contexts. Don Skemer's <em>Binding Words</em> (2006) treats characters and seals in the context of textual amulets.</p>""",

"celestial_influence": """<h2>Definition</h2>
<p>Analyst Term. Celestial influence designates the theory, central to medieval and Renaissance natural philosophy and astrology, that the motions, positions, and configurations of celestial bodies — planets, fixed stars, and the heavens generally — causally affect terrestrial things: the weather, the growth of plants and minerals, the temperaments of human beings, and the outcomes of historical events. The theory of celestial influence provided the theoretical basis for astrology (the predictive science) and for astrological magic (the operative art of attracting or concentrating celestial power for practical ends).</p>

<h2>The Theory</h2>
<p>Medieval accounts of celestial influence drew on several sources. Aristotle's <em>Meteorologica</em> argued that the sun's motion is the cause of all generation and corruption in the sublunary world. Arabic cosmology, derived from Ptolemy and elaborated by al-Kindi, Thabit ibn Qurra, and Abu Mashar, developed a comprehensive account of how each planet radiates specific qualities (heat, cold, moisture, dryness, and more specific influences) that shape terrestrial matter. Al-Kindi's <em>De radiis</em> (c.850) generalized this into a theory of rays: all things, not just celestial bodies, emit rays that affect other things, and the magician who understands this ray-system can manipulate it for practical ends.</p>
<p>The theory of celestial influence was not simply accepted wholesale. Scholastic natural philosophy insisted that the influence operated through secondary natural causes — celestial bodies moved sublunary matter through heat and light — and that this influence did not determine the will, which was moved only by intellectual apprehension and by God. The Parisian condemnations of 1277 specifically targeted astrological determinism. The question of whether celestial influence could explain apparent wonders (rather than requiring demonic intervention) was the central contested point in scholastic discussions of natural magic and image magic.</p>

<h2>Significance for Magic</h2>
<p>Celestial influence theory was the primary naturalistic resource for legitimating astrological and talismanic magic: if the stars genuinely cause terrestrial effects through natural rays, then a practitioner who times his operations to specific planetary configurations and uses materials resonant with specific planetary powers is simply an expert applied natural philosopher, not a demonic magician. This argument — made most systematically by the author of the <em>Speculum astronomiae</em> — was the principal strategy for defending learned astrological magic against theological condemnation.</p>""",

"clerical_underworld": """<h2>Definition</h2>
<p>Analyst Term, coined by Richard Kieckhefer in <em>Magic in the Middle Ages</em> (Cambridge University Press, 1989). The "clerical underworld" designates the social milieu of literate clergymen and university graduates who circulated practical magic manuscripts in medieval Europe — performing conjurations, offering divination and magical services, or simply preserving magical texts within broader manuscript collections. The term captures the paradox that the primary custodians of the learned magical tradition were men trained in and ostensibly committed to orthodox Christian practice.</p>

<h2>Social Context</h2>
<p>The clerical underworld was not a formal organization or a deliberate counter-culture, but a penumbra of individuals sharing certain social characteristics: Latin literacy (required to read and use the manuscripts), some degree of formal education (university or cathedral school training), and often economic or social marginality — minor clergy without secure benefices, university graduates without positions, students needing income to fund further study. These circumstances made the provision of magical services (healing, finding lost objects, casting horoscopes, compelling love) an attractive supplementary livelihood.</p>
<p>Evidence for the clerical underworld comes principally from three sources: the magical manuscripts themselves (which often show signs of practical use — wear patterns, marginal annotations, additions in different hands — and circulate within broader manuscript collections including medical, astrological, and grammatical texts); inquisitorial and trial records (which document prosecuted practitioners and their social backgrounds); and ecclesiastical condemnations (which consistently target the "learning" that enabled magical practice as well as the practice itself).</p>

<h2>Evidence and Scholarship</h2>
<p>Kieckhefer's analysis of the Munich Manual (<em>Forbidden Rites</em>, 1997) uses that specific text as a primary document for the clerical underworld: a Latin necromantic handbook clearly designed for a literate, educated practitioner. Frank Klaassen's systematic survey of English magical manuscripts (<em>The Transformations of Magic</em>, 2013) confirms and refines the picture for the English context, showing how magical texts circulated within broader manuscript miscellanies alongside grammatical, medical, and astronomical material. Sophie Page's <em>Magic in the Cloister</em> (2013) extends the analysis to monastic libraries.</p>""",

"condemned_arts": """<h2>Definition</h2>
<p>Actor Term (Latin: <em>artes prohibitae</em>, <em>artes damnabiles</em>, <em>artes illicitae</em>). The condemned arts designates the category of practices formally prohibited by canon law, theological condemnation, and inquisitorial procedure in medieval Christendom. The canonical taxonomy derives primarily from Isidore of Seville's <em>Etymologiae</em> VIII.9, transmitted through canon law (Gratian's <em>Decretum</em>, c.1140, Canon 26, q. 5) and theological summas. The condemned arts include divination in all its forms, demonic conjuration, maleficium (harmful magic), and all commerce with spiritual beings other than God and the saints.</p>

<h2>The Canonical Taxonomy</h2>
<p>Isidore's list of condemned arts became the standard reference for medieval moralists and canonists: <em>magi</em> (magicians), <em>malefici</em> (evildoers who work through demonic power), <em>mathematici</em> (astrologers who predict the future), <em>haruspices</em> (diviners from entrails), <em>augures</em> (from birds), <em>pythones</em> (those who speak through demons), and <em>arioli</em> (those who seek answers from demons through sacrifices). These categories were repeatedly rehearsed in penitentials, canon law collections, and theological treatises, and provided the vocabulary for inquisitorial inquiry.</p>
<p>The legal codification in Gratian's <em>Decretum</em> made these prohibitions enforceable in ecclesiastical courts. The development of inquisitorial procedure in the thirteenth century provided the institutional mechanism for their enforcement. The fifteenth-century elaboration of the witchcraft concept added the collective sabbath and explicit demonic pact to the list, generating a new wave of prosecutorial activity.</p>

<h2>The Problem of Natural Magic</h2>
<p>The boundary between the condemned arts and legitimate natural philosophy was the central contested terrain of medieval magical discourse. Natural magic — the use of occult properties of things without demonic assistance — was not straightforwardly condemned; the question was whether the specific operation under examination involved demonic cooperation or purely natural causes. Scholastic natural philosophy's investment in clarifying this boundary produced the taxonomic refinements of Albertus Magnus, Thomas Aquinas, and the <em>Speculum astronomiae</em>, which attempted to carve out a domain of licit natural magic within and adjacent to the broader category of the condemned arts.</p>""",

"enochian_system": """<h2>Definition</h2>
<p>Actor and Analyst Term. The Enochian system designates the angelic language, cosmology, and ritual system revealed to John Dee and his scryer Edward Kelley during their angelic conversations of 1582–1589, and subsequently elaborated within the Western ceremonial magic tradition, most notably by the Hermetic Order of the Golden Dawn in the 1880s–1900s. In Dee's own usage, the system was not called "Enochian" — that designation was applied later; Dee and Kelley called the language received in their sessions the "Angelic Language" or the language of the angels, and connected it to the antediluvian patriarch Enoch.</p>

<h2>The Communications</h2>
<p>The angel conversations, conducted primarily at Dee's Mortlake house and then during the continental travels of 1583–1589, produced an elaborate angelic cosmology: forty-eight "Angelic Keys" or "Calls" in the angelic language (with English translations), tables of letters corresponding to angelic names and powers (the "Tabula Bonorum"), a system of angelic governors arranged in a complex cosmographic scheme, and extensive prophecy concerning the eschatological future of Europe. The communications were received through Edward Kelley's scrying in a crystal "shewstone," with Dee recording every utterance in his diaries.</p>
<p>Deborah Harkness's <em>John Dee's Conversations with Angels</em> (Cambridge, 1999) provides the most thorough analysis of the angel conversations in their historical context, arguing that Dee understood the system as a divinely-restored Adamic language and a programme for the reform of natural philosophy. The primary manuscript sources are BL Sloane 3188 and 3677; Meric Casaubon published a selection as <em>A True and Faithful Relation</em> in 1659.</p>

<h2>Post-Dee Elaboration</h2>
<p>The Hermetic Order of the Golden Dawn absorbed the Enochian material in the 1880s through the work of Samuel Liddell Mathers and William Wynn Westcott, incorporating the Enochian Calls into the Grade rituals and treating the system as a complete magical technology. Aleister Crowley's elaborations and the subsequent influence on twentieth-century ceremonial magic (the A∴A∴, Thelema, the Aurum Solis) have made "Enochian magic" one of the most widely practised systems in the modern Western magical tradition.</p>""",

"experimental_science": """<h2>Definition</h2>
<p>Actor Term (Roger Bacon's <em>scientia experimentalis</em>) and Analyst Term. Roger Bacon coined the term <em>scientia experimentalis</em> in the <em>Opus maius</em> (c.1267) to designate the highest branch of natural philosophy — the science that verifies the conclusions of the other sciences through direct experience and produces the most powerful practical effects from knowledge of nature's hidden causes. The relationship between Bacon's experimental science and magic is both close and contested: Bacon explicitly naturalized many phenomena that others attributed to magic, arguing that they resulted from natural processes accessible to careful investigation.</p>

<h2>Bacon's Programme</h2>
<p>Part VI of the <em>Opus maius</em> on <em>scientia experimentalis</em> identifies three prerogatives of experimental knowledge: it certifies the conclusions of the other sciences (only experience can confirm or refute theory); it adds new discoveries not available through syllogistic reasoning; and it produces marvellous arts that may seem magical to the uninitiated. This third prerogative — the production of wonders through natural knowledge — directly overlaps with natural magic: Bacon mentions the possibility of explosive powder (anticipating gunpowder), optical instruments that magnify distant objects, ships that move without oarsmen, and flying machines, all as products of experimental science rather than magic.</p>
<p>Bacon's stance on actual demonic magic was unambiguous: he condemned it as inferior to true natural knowledge because it depended on deceptive spiritual agents rather than genuine understanding of causes. But his naturalization of many apparently magical phenomena — through his theory of multiplication of species (the mechanism of celestial influence), his optics, and his account of the imagination's power — substantially expanded the domain of what natural philosophy could claim.</p>

<h2>Historiographical Significance</h2>
<p>Lynn Thorndike's <em>History of Magic and Experimental Science</em> (1923–1958) treated Bacon as a key figure in the gradual separation of experimental science from magic. David Lindberg's subsequent work on Bacon's optics and natural philosophy has provided a more nuanced account of his theoretical framework and its dependence on Arabic sources (Alhazen, al-Kindi). The relationship between Bacon's programme and early modern experimental science is debated: he had no direct institutional successors, and his practical programme was not realized until long after his death.</p>""",

"geomancy": """<h2>Definition</h2>
<p>Actor Term. Geomancy (from Greek <em>geomanteia</em>, divination from earth; Arabic <em>ʿilm al-raml</em>, science of the sand) is a divinatory system based on the manipulation of sixteen figures (<em>geomantic figures</em>), each consisting of four rows of one or two dots, generating 16 possible combinations. A practitioner generates figures by random marks on sand, soil, or paper, combines them through a systematic process into a "shield chart" and "house chart," and interprets the resulting configuration to answer specific questions. Geomancy was the most widely practised learned divinatory system in medieval Europe after astrology.</p>

<h2>Origins and Transmission</h2>
<p>Geomancy originated in the Islamic world — the Arabic name (<em>ʿilm al-raml</em>, science of the sand) suggests its origins in desert divination — and was transmitted to Latin Europe through the twelfth-century translation movement. Hugo of Santalla translated an Arabic geomantic text around 1140 (the <em>Ars geomantiae</em>); other translations followed through the twelfth and thirteenth centuries. The system adapted rapidly to the Latin scholarly context: its sixteen figures were associated with the seven planets, the twelve astrological houses, and the signs of the zodiac, giving it a veneer of astrological legitimacy.</p>
<p>Geomantic texts circulated widely in university and court contexts. Sophie Page's work on English magical manuscripts and Don Skemer's <em>Binding Words</em> (2006) document geomantic texts appearing alongside medical, astronomical, and other learned material. The <em>Ars geomantiae</em> attributed to Gerard of Cremona and the geomantic works associated with Michael Scot and Roger Bacon attest its scholarly respectability.</p>

<h2>Status and Condemnation</h2>
<p>Geomancy was consistently condemned in the category of divination (<em>divinatio per sortes</em>, divination by lots) in canon law and theological writing. Its use of random processes to generate figures made it formally equivalent to sortilege (casting lots), which Augustine had condemned and which canon law prohibited. However, practitioners and some scholars argued that geomancy worked through natural celestial influences — the random marks reflecting the practitioner's astrological moment — in the same way that astrology did, making it at least partially naturalistic. This argument was not accepted by orthodox theologians but it circulated in the literature.</p>""",

"kabbalism_renaissance_magic": """<h2>Definition</h2>
<p>Analyst Term. "Kabbalism and Renaissance magic" designates the synthesis of Jewish Kabbalah with Christian theology and Neoplatonic philosophy achieved by Pico della Mirandola, Johannes Reuchlin, and Cornelius Agrippa in the period 1486–1531, which produced "Christian Kabbalah" — an adaptation of Jewish mystical doctrines about divine names, sefirot, and letter-permutation serving as a technology of magical and theological knowledge. Christian Kabbalah provided the third element of the standard Renaissance occult synthesis: natural magic (elemental), astral magic (celestial), and Kabbalistic magic (divine or intellectual).</p>

<h2>Pico and the Beginnings</h2>
<p>Giovanni Pico della Mirandola's 900 <em>Conclusiones</em> (Rome, 1486) included 72 Kabbalistic theses, among them the claim that no science demonstrates the divinity of Christ more effectively than Kabbalah. Pico learned Kabbalah from Jewish teachers — primarily the convert Samuel ben Nissim Abulfaraj (Flavius Mithridates) — and purchased a collection of Kabbalistic manuscripts. His <em>Apologia</em> (1487), written to defend the condemned theses, argued that Kabbalah was not demonic magic but a divinely revealed mystical tradition confirming Christian truth. His distinction between "practical Kabbalah" (the magical manipulation of divine names) and "speculative Kabbalah" (theological meditation) mapped onto the Christian distinction between licit and illicit enquiry, with Pico firmly placing his own interest in the speculative category.</p>

<h2>Reuchlin and Agrippa</h2>
<p>Johannes Reuchlin's <em>De verbo mirifico</em> (1494) and <em>De arte cabalistica</em> (1517) provided more systematic accounts of Christian Kabbalah for German humanist readers, focusing especially on the divine name (the Tetragrammaton) and its Christological interpretation. Cornelius Agrippa's <em>De occulta philosophia</em> III (1531) incorporated Kabbalistic materials systematically into the third level of his magical hierarchy — divine or ceremonial magic — arguing that the manipulation of Hebrew divine names could draw down angelic assistance and ultimately achieve direct divine communication.</p>

<h2>Scholarship</h2>
<p>François Secret's <em>Les Kabbalistes chrétiens de la Renaissance</em> (1964) is the foundational survey. Joseph Dan's work on Kabbalah and early modern Christianity, and Moshe Idel's comparative studies of Kabbalah and magic, provide the Jewish scholarly perspective. For Agrippa, see Charles Nauert's biography (1965) and V. Perrone Compagni's critical edition of <em>De occulta philosophia</em> (Brill, 1992).</p>""",

"medieval_magic": """<h2>Definition</h2>
<p>Analyst Term. "Medieval magic" is a broad scholarly category covering all forms of practice, belief, and text associated with the intentional causation of effects through means that exceed ordinary natural understanding, in European culture from approximately the fifth century CE to the end of the fifteenth century. The term encompasses ritual practices (conjuration, exorcism, protective ritual), material procedures (amulets, talismans, healing herbs), divinatory arts (astrology, geomancy, chiromancy), and the texts that transmit, describe, and theorize all of the above.</p>

<h2>Historiographical Problems</h2>
<p>The scholarly category "medieval magic" is complicated by at least three definitional problems. First, the boundary between magic and religion is a modern analytical distinction that medieval actors did not consistently make: the same practices (prayer, ritual recitation of divine names, use of consecrated objects) appear in both religious and magical contexts, often by the same practitioners. Second, the boundary between magic and medicine is similarly fluid: herbalism, amulets, and ritual healing shade continuously into what both modern and medieval classifications call magic. Third, medieval actors had their own categorizations (condemned arts, superstition, natural magic, experiment) that do not map neatly onto modern taxonomy.</p>
<p>Richard Kieckhefer's <em>Magic in the Middle Ages</em> (1989) proposed the most influential modern analytical framework, distinguishing a "common tradition" of magical practices widely shared across social classes (protective charms, healing herbs, divination) from a "specific tradition" of learned magic (Solomonic conjuration, astrological image magic, the <em>Ars Notoria</em>) circulating in Latin manuscripts among educated practitioners. Michael Bailey's work has further refined this framework by insisting on attention to the historical specificity of each period and region.</p>

<h2>Key Surveys</h2>
<p>Kieckhefer's <em>Magic in the Middle Ages</em> (Cambridge, 1989; revised 2000) is the standard introduction. Valerie Flint's <em>The Rise of Magic in Early Medieval Europe</em> (Princeton, 1991) covers the sixth through eleventh centuries with an argument for Church accommodation rather than simple suppression. Michael Bailey's <em>Magic and Superstition in Europe</em> (Rowman and Littlefield, 2006) provides a concise synthetic overview. Karen Louise Jolly, Catharina Raudvere, and Edward Peters's <em>Witchcraft and Magic in Europe: The Middle Ages</em> (2002) collects specialist essays on specific topics.</p>""",

"natural_powers": """<h2>Definition</h2>
<p>Actor and Analyst Term. "Natural powers" designates the hidden causal properties of things — primarily stones, plants, metals, and animals — that produce effects exceeding ordinary elemental analysis but operating through natural, not demonic, causation. The concept is central to the naturalistic defence of learned magic: if unusual effects can be attributed to occult natural properties, they do not require demonic assistance and are therefore potentially licit.</p>

<h2>The Theory of Occult Properties</h2>
<p>The Aristotelian tradition acknowledged "specific form" and "specific virtue" as causal properties of things that could not be reduced to the four elements and their qualities. Avicenna's medical philosophy elaborated a systematic account of occult properties in stones and plants, transmitted to Latin Europe through the twelfth-century translations of his <em>Canon of Medicine</em>. Albertus Magnus's <em>De mineralibus</em> (c.1262) applied this framework to the virtues of stones: a stone's occult property is impressed on it by the celestial body dominant at the moment of its formation, and this property persists and acts in ways analogous to a form, producing effects (healing, protection, influence) through purely natural causation.</p>
<p>Thomas Aquinas's short treatise <em>De occultis operibus naturae</em> (On the Occult Works of Nature), addressed to a soldier, argues against those who too hastily attribute unusual natural effects to demonic agency: many things in nature have properties that exceed ordinary explanation but operate through genuine natural causation. The magnet, the loadstone, the medicinal properties of specific herbs, the effects of celestial configurations on terrestrial generation — all are natural phenomena, however marvellous.</p>

<h2>Magic and Natural Powers</h2>
<p>The category of natural powers provided the primary resource for defenders of natural magic. If a talisman's effect can be attributed to the natural occult properties of its material combined with the natural influence of the planetary configuration under which it was made, it requires no demonic assistance and is therefore licit. This argument was deployed by the author of the <em>Speculum astronomiae</em>, by Ficino in <em>De vita coelitus comparanda</em>, and by della Porta in <em>Magia naturalis</em>, with varying degrees of philosophical sophistication and varying success in convincing theological critics.</p>""",

"occult_properties": """<h2>Definition</h2>
<p>Actor Term (Latin: <em>qualitates occultae</em>, hidden qualities; <em>virtutes occultae</em>, hidden powers). Occult properties designate the hidden powers of natural things — stones, plants, animals, metals — that produce effects not explicable by analysis of their elemental composition (the four qualities: hot, cold, wet, dry). The magnet's attraction of iron, the torpedo fish's numbing power, the remora's alleged ability to stop ships, the healing properties of specific stones, the antipathy between the wolf and the lamb — all these were standard examples of occult properties cited in the philosophical literature from Aristotle through the seventeenth century.</p>

<h2>Philosophical Background</h2>
<p>The concept of occult properties derives from Aristotelian natural philosophy, specifically the doctrine of "specific form" — the defining principle of a natural species that confers its characteristic properties. Avicenna elaborated this into a systematic account of occult properties in his <em>Canon of Medicine</em>: some properties are impressed on substances by the stars and are specific to particular species, operating in ways that elemental analysis cannot predict or explain. This framework was transmitted to Latin natural philosophy through the twelfth-century translations and systematized by Albertus Magnus in <em>De mineralibus</em>.</p>
<p>Occult properties occupied a contested middle ground between the marvellous (explicable through natural causes, however hidden) and the miraculous (requiring divine power) or the magical (requiring demonic assistance). Natural philosophers from Aquinas through Bacon insisted that many apparently miraculous or magical effects were in fact occult natural properties — expanding the domain of nature at the expense of both miracle and magic. This expansion was the primary theoretical resource for defenders of natural magic.</p>

<h2>Early Modern Fate</h2>
<p>The concept of occult properties was challenged by the mechanical philosophy of the seventeenth century: Descartes, Boyle, and Newton argued that all natural effects must be explicable through matter and motion, and that "occult quality" was merely a label for ignorance. Newton's gravitational attraction was criticized by contemporaries as a return to occult properties; his defence of gravity as a genuine natural force operating at a distance contributed to the concept's rehabilitation in a modified form. For the history of magic, occult properties are significant as the primary naturalistic vocabulary available to practitioners and natural philosophers seeking to defend magical operations against theological condemnation.</p>""",

"prisca_theologia": """<h2>Definition</h2>
<p>Actor Term. <em>Prisca theologia</em> (the primordial or ancient theology) designates the Renaissance doctrine that a single, divinely-revealed wisdom — anticipating and confirming Christian truth — was transmitted through a chain of ancient sages: Zoroaster, Hermes Trismegistus, Orpheus, Pythagoras, Plato, and ultimately Moses. The doctrine was formulated systematically by Marsilio Ficino in the preface to his <em>Theologia Platonica</em> (1474) and in various other texts, and provided the legitimating framework for the Hermetic and Neoplatonic philosophy he promoted. If Hermes Trismegistus was as ancient as Moses and his wisdom anticipated Christian truth, then the <em>Corpus Hermeticum</em> carried divine authority.</p>

<h2>Historical Basis and Collapse</h2>
<p>The doctrine's historical basis was illusory. The belief that Hermes Trismegistus was an Egyptian sage of Mosaic antiquity was itself a product of late antique Hermetic propaganda, preserved in Lactantius and Augustine. Isaac Casaubon's philological analysis (<em>De rebus sacris et ecclesiasticis exercitationes</em>, 1614) demonstrated from linguistic evidence that the <em>Corpus Hermeticum</em> was composed in the first three centuries CE, not in Egyptian antiquity. This refutation, though immediately recognized as compelling, had limited immediate practical effect on the tradition: the <em>prisca theologia</em> continued to be invoked in occult and esoteric contexts well into the eighteenth century and beyond, and Yates argued that the <em>belief</em> in the texts' antiquity — not their actual date — was what historically mattered.</p>

<h2>Magical Significance</h2>
<p>For the history of magic, the <em>prisca theologia</em> doctrine was primarily a legitimating strategy. If Hermetic magic derived from ancient Egyptian divine revelation — more ancient than Plato, contemporary with Moses — it could not be dismissed as merely superstition or demonic innovation. The Solomonic tradition employed an analogous strategy: attributing magical knowledge to Solomon, the wisest and most divinely-favoured of biblical kings, gave it pre-Christian, Scriptural authority. In both cases, pseudepigraphic antiquity served as a defence against theological condemnation.</p>""",

"ring_of_solomon": """<h2>Definition</h2>
<p>Actor Term. The Ring of Solomon is the signet ring given by the archangel Michael to King Solomon (according to the <em>Testament of Solomon</em>), inscribed with a pentagram or divine name, that granted Solomon power to summon, interrogate, and bind demons, compelling them to serve him in the construction of the Temple in Jerusalem. The ring is the foundational magical instrument of the Solomonic tradition: all subsequent Solomonic authority — the seals, pentacles, and conjuration formulas of the grimoire corpus — derives symbolically and narratively from this originary instrument of demonic binding.</p>

<h2>Sources</h2>
<p>The <em>Testament of Solomon</em> (probably second to fifth century CE) provides the fullest account: the ring is described as bearing a five-pointed seal (<em>pentagrammon</em>) and is given by Michael in response to Solomon's prayer. Josephus (<em>Antiquities</em> 8.2.5) mentions Solomon's knowledge of exorcistic arts and roots, but not the ring specifically. The ring's power to bind Asmodeus — the demon who had been plaguing Solomon's servant — and all subsequent demons makes it the architectural concept underlying the entire spirit-binding tradition.</p>
<p>In Islamic tradition, the "seal of Solomon" (khatam Sulayman) is even more central: Sulayman's ring (given by God) is described in Qurʾanic commentary and hadith literature as bearing God's greatest name and as enabling his rule over jinn, animals, and winds. The visual motif of the hexagram — the six-pointed Star of David / Seal of Solomon — became associated with Solomonic power across Jewish, Christian, and Islamic magical traditions, appearing on amulets and magical seals throughout the medieval and early modern periods. Pablo Torijano's <em>Solomon the Esoteric King</em> (2002) and Gideon Bohak's <em>Ancient Jewish Magic</em> (2008) provide the fullest scholarly analyses.</p>""",

"solomonic_authority": """<h2>Definition</h2>
<p>Analyst Term. Solomonic authority designates the legitimating strategy by which magical texts attribute their content to King Solomon — claiming that the procedures, spirit names, seals, and adjurations they contain were originally revealed to, compiled by, or passed down from the biblical king who was the wisest man in history and who built the Temple of God with demonic labour. The attribution accomplishes several things simultaneously: it gives the text a pre-Christian, Scriptural pedigree; it associates magical knowledge with royal power and divine favour; and it frames potentially condemned operations as part of a divinely sanctioned historical project (building the Temple).</p>

<h2>The Attribution Strategy</h2>
<p>Solomonic attribution is not a single fixed claim but a repertoire of framing devices deployed with varying specificity across the tradition. Some texts (the <em>Testament of Solomon</em>) narrate Solomonic magic as a historical event. Others (the <em>Clavicula Salomonis</em>) present themselves as the actual book Solomon compiled from his magical knowledge. Others still invoke "the wisdom of Solomon," "the seal of Solomon," or "the pentacle of Solomon" as authorizing concepts without claiming direct textual transmission. In Islamic tradition, Sulaymanic authority functions in parallel ways across a different set of textual and cultural resources.</p>
<p>Frank Klaassen's <em>The Transformations of Magic</em> (2013) analyses Solomonic attribution as a dynamic textual strategy that changes across the medieval period: earlier texts tend to frame Solomonic magic within a broadly Christian ritual framework (Solomon as proto-Christian king, the demonic work as God-ordained); later texts sometimes adopt the attribution more mechanically, as a conventional marker of the grimoire genre rather than a substantive theological claim. Pablo Torijano's <em>Solomon the Esoteric King</em> (2002) provides the deepest analysis of the attribution across Jewish, Christian, and Islamic sources.</p>""",

"spirit_catalogue": """<h2>Definition</h2>
<p>Analyst Term. A spirit catalogue is a structured list or hierarchy of named demons, angels, or spirits with their individual attributes — ranks, seals or sigils, powers, associated celestial bodies, and sometimes the means of binding or dismissing them — constituting a major organizational feature of the Solomonic grimoire tradition. Spirit catalogues represent one of the most distinctive features of the learned magical tradition, distinguishing it from popular protective magic (which typically addresses spirits generically rather than by name) and from philosophical demonology (which classifies demons theoretically rather than enumerating them operatively).</p>

<h2>Historical Development</h2>
<p>The earliest and most influential spirit catalogue is in the <em>Testament of Solomon</em> (probably second to fifth century CE): thirty-six or more demons are summoned by Solomon, each revealing its name, the affliction it causes, the angel that can thwart it, and (in some recensions) its physical appearance. This pattern — named spirit, function, counteracting angel — is the template replicated across two millennia. The <em>Ars Goetia</em> (part of the seventeenth-century <em>Lemegeton</em>) catalogues seventy-two demons with names, ranks (king, duke, marquis, count, etc.), seals, and powers, derived from an earlier catalogue appended to Johann Weyer's <em>De praestigiis daemonum</em> (1563). The <em>Sepher ha-Razim</em> catalogues the angelic inhabitants of the seven heavens with their periods of activity and adjuration formulas.</p>
<p>Richard Kieckhefer's analysis in <em>Forbidden Rites</em> (1997) treats spirit catalogues as evidence of a learned clerical engagement with demonological classification: the detailed enumeration of spirits by name, rank, and function reflects the same scholastic impulse toward systematic taxonomy visible in natural philosophy and theology. The operative function — using the name to summon the spirit — may be primary, but the classificatory structure reflects learned culture's organizing habits.</p>""",

"superstitio": """<h2>Definition</h2>
<p>Actor Term (Latin). <em>Superstitio</em> — superstition — is the primary theological category through which medieval Christianity condemned magic, divination, and unlawful religious practices. Thomas Aquinas defined superstition in the <em>Summa theologiae</em> (II-II, q. 92) as a vice opposed to the virtue of religion (<em>religio</em>), specifically as giving to creatures — stars, images, demons, lots — the worship, reverence, or trust that belongs to God alone. Superstition encompasses four main species: improper worship of God (idolatry), divination, observances (magical rituals), and vain observances (practices that claim supernatural effects without natural or divine basis).</p>

<h2>Augustine's Foundation</h2>
<p>Augustine of Hippo provided the foundational account in <em>De doctrina christiana</em> (II.20–23): superstition is any compact with demons, explicit or implicit, including the use of amulets, divination, and magical signs. Augustine's concern was not primarily with unusual ritual practices but with the orientation of the will: superstition involves a turning toward creatures for help that belongs to God. This orientation is wrong regardless of whether the operation actually works; even if a demon provides accurate information or genuine healing, the consultation is illicit because it involves the implicit acknowledgment of demonic power.</p>

<h2>Scholastic Elaboration</h2>
<p>Aquinas refined Augustine's account by distinguishing the species of superstition more carefully and by addressing the naturalistic challenges posed by Arabic philosophy: if certain operations work through natural occult properties, are they still superstitious? Aquinas's answer preserved the category: operations that work through natural causes are not superstitious (they are natural philosophy); operations that claim supernatural effects without natural basis, or that invoke non-natural agents, are superstitious because they presuppose demonic cooperation. This framework gave medieval theologians a precise tool for evaluating specific practices — and a tendency to classify them as superstitious whenever a natural explanation was not available.</p>""",

"talismans": """<h2>Definition</h2>
<p>Hybrid Term. A talisman (from Arabic <em>tilasm</em>, possibly from Greek <em>telesma</em>, a consecrated object) is a physical object — typically a figure, seal, or image inscribed on metal, stone, or parchment — created and consecrated under specific astrological conditions to attract and concentrate the influence of a specific celestial body or spirit and direct it toward a practical end. Talismans are central to the astrological magic tradition: they function as material focal points for stellar power, their efficacy depending on the correspondence between their form, material, and the celestial configuration under which they are created.</p>

<h2>Theory</h2>
<p>The theoretical basis for talisman efficacy was provided by Arabic astrological magic, especially al-Kindi's <em>De radiis</em> and Thabit ibn Qurra's <em>De imaginibus</em>. Al-Kindi's theory of stellar rays — all things emit rays that affect other things; the stars emit rays that causally determine terrestrial matter — provided the mechanism by which a material object created at the right astronomical moment could "capture" planetary influence. Thabit's <em>De imaginibus</em> provided practical instructions for making talismans keyed to the planets and fixed stars, specifying the materials (each planet has corresponding metals, plants, and stones), the images to be engraved, the prayers or fumigations to accompany the operation, and the timing.</p>
<p>The <em>Picatrix</em> (Arabic <em>Ghāyat al-ḥakīm</em>, c.1000 CE; Latin translation c.1300) is the most comprehensive resource for talisman magic in the medieval Latin tradition, covering talismans keyed to the twenty-eight lunar mansions as well as the seven planets and providing an extended philosophical account of how they work. David Pingree's critical edition (Warburg Institute, 1986) and the Attrell-Porreca English translation (Penn State, 2019) are the scholarly standards.</p>

<h2>The Scholastic Debate</h2>
<p>Whether talismans were licit was the central question of scholastic astrological magic theory. The <em>Speculum astronomiae</em> (attributed to Albertus Magnus) argued for a tripartite classification: fully licit talismans (using natural materials, natural timing, natural images with no spirit invocation); potentially licit (depending on whether demonic names are included); clearly illicit (explicitly demonic). William of Auvergne and later Thomas Aquinas rejected this framework, arguing that any image that claimed causal efficacy beyond its natural material properties must presuppose demonic assistance. The debate was never definitively resolved and continued into the Renaissance through Ficino, Agrippa, and della Porta.</p>""",

"voces_magicae": """<h2>Definition</h2>
<p>Actor Term. <em>Voces magicae</em> (magical voices or words) designates the strings of untranslatable or apparently meaningless syllables that appear in Greek and Latin magical papyri, in the prayers of the <em>Ars Notoria</em>, and in other learned magical texts. These sequences — typically strings of vowels (AEIOUÔ), divine names in foreign languages (Hebrew, Coptic, Egyptian), or invented-seeming syllables — functioned within the ritual context as efficacious sounds whose power derived from their divine or primordial origin rather than from semantic content.</p>

<h2>Greek Magical Papyri and Late Antique Context</h2>
<p>The Greek Magical Papyri (PGM), a collection of magical texts from Egypt datable to roughly the second century BCE through the fifth century CE, provide the primary corpus of <em>voces magicae</em>. These texts include strings of vowels understood as representations of the seven planetary sounds; divine names in Hebrew (IAO = YHWH, SABAOTH, ADONAI), Coptic, and Egyptian; and invented-seeming sequences (ABLANATHANALBA, AKRAMMACHAMAREI) whose etymology and function are debated. Gideon Bohak's <em>Ancient Jewish Magic</em> (2008) analyses the Jewish divine names in the PGM; Hans Dieter Betz's edition of the PGM (1986) remains the standard collection.</p>

<h2>Medieval Survival</h2>
<p>The <em>Ars Notoria</em> prayers include sequences of Greek, Hebrew, and apparently invented syllables alongside Latin text; these were understood as sacred words whose efficacy derived from divine origin rather than ordinary linguistic meaning. Thomas Aquinas cited these sequences in his condemnation of the <em>Ars Notoria</em>: because they bear no natural relationship to the knowledge they are supposed to produce, their efficacy must presuppose demonic assistance. Practitioners and defenders of the <em>Ars Notoria</em> tradition argued instead that the words preserved a primordial divine language (Adamic or angelic) whose efficacy was given by God rather than by demons — anticipating Dee's Enochian language claim by three centuries.</p>""",

"witchcraft": """<h2>Definition</h2>
<p>Hybrid Term. "Witchcraft" in scholarly usage designates both the historical belief — widely documented across cultures — that certain persons can cause harm (<em>maleficium</em>) through supernatural means, and the specific late medieval and early modern elaboration of that belief into the concept of the diabolical witch: a person who has made an explicit pact with the Devil, attends nocturnal sabbaths, engages in infanticide and cannibalism, and systematically inverts Christian religious practice. These two senses are related but distinct; conflating them distorts the history of both.</p>

<h2>Maleficium and the Common Tradition</h2>
<p>The older, more cross-culturally widespread belief involves <em>maleficium</em> (harmful magic): the attribution of disease, crop failure, livestock death, and other misfortune to the hostile magical action of a neighbour or enemy. This belief — documented in Roman law, early medieval canon law collections, and throughout medieval pastoral literature — constitutes the "common tradition" of popular magic in Kieckhefer's framework. The practitioner accused of maleficium need not be conceptualized as a Satanic witch; accusations of maleficium are structurally similar to accusations of witchcraft in non-Christian societies and do not inherently involve diabolism.</p>

<h2>The Construction of the Diabolical Witch</h2>
<p>The concept of the diabolical witch — the specific demonological construct that drove the major witch trials of the fifteenth through seventeenth centuries — was a learned, clerical construction. Michael Bailey's <em>Battling Demons</em> (2003) traces its emergence in the early fifteenth century from the confluence of three elements: the inquisitorial prosecution of heresy (which provided the concept of diabolical conspiracy), the pastoral concern with maleficium and popular magic, and the learned demonology of scholastic theology. The <em>Malleus Maleficarum</em> (1486) codified the construct: the witch explicitly renounces Christianity, makes a pact with the Devil, attends the sabbath, and performs maleficia through demonic power.</p>
<p>Stuart Clark's <em>Thinking with Demons</em> (1997) analyses early modern demonological writing as an internally coherent intellectual system rather than as mere superstition. Richard Kieckhefer's work, Richard Gordon's studies, and the essays collected in Bengt Ankarloo and Stuart Clark (eds.), <em>Witchcraft and Magic in Europe</em> (6 vols., Athlone/Penn State, 1999–2002), provide comprehensive coverage.</p>""",

}


PERSON_ENRICHMENTS = {

"augustine_of_hippo": """<h2>Life</h2>
<p>Augustine of Hippo (354–430 CE) was born in Thagaste in Roman North Africa (modern Algeria), educated in rhetoric at Carthage, and converted to Christianity in Milan in 386 under the influence of Ambrose of Milan and after years of engagement with Manichaeism and Neoplatonism. He returned to North Africa, was ordained priest, and became Bishop of Hippo Regius in 396, a position he held until his death during the Vandal siege of the city. He is the most influential theologian in the history of Western Christianity, and his writings established the conceptual foundations for medieval demonology, the theology of magic, and the critique of divination.</p>

<h2>Demonology and Magic</h2>
<p>Augustine's engagement with magic and demonology is dispersed across his enormous output but concentrated in several key texts. <em>De civitate Dei</em> (City of God, completed c.426) Books VIII–X — written in response to pagan accusations that Rome's sack in 410 was caused by the abandonment of the old gods — provides the most systematic Christian demonological framework. Augustine argues that the Neoplatonic daemons are real spiritual beings capable of apparent wonders, that all pagan religion constitutes effective (if unwitting) demon-worship, and that theurgic practices like those of Porphyry and Iamblichus are diabolical regardless of their philosophical pretensions. His distinction between divine miracles and demonic wonders (<em>praestigia</em>) — the latter real but limited in scope and always deceptive in intent — became the canonical framework for all subsequent medieval discussion.</p>
<p><em>De divinatione daemonum</em> (On the Divination of Demons) argues that demons can appear to predict the future not because they have genuine foreknowledge (which belongs to God alone) but because they have sharper senses and faster movement than humans, enabling them to observe and report on distant events before human messengers could arrive. This naturalistic reduction of demonic prophecy — demons are cleverer and faster, not genuinely omniscient — became a standard resource for scholastic accounts of what demons could and could not do.</p>
<p><em>De doctrina christiana</em> II.20–23 defines superstition and condemns all magical practices as implicit demonic pact: any appeal to non-divine agents for knowledge or power constitutes the worship of demons and is illicit regardless of outcome or intent.</p>

<h2>Legacy</h2>
<p>Augustine's framework dominated medieval thinking about magic for a millennium. Gratian's <em>Decretum</em> (c.1140) transmitted his anti-divination arguments into canon law; Thomas Aquinas's <em>Summa theologiae</em> repeatedly cites and develops his positions; the <em>Malleus Maleficarum</em> (1486) and subsequent witch-trial literature are unthinkable without the Augustinian framework of demonic pact and diabolical power.</p>""",

"al_kindi": """<h2>Life</h2>
<p>Abu Yusuf Yaʿqub ibn Isḥaq al-Kindi (c.800/01–873 CE) was the first great Arab philosopher and a central figure in the translation movement that transmitted Greek philosophical and scientific learning into Arabic. Born in Basra to an aristocratic Yemeni family and educated in Baghdad, he served at the ʿAbbasid court as a physician and intellectual under al-Maʾmun and al-Muʿtasim, overseeing translations and contributing his own extensive philosophical and scientific writings. He was called "the Philosopher of the Arabs" by later writers. His works cover mathematics, astronomy, optics, medicine, philosophy, and music — as well as astrology and magic.</p>

<h2>De radiis and the Theory of Rays</h2>
<p><em>De radiis stellarum</em> (On Stellar Rays) — the Latin title of a work whose Arabic original does not survive — is al-Kindi's most influential contribution to the history of magic. The work, probably written around 850 CE and surviving only in a medieval Latin translation (probably twelfth century), argues that all things in the world continuously emit rays in all directions, analogous to the way light radiates from a luminous body. These rays carry the qualities of their source and affect the things they strike. Celestial bodies emit the most powerful rays, but sublunary things also emit them; the human voice, when charged with intense mental concentration, can similarly emit effective rays. A person with the right knowledge can exploit this ray-system to produce effects at a distance — which is what magic is.</p>
<p>This theory had enormous influence on Latin natural philosophy and magic theory. Robert Grosseteste's metaphysics of light and optics drew on similar principles. Roger Bacon's theory of "multiplication of species" — the fundamental causal mechanism in his account of perception and celestial influence — is closely related. Thabit ibn Qurra's <em>De imaginibus</em>, which provides practical instructions for astrological image magic, presupposes al-Kindi's theoretical framework. David Pingree's analysis of al-Kindi's place in the tradition and Betsey Barker Price's work on the Latin reception of <em>De radiis</em> provide the scholarly context.</p>""",

"david_pingree": """<h2>Life and Scholarship</h2>
<p>David Pingree (1933–2005) was Professor of History of Mathematics and History of Science at Brown University and the most productive editor and translator of mathematical, astronomical, and magical texts in the Western historical tradition. His output — spanning Sanskrit, Persian, Arabic, Greek, and Latin — was extraordinary in its scope and precision. He is described by colleagues as having produced more critical editions of primary sources in the history of science and astrology than any other scholar of his generation.</p>

<h2>Work on the Magical Tradition</h2>
<p>For the history of magic, Pingree's most important contributions are his critical editions of the <em>Picatrix</em> (2 vols., Warburg Institute Studies 39, 1986) — the standard scholarly edition of both the Latin text and the related Arabic tradition — and of Thabit ibn Qurra's <em>De imaginibus</em>, al-Kindi's astrological works, and numerous other texts in the astrological-magical tradition. His edition of the <em>Picatrix</em> established the manuscript tradition, identified the Arabic sources, and provided the essential tools for all subsequent scholarship on the most comprehensive medieval text of astrological magic. Without Pingree's editions, systematic scholarly work on the Arabic-Latin transmission of astral magic theory would be impossible.</p>
<p>Pingree also produced critical editions of several Sanskrit astrological texts, Persian astronomical tables, and Greek astrological compilations, demonstrating through these comparative editions the transmission routes through which ancient Babylonian and Hellenistic astronomy and astrology reached Arabic, Persian, and eventually Latin learning. His contributions to understanding the exact bibliographic and textual transmission paths of magical and astrological knowledge set the standard for subsequent work in the field.</p>

<h2>Legacy</h2>
<p>Pingree's students and successors — including Charles Burnett, Julio Samsó, and others working on the Arabic-Latin transmission — continue the philological tradition he established. His <em>Picatrix</em> edition, in particular, remains the indispensable scholarly resource for anyone working on astrological magic theory in the medieval Latin tradition.</p>""",

"gideon_bohak": """<h2>Life and Scholarship</h2>
<p>Gideon Bohak is Professor of Jewish Philosophy at Tel Aviv University and the leading authority on ancient Jewish magic from antiquity through the rabbinic period. His training combined classical philology, Semitic languages, and the history of Judaism, enabling him to work across the range of material evidence — Greek magical papyri, Aramaic incantation bowls, Hebrew amulets, Genizah fragments, and rabbinic literature — that documents Jewish magical practice in late antiquity.</p>

<h2>Ancient Jewish Magic: A History</h2>
<p><em>Ancient Jewish Magic: A History</em> (Cambridge University Press, 2008) is Bohak's major work and the most comprehensive account of Jewish magical practice from the biblical period through the end of antiquity. The book surveys the full range of material evidence: biblical and Second Temple literary sources, the Dead Sea Scrolls (particularly the Songs of the Maskil and related angelic adjuration texts), the Greek magical papyri (which contain extensive Jewish material including divine names — YHWH, IAO, SABAOTH, ADONAI — and Hebrew adjuration formulas), Aramaic incantation bowls from Babylonian Jewish communities (sixth to eighth centuries CE), and Hebrew and Aramaic amulet texts from the Cairo Genizah.</p>
<p>Bohak argues against the view that "Jewish magic" was simply an undifferentiated part of a homogeneous Mediterranean magical culture. He demonstrates that Jewish magical practice had distinctive features — its reliance on divine names, its engagement with biblical and pseudepigraphic narrative, its use of Hebrew and Aramaic in specifically Jewish formulas — that mark it as a coherent tradition with its own history, even as it participated in and contributed to the broader Mediterranean magical culture from which Greek, Roman, Christian, and Islamic magical traditions also emerged.</p>

<h2>Significance for Solomonic Studies</h2>
<p>For the Solomonic tradition specifically, Bohak's work provides the essential Jewish background: the earliest attestations of Solomonic magical authority, the relationship between Second Temple angelic adjuration and the later Solomonic grimoire tradition, and the role of Hebrew divine names and angelic catalogues in shaping the magic of the <em>Sepher ha-Razim</em>, the <em>Testament of Solomon</em>, and ultimately the Latin <em>Clavicula Salomonis</em>. His work, together with Pablo Torijano's <em>Solomon the Esoteric King</em> (2002), provides the foundational scholarly account of the Solomonic tradition's Jewish roots.</p>""",

"michael_d_bailey": """<h2>Life and Scholarship</h2>
<p>Michael D. Bailey is Professor of History at Iowa State University and one of the leading historians of medieval and early modern magic and witchcraft. His scholarship focuses on the intersection of magic, heresy, and religious reform in the late medieval period, with particular attention to the construction of the diabolical witch concept and the social history of magical practice in the fifteenth and sixteenth centuries.</p>

<h2>Major Works</h2>
<p><em>Battling Demons: Witchcraft, Heresy, and Reform in the Late Middle Ages</em> (Penn State University Press, 2003) is Bailey's most important work and the most thorough analysis of the emergence of the diabolical witch concept in the early fifteenth century. Bailey argues that the witch-sabbath construct was not a simple outgrowth of popular belief but was created by a specific group of reform-minded clerics — primarily in the Alpine regions of the Diocese of Lausanne and the western Alps — who combined the inquisitorial concern with heretical conspiracy with the pastoral concern over maleficium and with learned demonological theory. The book identifies Johannes Nider's <em>Formicarius</em> (c.1437) as the key text in which these elements first coalesce into the full diabolical witch concept.</p>
<p><em>Magic and Superstition in Europe: A Concise History from Antiquity to the Present</em> (Rowman and Littlefield, 2006) provides a broader synthetic overview of European magical practice and its regulation from ancient Rome through the twentieth century. The book is notable for its clarity and its attention to the problems of definition that have bedevilled the historiography of magic.</p>
<p><em>Fearful Spirits, Reasoned Follies: The Boundaries of Superstition in Late Medieval Europe</em> (Cornell University Press, 2013) examines how late medieval thinkers — theologians, inquisitors, pastoral writers — drew and defended the boundaries between licit religious practice and condemned superstition, and how these boundary-drawing efforts both reflected and shaped the prosecution of magic and witchcraft.</p>""",

"nicolas_weill_parot": """<h2>Life and Scholarship</h2>
<p>Nicolas Weill-Parot is a French historian of science and philosophy at the École pratique des hautes études in Paris, specializing in medieval and Renaissance natural philosophy, astrology, and the history of learned magic. His work is distinguished by its combination of rigorous philological analysis of primary sources with sophisticated philosophical reconstruction of the theoretical frameworks within which medieval natural philosophers discussed magical phenomena.</p>

<h2>Addressative Magic and the Speculum astronomiae</h2>
<p>Weill-Parot's most important contribution is his development of the concept of "addressative magic" (<em>magie addressative</em>), elaborated in his monumental study <em>Les "images astrologiques" au Moyen Âge et à la Renaissance: Spéculations intellectuelles et pratiques magiques (XIIe–XVe siècle)</em> (Honoré Champion, 2002). Addressative magic designates magical operations that explicitly address spiritual agents — demons, angels, or planetary spirits — as personal, rational beings responsive to command or invocation, as opposed to operations that merely exploit impersonal natural forces. Weill-Parot argues that the scholastic condemnation of image magic targeted specifically the addressative dimension: images that worked through natural celestial causes (as Albertus Magnus attempted to defend) were potentially licit; images that required explicit invocation of spirits were condemned as demonic.</p>
<p>His analysis of the <em>Speculum astronomiae</em> and its attribution dispute — Weill-Parot argues against the attribution to Albertus Magnus on both historical and internal grounds — has been controversial but has significantly advanced the historiography. His broader work on the relationship between natural philosophy and magic in the thirteenth and fourteenth centuries, particularly his account of William of Auvergne as the key transition figure, provides the indispensable context for understanding scholastic engagement with the Arabic magical tradition.</p>""",

"nicole_oresme": """<h2>Life</h2>
<p>Nicole Oresme (c.1320–1382) was a French philosopher, mathematician, and theologian who studied at the Collège de Navarre in Paris under Jean Buridan, became Master of the Collège de Navarre, was appointed canon of Rouen (1362), and eventually served as Bishop of Lisieux (1377). He was a close advisor to King Charles V of France and translated several Aristotelian works into French at royal request. He is recognized as one of the most original thinkers of the fourteenth century for his mathematical and physical innovations (the latitude of forms, the graphical representation of change, proto-impetus theory).</p>

<h2>Magic and Wonders</h2>
<p>Oresme wrote two works directly relevant to the history of magic. <em>De causis mirabilium</em> (On the Causes of Wonders, c.1360) argues systematically that all apparent marvels and wonders — including those typically attributed to demons or supernatural forces — can be explained through natural causes: optical illusions, the imagination's influence on the body, unusual properties of specific places or times, the suggestibility of the human mind. This systematic naturalization of the marvellous was not intended as a denial of the supernatural but as a methodological first step: natural explanation should be attempted before supernatural causes are invoked.</p>
<p><em>Tractatus contra astronomos</em> (also called <em>Livre de divinacions</em> in its French version) attacked judicial astrology — the prediction of specific future events from horoscopes — as neither scientifically valid nor morally permissible. Oresme's arguments anticipate later sceptical challenges to astrology: celestial influence on terrestrial matter may be real, but the precision required for horoscopic prediction far exceeds what the theory can deliver, and the claim to determine the future of individuals undermines free will. His critique of astrology was influential on subsequent natural philosophical discussions of celestial influence and its limits.</p>""",

"pico_della_mirandola": """<h2>Life</h2>
<p>Giovanni Pico della Mirandola (1463–1494) was born into the ruling family of Mirandola in Emilia, studied canon law at Bologna, philosophy at Ferrara and Padua, and Arabic and Kabbalah in Florence and Perugia. He was a prodigy in multiple languages (Latin, Greek, Hebrew, Arabic, Aramaic) and in philosophy, and his short career — he died at thirty-one, possibly of poisoning, in the year the French invaded Italy — produced works of extraordinary ambition and originality. He was closely associated with Ficino's Florentine milieu but also a distinctly independent and more radical thinker.</p>

<h2>The 900 Conclusiones and Christian Kabbalah</h2>
<p>Pico's <em>Conclusiones nongentae</em> (900 Conclusions, 1486) — 900 theses drawn from ancient, medieval, and contemporary sources, including 72 Kabbalistic and 26 "magical" theses — were intended for a public debate in Rome that Pope Innocent VIII refused to permit. Thirteen of the theses were condemned as heretical; Pico fled to France, was arrested, and returned to Florence under Medici protection. The condemned theses included claims that Kabbalistic art confirmed the divinity of Christ and that no science demonstrates the resurrection more effectively than natural magic and Kabbalah.</p>
<p>Pico's contribution to the history of magic was twofold. First, he added Christian Kabbalah to the Renaissance occult synthesis as the highest form of magical technology: manipulating the Hebrew divine names and sefirot could accomplish what natural magic and astral magic could not, because it operated at the level of the divine intellectual world rather than the elemental or celestial. Second, his <em>Oratio de dignitate hominis</em> (Oration on the Dignity of Man, composed as a preface to the 1486 debate but not delivered) articulated the vision of the magus as the person who unites all the worlds within himself — elemental, celestial, intellectual — and thereby achieves a form of deification. This vision became the standard Renaissance image of the philosopher-magician.</p>

<h2>Later Work</h2>
<p>After his condemnation and pardon, Pico moved toward a more sceptical position on magic: his posthumously published <em>Disputationes adversus astrologiam divinatricem</em> (Disputations against Divinatory Astrology, 1496) constitutes one of the most systematic Renaissance attacks on judicial astrology, anticipating many of the arguments that Kepler and later sceptics would make. His <em>Heptaplus</em> (1489) and <em>De ente et uno</em> (1492) represent a more orthodox Neoplatonist theology, less explicitly magical than the <em>Conclusiones</em>.</p>""",

"reginald_scot": """<h2>Life</h2>
<p>Reginald Scot (c.1538–1599) was an English squire from Kent, a justice of the peace and hop-farmer, who in 1584 published <em>The Discoverie of Witchcraft</em> — one of the most remarkable books of the Elizabethan period and the most thorough sceptical treatment of witchcraft beliefs in sixteenth-century England. Scot had no formal theological or philosophical training, but he assembled an enormous range of sources (classical, patristic, medieval, and contemporary) to argue that the witch trials were a combination of judicial murder and theological delusion.</p>

<h2>The Discoverie of Witchcraft</h2>
<p><em>The Discoverie of Witchcraft</em> (1584) is a work of two distinct ambitions. First, it is a sceptical argument against the reality of the diabolical witch: Scot marshals evidence and argument to demonstrate that the accused women in witch trials are mentally ill, senile, or poor and marginalized individuals whose confessions are products of delusion, coercion, or ignorance rather than genuine evidence of demonic pact. His humanitarian concern for the accused — directed partly against the <em>Malleus Maleficarum</em> and its Continental counterparts — is genuine and historically important as an early defence of what we might now call procedural justice.</p>
<p>Second, and paradoxically, <em>The Discoverie</em> contains an extensive collection of conjuration procedures, exorcism rituals, and magical formulas, apparently reproduced to demonstrate that learned magic is no more real than witchcraft — but in the process providing one of the most comprehensive sixteenth-century accounts of Elizabethan magical practice. Books XV and XVI of the <em>Discoverie</em> contain conjuration rituals drawn from or similar to those in the <em>Heptameron</em>, the <em>Ars Almadel</em>, and related texts, making Scot's sceptical treatise also a primary source for the history of English ritual magic.</p>

<h2>Reception</h2>
<p>James VI of Scotland (later James I of England) included Scot among those he attacked in his <em>Daemonologie</em> (1597); according to tradition (disputed by scholars), James ordered copies of the <em>Discoverie</em> burned when he became King of England in 1603. Ben Jonson, Christopher Marlowe, and Shakespeare all drew on Scot for magical material. His influence on the seventeenth-century English tradition of magical scepticism is significant.</p>""",

"solomon": """<h2>The Biblical and Legendary Solomon</h2>
<p>Solomon, son of David and King of Israel (traditionally c.970–931 BCE), is one of the most important figures in the history of religion and magic: a historical ruler about whom almost nothing can be independently verified, but whose legendary attributes — surpassing wisdom, fabulous wealth, architectural achievement (the Temple), and mastery of demons and spirits — made his name the primary authorizing signature of the learned magical tradition across Jewish, Christian, and Islamic cultures for two millennia.</p>

<h2>Biblical Solomon</h2>
<p>The biblical accounts of Solomon in 1 Kings and 2 Chronicles establish the basic attributes: the gift of divinely-granted wisdom (surpassing all other men), wealth beyond ordinary description, the construction of the Temple in Jerusalem, and ultimately the apostasy into which his foreign wives led him. The Wisdom literature of the Hebrew Bible was attributed to Solomon (Proverbs, Ecclesiastes, Song of Songs, and in the Septuagint, the Wisdom of Solomon and Psalms of Solomon), establishing him as the paradigmatic wise man and author of authoritative texts.</p>

<h2>The Magical Solomon</h2>
<p>The magical attributes not found in the main biblical narrative developed in Second Temple Jewish literature and in the Hellenistic and late antique period. Josephus (first century CE) describes Solomon as an expert in exorcism using a ring and the plant baaras, and notes that his craft was still practised in Josephus's own time. The <em>Testament of Solomon</em> (probably second to fifth centuries CE) provided the fullest narrative account of Solomon's magical career: the ring given by Michael, the summoning and interrogation of thirty-six demons, their compelled labour in building the Temple. This text established the structural template — named demons, Solomonic authority, divine names as binding force — that the entire subsequent grimoire tradition replicates.</p>
<p>In Islam, Sulayman is a prophet-king granted power over jinn, wind, and animals by divine command (Qurʾan 27, 34). Islamic commentators elaborated his magical power extensively. In late medieval and early modern European magic, "Solomon" functions primarily as an authorizing label: the texts' claim to Solomonic origin is a pseudepigraphic strategy, not a historical claim. Pablo Torijano's <em>Solomon the Esoteric King</em> (2002) provides the most thorough cross-cultural analysis.</p>""",

"thabit_ibn_qurra": """<h2>Life</h2>
<p>Thabit ibn Qurra al-Harrani (c.836–901 CE) was a Sabian mathematician, astronomer, and philosopher from Harran (in modern southern Turkey), working in Baghdad under the patronage of the Banu Musa brothers and later of the ʿAbbasid court. The Sabians of Harran were a pagan community who preserved Neoplatonic and Hermetic traditions alongside astronomical and mathematical learning; their religious practice involved planetary worship and ritual addressed to the celestial bodies, which gave Thabit both theoretical and practical interest in the relationship between celestial bodies and terrestrial things. He is one of the most productive and original scientists of the ninth century, contributing to mathematics, astronomy, mechanics, and medicine.</p>

<h2>De imaginibus and Astral Magic</h2>
<p><em>De imaginibus</em> (On Images) is Thabit's treatise on astral image magic, surviving in Latin translation (the Arabic original does not appear to be extant, though similar texts exist in Arabic). The work provides practical instructions for making talismans keyed to the planets and fixed stars: for each operation, it specifies the appropriate planetary hour and configuration, the materials to be used (each planet corresponds to specific metals, plants, and stones), the image to be engraved or cast, the fumigations and prayers to accompany the operation, and the practical ends that can be achieved. The theoretical basis is al-Kindi's ray theory combined with Neoplatonic doctrine of the world-soul and planetary intelligences.</p>
<p>David Pingree edited and analysed <em>De imaginibus</em> in the context of the broader tradition of Arabic astrological magic. The text was known to and used by Latin natural philosophers from the twelfth century: the <em>Speculum astronomiae</em> cites Thabit's works on images as examples of potentially licit astrological magic (those operating through natural celestial causes rather than demonic names). Nicolas Weill-Parot's work on addressative magic situates <em>De imaginibus</em> within the scholastic controversy over image magic.</p>""",

"valerie_flint": """<h2>Life and Scholarship</h2>
<p>Valerie I.J. Flint (1936–2009) was a historian of medieval religion and culture at the University of Hull and later the University of Auckland, whose work challenged the dominant historiographical model of the early medieval Church as simply suppressive of pagan and magical practices. Her scholarship argued for a more complex and ambivalent relationship between institutional Christianity and the popular magical practices it officially condemned.</p>

<h2>The Rise of Magic in Early Medieval Europe</h2>
<p><em>The Rise of Magic in Early Medieval Europe</em> (Princeton University Press, 1991) is Flint's major work and one of the most provocative interventions in the historiography of medieval magic. Flint argues that the early medieval Church did not simply condemn and suppress popular magic: it deliberately accommodated, Christianized, and in some respects promoted forms of magical practice that it reframed as compatible with orthodox Christianity. Healing rituals, protective charms, divination, and even some forms of spirit-consultation were tolerated or transformed rather than eliminated, because the Church needed to win converts from precisely the social world where such practices were embedded.</p>
<p>The argument rests on close reading of pastoral texts, penitentials, canon law collections, and hagiography from the sixth through eleventh centuries. Flint shows how the same practices (using written texts for healing, consulting the calendar for lucky and unlucky days, employing protective objects) appear in both condemned and approved contexts, and argues that the difference is often one of authorization and framing rather than content. A charm using the Lord's Prayer rather than a pagan deity's name is structurally identical to its pagan predecessor but theologically transformed.</p>

<h2>Reception and Significance</h2>
<p>Flint's thesis was controversial: critics argued that she overstated the degree of ecclesiastical endorsement and understated genuine suppression. Richard Kieckhefer, Karen Louise Jolly, and others have engaged with and refined her argument. Her work is significant for insisting that the relationship between institutional Christianity and popular magic was not simply one of condemnation and resistance, and for drawing attention to the pastoral and missionary contexts within which early medieval attitudes toward magic were formed.</p>""",

}


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    updated = 0
    for slug, html in CONCEPT_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM concepts WHERE slug=?", (slug,)).fetchone()
        if row:
            conn.execute("UPDATE concepts SET definition_long=? WHERE slug=?", (html, slug))
            print(f"  concept: {slug} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING concept: {slug}")

    for pid, html in PERSON_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM persons WHERE person_id=?", (pid,)).fetchone()
        if row:
            conn.execute("UPDATE persons SET bio_html=? WHERE person_id=?", (html, pid))
            print(f"  person: {pid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING person: {pid}")

    conn.commit()
    print(f"\nUpdated {updated} entries.")
    conn.close()


if __name__ == "__main__":
    main()
