"""
Enrich batch 9: remaining concepts and persons.
"""
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import DB_PATH


CONCEPT_ENRICHMENTS = {

"grimoire_corpus": """<h2>Definition</h2>
<p>Analyst Term. The "grimoire corpus" designates the body of learned magical texts — manuscripts and printed books — that transmit practical ritual magic: conjuration procedures, spirit catalogues, talismanic operations, and related material. The term "corpus" is an analyst construct: no medieval practitioner used it, and the texts now grouped under it were never a unified canon. Nevertheless, scholars find the concept useful for designating a recognizable tradition with shared features — Solomonic attribution, spirit hierarchies, ritual apparatus, astrological timing — that persists from late antiquity through the nineteenth century with remarkable structural stability.</p>

<h2>Core Texts and Boundaries</h2>
<p>The core of the Solomonic grimoire corpus consists of a group of interrelated texts that share structural features and have demonstrable textual relationships: the <em>Clavicula Salomonis</em> (Key of Solomon), the <em>Lemegeton</em> (Lesser Key of Solomon, comprising five books), the <em>Sworn Book of Honorius</em>, the <em>Hygromanteia</em>, the <em>Ars Notoria</em>, and the <em>Liber Razielis</em>. Surrounding this core is a wider field of texts with varying degrees of connection: the <em>Picatrix</em> and the astrological image magic tradition (related by subject matter but with independent transmission); the pseudo-Aristotelian and pseudo-Albertine natural magic compilations (related by genre); the eighteenth-century French chapbook grimoires (related by the commercial tradition but not by direct textual descent from the medieval Solomonic texts).</p>
<p>Frank Klaassen's concept of the "experiment literature" in <em>The Transformations of Magic</em> (2013) provides a useful functional definition: texts that record practical magical procedures (<em>experimenta</em>, experiments), whether or not they belong to the Solomonic attribution tradition. This functional definition includes texts that earlier scholarship sometimes excluded (simple charm collections, medical magical recipes) while appropriately situating the Solomonic grimoires within a broader tradition of practical magical record-keeping. Owen Davies's <em>Grimoires: A History of Magic Books</em> (2009) provides the most comprehensive historical account of how the corpus evolved from antiquity to the present.</p>""",

"chiromancy": """<h2>Definition</h2>
<p>Actor Term. Chiromancy (from Greek <em>cheir</em>, hand, and <em>manteia</em>, divination) is divination from the lines, mounts, and features of the hand — the discipline that later tradition called palmistry. Medieval chiromancy was a learned divinatory art, transmitted in Latin texts and taught in university contexts, distinct from the popular palmistry of marketplace fortune-tellers; it claimed a connection to astrological theory (the lines and mounts of the hand correspond to the seven planets) that gave it the same naturalistic basis as astrology. The major medieval Latin chiromantic texts include the <em>Chiromantia</em> attributed to Ciromnides and texts associated with Michael Scot, Albertus Magnus, and various Arabic authorities.</p>

<h2>Theory and Practice</h2>
<p>Medieval chiromantic theory held that the hand revealed the person's complexion (humoral constitution), temperament, and destiny through features that corresponded to planetary influences: the Mount of Jupiter under the index finger, the Mount of Saturn under the middle finger, the Mount of Apollo under the ring finger, and so on. The lines of the hand — the "line of life," "line of head," and "line of heart" — were interpreted in relation to these planetary mounts and to the overall balance of humours evident in the hand's colour, texture, and proportions.</p>
<p>Johannes Hartlieb's <em>Buch aller verbotenen Kunst, Unglaubens und der Zauberei</em> (c.1456) listed chiromancy among the seven forbidden arts, alongside geomancy, necromancy, and astrology in its divinatory form. However, chiromancy circulated in university contexts and was defended by some as a legitimate application of astrological theory to the body: if the stars impress their qualities on human constitution, the hand might reasonably manifest those impressions in readable form. Sophie Page's work on magical manuscripts in institutional collections documents chiromantic texts appearing alongside medical and astrological material.</p>""",

"experimenta": """<h2>Definition</h2>
<p>Actor Term (Latin plural). <em>Experimenta</em> (experiments, singular: <em>experimentum</em>) is the standard medieval Latin term for individual practical magical procedures — the discrete recorded operations that constitute the practical content of magical handbooks. An <em>experimentum</em> specifies what to do (materials, words, actions), when to do it (timing by planetary hours, lunar phases, or calendar days), and what result to expect. The term is neutral with respect to the moral status of the operation: the same word covers medical recipes, natural philosophical observations, and demonic conjurations, reflecting the medieval understanding of magic as a form of practical technology rather than a categorically distinct enterprise.</p>

<h2>The Experiment Literature</h2>
<p>Frank Klaassen coined the term "experiment literature" to designate the body of texts that record <em>experimenta</em>, distinguishing this practical literature from the theoretical natural philosophy that provided its intellectual context. The <em>experimenta</em> tradition spans the full social range of medieval magical practice: from the simple vernacular charm ("take three hairs from a black cat and bury them at a crossroads") through the elaborate Latin conjuration of the Munich Manual, the same basic format — specified materials, actions, timing, and expected result — underlies the practical content.</p>
<p>The textual history of <em>experimenta</em> is characterized by extreme mobility: individual experiments circulated freely, were extracted from one compilation and incorporated into another, were translated between Latin and vernacular, and were modified in transmission in ways that make it very difficult to establish priority between related texts. This mobility is itself evidence for the practical orientation of the tradition: what mattered was whether the <em>experimentum</em> worked, not who composed it or what theoretical framework it presupposed. Klaassen's <em>The Transformations of Magic</em> (2013) and Sophie Page's <em>Magic in the Cloister</em> (2013) both engage extensively with the <em>experimenta</em> tradition.</p>""",

"magical_alphabets": """<h2>Definition</h2>
<p>Actor Term. Magical alphabets are invented or adapted writing systems used in magical texts, either for writing divine names, spirit names, and magical words in a visually distinctive form, or for encrypting magical content so that it is not immediately legible to the uninitiated. The most famous examples associated with the Western learned magic tradition are the Theban script (attributed in late sources to Honorius of Thebes, though its actual origin is obscure), the Malachim script, the Passing of the River script, and the Enochian alphabet revealed to John Dee and Edward Kelley in 1583.</p>

<h2>Function and Significance</h2>
<p>Magical alphabets served multiple functions within the traditions that used them. First, they provided a visually distinctive form for divine and spirit names that emphasized their sacred or foreign character — using a non-standard script to write the name of an angel marks it as something other than ordinary language, imbuing it with the aura of esoteric knowledge. Second, they provided a degree of practical encryption: a text written in Theban or Malachim could not be read by someone who had not been taught the correspondence table, offering some protection from casual discovery.</p>
<p>Cornelius Agrippa's <em>De occulta philosophia</em> III includes tables of several magical alphabets with their Latin equivalents, presenting them as ancient or angelic scripts with intrinsic magical significance. The Enochian alphabet received by John Dee and Edward Kelley during their angel conversations (1583) was presented as the actual angelic language — the language in which God spoke to Adam before the Fall — and its letters carry specific phonological values and mystical associations documented in Dee's diaries. The subsequent ceremonial magic tradition (Golden Dawn, Thelema) has elaborated the Enochian system extensively, using the alphabet in ritual practice.</p>""",

"pastoral_care_and_magic": """<h2>Definition</h2>
<p>Analyst Term. "Pastoral care and magic" designates the intersection between the institutional Church's programme of pastoral oversight — guiding lay Christians in proper religious practice — and the magical practices that pastoral handbooks, penitentials, and sermon literature consistently documented, condemned, and sometimes tacitly accommodated. The pastoral literature is one of the primary historical sources for knowledge of popular magical practice in medieval Europe, precisely because pastoral writers needed to know what practices existed in order to direct confessors to inquire about them and assign appropriate penances.</p>

<h2>The Penitential Tradition</h2>
<p>From the sixth century onward, penitential handbooks — guides for confessors listing sins and their appropriate penances — included sections on magical practices. Burchard of Worms's <em>Decretum</em> (c.1012), Book XIX (the <em>Corrector sive Medicus</em>), is the most comprehensive early medieval catalogue of popular magical practices for which penances were to be imposed: it covers charm-use, love magic, healing rituals, divination, weather-working, and many other practices, providing the most detailed window available into what popular magic actually consisted of in eleventh-century Germany. Similar material appears in Regino of Prüm's penitential (c.906) and in the penitentials of the insular tradition.</p>
<p>The later medieval tradition of sermon exempla — brief narratives used to illustrate moral points in preaching — provides another documentary layer: preachers recorded stories of magical practitioners (cunning folk, fortune-tellers, treasure-hunters) that give a sense of what their pastoral audiences knew and expected. Valerie Flint's <em>The Rise of Magic in Early Medieval Europe</em> (Princeton, 1991) analyses the pastoral literature's role in both condemning and accommodating popular magic. The essays in Don Bailey's and Catherine Rider's edited volumes extend this analysis to the later medieval period.</p>""",

"planetary_spirits": """<h2>Definition</h2>
<p>Hybrid Term. Planetary spirits designate the intelligent beings — neither fully material nor fully divine — that Renaissance Neoplatonism and the astrological magic tradition posited as intermediaries between the celestial bodies (as physical objects) and their effects on terrestrial life. In the Neoplatonic hierarchy, each planet is governed by an intelligence (<em>intelligentia</em>) that moves it and by a spirit (<em>spiritus</em>) that conveys its influence to the sublunary world. The magic of Ficino, Agrippa, and the <em>Picatrix</em> tradition engages with these planetary spirits as potential partners in magical operation.</p>

<h2>Theory</h2>
<p>The doctrine of planetary spirits derives from the Neoplatonic account of the celestial hierarchy: Plotinus, Iamblichus, and Proclus all discussed the daemons associated with the planets as intermediary beings between the divine intellect and material creation. In the Arabic astrological tradition, each planet was associated with an intelligence (a governing rational being) and a spirit (an executive power), whose cooperation could be secured through appropriate ritual — the right materials, timing, images, prayers, and fumigations specified by texts like the <em>Picatrix</em> and Thabit ibn Qurra's <em>De imaginibus</em>. Agrippa's <em>De occulta philosophia</em> II provides the standard Renaissance account, connecting the planetary intelligences to specific divine names and the planetary spirits to the camea (magic squares) of each planet.</p>
<p>The theological problem was the same as with all astrological magic: were the planetary spirits simply natural forces (and therefore exploitable within natural philosophy) or personal, rational agents (and therefore addressative magic that required explicit invocation and risked demonic cooperation)? Nicolas Weill-Parot's analysis of addressative magic identifies this question as the central contested point of scholastic astrological magic theory. The Renaissance resolution — treating planetary spirits as aspects of the natural celestial mechanism rather than as personal beings — was philosophically unstable but practically necessary for maintaining the claim to natural philosophy.</p>""",

"prohibited_arts": """<h2>Definition</h2>
<p>Actor Term (Latin: <em>artes prohibitae</em>; also <em>artes vetitae</em>, <em>artes damnabiles</em>, <em>artes illicitae</em>). The prohibited arts is the standard medieval category for magical, divinatory, and related practices condemned by canon law, theological teaching, and ecclesiastical authority. The category is defined negatively — by what the Church forbids — and its contents are relatively stable across the medieval period, derived primarily from Isidore of Seville's taxonomy in <em>Etymologiae</em> VIII.9 and codified in Gratian's <em>Decretum</em>.</p>

<h2>Content of the Category</h2>
<p>The prohibited arts typically include: necromancy (demonic conjuration); geomancy, pyromancy, hydromancy, and aeromancy (elemental divination); chiromancy (palmistry); augury and auspicy (divination from birds and natural signs); haruspicy (divination from entrails); astrology in its judicial form (predicting individual futures from horoscopes, as distinct from the legitimate natural science of astronomy); sortilege (divination by lot); and various forms of charm-use and image magic. The precise list varies between authorities — Isidore's taxonomy was the standard reference, but it was expanded and reorganized by subsequent writers including Rabanus Maurus, Johannes Hartlieb, and the authors of the late medieval magic classification treatises.</p>
<p>The boundary between the prohibited arts and legitimate natural philosophy was never definitively established. Natural magic — the use of occult natural properties without demonic assistance — occupied an ambiguous position: it was not straightforwardly included in the prohibited arts (since it claimed natural rather than demonic causation) but it was not clearly excluded either (since the claim to purely natural operation was philosophically contested). The negotiation of this boundary was the central intellectual task of scholastic magic theory from the twelfth century onward. Johannes Hartlieb's <em>Buch aller verbotenen Kunst</em> (c.1456) provides the most accessible vernacular account of the prohibited arts in their late medieval formulation.</p>""",

"reformation_and_magic": """<h2>Definition</h2>
<p>Analyst Term. "The Reformation and magic" designates the complex and contested relationship between the Protestant and Catholic reformations of the sixteenth century and the magical practices they inherited, tolerated, attacked, and transformed. The relationship is multidimensional: the Reformations attacked Catholic ritual as magic (the Mass as transubstantiation, indulgences, relic veneration); created new demarcations between acceptable religion and condemned superstition; intensified prosecution of witchcraft in some contexts while creating scepticism about it in others; and produced new forms of providentialist thinking that both condemned divination and generated prophetic cultures of their own.</p>

<h2>Protestantism and Magic</h2>
<p>Protestant reformers faced a distinctive problem: their dismantling of the Catholic sacramental and ritual system — exorcism, holy water, blessed candles, the sign of the cross as protection against demons — removed the institutional tools that had provided ordinary people with protection against maleficium. If holy water no longer worked against demons, what did? Protestant responses varied: some insisted that providentialist prayer and faith were the only legitimate protection; others tolerated or even promoted cunning folk and practical magic as filling the gap left by the abolished Catholic protective rituals. Keith Thomas's <em>Religion and the Decline of Magic</em> (1971) argued that the Reformation's dismantling of Catholic magic created the demand for popular magic that cunning folk met. This thesis has been qualified by subsequent work showing that Catholic regions also had thriving popular magic cultures.</p>
<p>The Protestant witch-hunting of the sixteenth and seventeenth centuries is a further dimension: if Protestant reformers were more aggressive in pursuing witchcraft prosecutions in some regions, this was not because they took magic more seriously than Catholics but because the institutional reconfiguration of the relationship between religion and magic created new anxieties and new legal frameworks. Brian Levack's <em>The Witch-Hunt in Early Modern Europe</em> provides the standard overview. Stuart Clark's <em>Thinking with Demons</em> (1997) analyses Protestant and Catholic demonological writing as parallel intellectual systems.</p>""",

"ritual_purity": """<h2>Definition</h2>
<p>Actor Term. Ritual purity designates the state of bodily and spiritual cleanliness required of the practitioner before performing magical operations in the Solomonic and related learned magical traditions. The Solomonic grimoires are consistent in their insistence on preparatory purification: the practitioner must fast, abstain from sexual activity, confess sins, attend Mass or perform equivalent devotions, wash the body, wear clean vestments, and avoid polluting contacts for a specified period (typically three to nine days) before undertaking a major conjuration. These requirements distinguish learned Solomonic magic from simple charm-use and align it with the ritual preparation expected of priests performing the sacraments.</p>

<h2>Sources and Parallels</h2>
<p>The purity requirements of the Solomonic grimoires derive from multiple sources: Jewish priestly purity laws (Leviticus, Numbers), which specified conditions for approaching the divine; Neoplatonic theurgy, in which the philosopher's ascent required moral and physical preparation; and the medieval Christian tradition of sacramental preparation, which required confession and fasting before communion. The <em>Clavicula Salomonis</em> and the <em>Sworn Book of Honorius</em> are particularly insistent on these requirements; the <em>Ars Notoria</em> extends the preparatory period over weeks or months.</p>
<p>The purity requirements served multiple functions. Practically, they may have enhanced the practitioner's psychological and physiological state for sustained ritual activity. Socially, they marked the practitioner as a serious, disciplined person rather than a casual dabbler. Theologically, they positioned the magical operation within the framework of Christian devotional practice, making it difficult to condemn straightforwardly as impious: a practitioner who fasted, confessed, and attended Mass before conjuring could claim to be acting within orthodox religious discipline even while performing operations that the same Church condemned. Frank Klaassen's analysis of how Solomonic magic framed itself within Christian devotional categories is the most thorough account of this dynamic.</p>""",

"secret_names": """<h2>Definition</h2>
<p>Actor Term. Secret names, in the context of medieval and Renaissance magic, designates the hidden or powerful names of God, angels, and demons that, when known and correctly pronounced or written, confer authority over the corresponding being or unlock specific magical powers. The concept is common to Jewish Kabbalah (the hidden names of God, the Tetragrammaton, the seventy-two names derived from Exodus 14), the Greek magical papyri (sequences of divine names including IAO, SABAOTH, ADONAI), and the Latin Solomonic tradition (the divine names inscribed on pentacles and spoken in conjuration formulas).</p>

<h2>Theoretical Basis</h2>
<p>The power of divine names in the magical tradition rests on several converging doctrines. In the Kabbalistic framework, the Hebrew letters of the Torah — especially the divine names — are not arbitrary signs but the actual creative words through which God made the world; knowing and manipulating them gives the adept access to creative power. In the Platonic tradition, names are not merely conventional but connected to the natures of things; the divine name participates in the divine nature it designates. In the Hermetic tradition, names are the handles by which the pneumatic world is manipulated; the magician who knows the true name of a spirit has power over it because names and natures are identical at the level of the world-soul.</p>
<p>The Solomonic grimoires exploit this doctrine systematically: each conjuration formula invokes a sequence of divine names (Hebrew, Greek, Latin, and invented) as compelling forces, and each spirit seal incorporates the spirit's name in a form that both identifies and binds it. The Enochian system received by Dee and Kelley represents the tradition's most elaborate development: an entire constructed language in which every word carries sacred power because the language itself is the original Adamic tongue in which God created. Agrippa's <em>De occulta philosophia</em> III, chapters on the sacred names, provides the most systematic Renaissance account.</p>""",

"secret_of_secrets": """<h2>Definition</h2>
<p>Analyst Term. The "Secret of Secrets" tradition designates the influential pseudo-Aristotelian text (<em>Secretum secretorum</em>) and its derivative literature, comprising one of the most widely circulated genres of medieval learned writing at the intersection of natural philosophy, medicine, physiognomy, astrology, and practical wisdom. The original Arabic text (<em>Sirr al-asrar</em> or <em>Kitab sirr al-asrar</em>), probably composed in the ninth or tenth century, was translated into Latin in two recensions: a partial translation by John of Seville (c.1120) and a longer version by Philip of Tripoli (c.1220–1250). Over two hundred Latin manuscripts survive.</p>

<h2>Contents and Magical Dimension</h2>
<p>The text's framing as a letter from Aristotle to Alexander the Great gave its contents the authority of the most eminent philosopher addressing the most powerful ruler. Its advice ranged across: governance and statecraft; health maintenance through diet, exercise, and seasonal regimen; physiognomy (reading character from physical features); astrology (timing activities by planetary configurations); and the occult properties of stones, plants, and animals. The natural magic dimension — recipes using specific materials with specific properties, instructions for astrological timing of medical and practical operations — sits uneasily alongside the practical governance advice, suggesting that the text was assembled from multiple sources.</p>
<p>Roger Bacon's engagement with the <em>Secretum secretorum</em> — he edited it and wrote a commentary treating it as genuine Aristotle — illustrates how the text operated in the thirteenth-century natural philosophical context: it provided authoritative support for the naturalistic treatment of apparently magical phenomena (occult properties of things, astrological timing) within the Aristotelian framework that dominated university natural philosophy. Don Skemer's work on material amulets and Sophie Page's on magical manuscripts both document the <em>Secretum secretorum</em>'s circulation alongside explicitly magical content.</p>""",

"ritual_diagrams": """<h2>Definition</h2>
<p>Actor Term. Ritual diagrams designate the visual-spatial components of learned magical practice: magic circles, geometric figures, planetary squares, spirit seals, and the elaborate composite images (the <em>notae</em> of the Ars Notoria, the pentacles of the Clavicula Salomonis) that constitute the visual dimension of the Solomonic and astrological magic traditions. Unlike the verbal components of magic (adjurations, divine names, prayers), ritual diagrams are spatial and graphical, existing on the boundary between text and image, between the language-like and the purely visual.</p>

<h2>The Magic Circle</h2>
<p>The magic circle — a drawn or marked circular space within which the practitioner stands during conjuration, inscribed with divine names, protective formulas, and/or spirit seals — is the most consistently required ritual diagram in the European learned magical tradition. It appears in the Munich Manual, the Clavicula Salomonis, the Heptameron, and virtually all practical demonic conjuration texts. The circle defines a protected space separated from the surrounding environment by its inscribed divine names; outside the circle, the conjured spirit must remain; within it, the practitioner is protected. The construction of the circle is typically elaborate and carefully prescribed.</p>
<p>The visual complexity of ritual diagrams varies enormously. The <em>notae</em> of the Ars Notoria are extremely intricate composite figures — surviving illustrated manuscripts show remarkable geometric complexity, with letter-forms, geometric patterns, and symbolic imagery combined in ways that require considerable draughtsmanship to reproduce. The pentacles of the Clavicula Salomonis are somewhat simpler but still require careful construction. Julien Véronèse's critical edition of the Ars Notoria (2007) includes analysis of the visual tradition; Sophie Page's work on magical manuscripts in institutional collections addresses the codicological significance of illustrated magical texts.</p>""",

"spiritual_magic_walker": """<h2>Definition</h2>
<p>Analyst Term. "Spiritual magic" is D.P. Walker's term, coined in <em>Spiritual and Demonic Magic from Ficino to Campanella</em> (Warburg Institute, 1958), for the type of Renaissance magical operation that works through the <em>spiritus</em> — the subtle pneumatic medium that Neoplatonic and medical philosophy posited as the link between the material body and the immaterial soul, and between the human organism and the world-soul of the cosmos. Spiritual magic is Walker's analytical category for operations that their practitioners claimed worked through purely natural causes (exploiting the spiritus's responsiveness to celestial influence) rather than through demonic cooperation.</p>

<h2>Walker's Framework</h2>
<p>Walker introduced the term to capture the specific philosophical territory occupied by Ficino's <em>De vita coelitus comparanda</em> and its successors: operations that used material means (foods, fumigations, music, talismans) to adjust the practitioner's pneumatic constitution by attracting or repelling specific planetary influences through the medium of the spiritus mundi. The key claim of spiritual magic is naturalistic: the spiritus is part of the natural world, subject to the same sympathies and influences as all other natural things, and operations that work through it are therefore natural philosophy rather than demonology.</p>
<p>Walker's analysis shows, however, that this naturalistic claim was philosophically unstable. The Neoplatonic framework that explained how spiritual magic worked — the doctrine of world-soul, daemonic intermediaries, and sympathetic resonance derived from Plotinus, Iamblichus, and Proclus — was not entirely innocent of the personal, addressative spirit-working that Christian theology condemned as demonic magic. Ficino's insistence that his operations were purely natural (like medicine or music, not like necromancy) was a necessary claim for his own protection, but it could not be fully sustained within the Neoplatonic framework he actually used. Walker's concept thus identifies the central philosophical problem of Renaissance learned magic: the tension between the need for a naturalistic account and the dependence on a theoretical framework that could not be fully naturalized.</p>""",

"picatrix_tradition": """<h2>Definition</h2>
<p>Analyst Term. The "Picatrix tradition" designates the influence of the <em>Picatrix</em> (Arabic <em>Ghāyat al-ḥakīm</em>, Goal of the Wise; Latin translation c.1300) on the subsequent history of astrological image magic in medieval and Renaissance Europe. The <em>Picatrix</em> was the most comprehensive and theoretically sophisticated astrological magic text available in Latin, and its influence on the learned magical tradition — through direct citation, through its provision of the theory of talismanic efficacy, and through its catalogues of materials and procedures — was pervasive from the fourteenth century onward.</p>

<h2>Direct Influence</h2>
<p>The most direct instances of <em>Picatrix</em> influence include: Marsilio Ficino's use of its astral medicine material in <em>De vita coelitus comparanda</em> (1489), where several specific procedures for attracting planetary spiritus are adapted from the <em>Picatrix</em>; Cornelius Agrippa's incorporation of its planetary correspondence tables and talisman procedures in <em>De occulta philosophia</em> II (1531); and the various astrological magic compilations of the fourteenth and fifteenth centuries that drew on its procedures for specific operations. The <em>Picatrix</em>'s organization around the twenty-eight lunar mansions — a finer-grained system than planetary magic alone — spread through subsequent talisman literature.</p>
<p>Nicolas Weill-Parot's analysis of addressative magic situates the <em>Picatrix</em> tradition at the centre of the scholastic controversy over image magic: the <em>Picatrix</em>'s procedures explicitly address planetary spirits as personal agents, invoking them by name and requesting their cooperation — precisely the "addressative" character that distinguished illicit demonic magic from licit natural talisman operation in the scholastic taxonomy. David Pingree's critical edition (1986) and the Attrell-Porreca English translation (2019) are the scholarly foundations for studying the <em>Picatrix</em> tradition.</p>""",

"notae": """<h2>Definition</h2>
<p>Actor Term (Latin plural, singular: <em>nota</em>). In the context of the Ars Notoria tradition, <em>notae</em> (notes or marks) designates the elaborate geometric and symbolic figures that serve as the visual components of the Notory Art's system of knowledge-acquisition. Each <em>nota</em> is a complex composite image — combining geometric shapes, letter-forms, and symbolic elements — that the practitioner contemplates while reciting the associated prayers (<em>orationes</em>) and that is believed, through divine grace and angelic mediation, to facilitate the infusion of specific knowledge (a particular liberal art, a language, a virtue).</p>

<h2>Form and Function</h2>
<p>The <em>notae</em> of the Ars Notoria vary considerably across manuscript traditions: the illustrated manuscripts show figures of remarkable complexity and visual interest, while many copies of the text were made without the figures (or with simplified schematic versions), suggesting that the practice could be adapted to different material conditions. The figures associated with the seven liberal arts are the most consistently represented; additional <em>notae</em> address practical knowledge, languages, theological understanding, and spiritual states.</p>
<p>The theoretical role of the <em>notae</em> is explained in various ways across the tradition. Some texts suggest they function as focal points for contemplation — looking at the figure while reciting the prayer concentrates the practitioner's attention. Others imply a more direct efficacy: the figure itself channels angelic or divine power. Thomas Aquinas's condemnation of the Ars Notoria (<em>Summa theologiae</em> II-II, q. 96, a. 1) turned partly on the <em>notae</em> and the Greek voces magicae in the prayers: because they bear no natural relationship to the knowledge they are supposed to produce, their claimed efficacy presupposes demonic rather than natural or divine causation. Julien Véronèse's critical edition of the Ars Notoria (2007) provides the most thorough analysis of the <em>notae</em> tradition; Claire Fanger's work on John of Morigny shows how one practitioner responded to and revised the figure-system under visionary guidance.</p>""",

"pyromancy": """<h2>Definition</h2>
<p>Actor Term. Pyromancy (from Greek <em>pyros</em>, fire, and <em>manteia</em>, divination) is divination through fire or flame — reading omens in the movement, colour, and behaviour of flames, or casting objects into fire and interpreting the results. It is one of the classical four elemental divination types (alongside geomancy from earth, hydromancy from water, and aeromancy from air) that appear in standard medieval taxonomies of the forbidden arts, including Isidore of Seville's <em>Etymologiae</em> and Johannes Hartlieb's <em>Buch aller verbotenen Kunst</em>.</p>

<h2>Historical Context</h2>
<p>Pyromancy was consistently condemned in the canonical medieval taxonomy of the prohibited arts, though it is the rarest of the four elemental divinations in surviving practical magical texts. Fire-based divination in ancient practice ranged from reading the behaviour of sacrificial fires (a form of haruspicy) through casting laurel branches, beans, or other substances into flames and observing the results. In medieval contexts, pyromantic procedures appear occasionally in magical miscellanies — readings of candle-flames, interpretation of burning substances in ritual contexts — alongside other divinatory techniques.</p>
<p>Unlike geomancy, which developed a systematic and widely taught divinatory method in the medieval Islamic and Latin worlds, pyromancy does not appear to have generated an equivalent technical literature. Its appearance in the canonical lists of forbidden arts reflects its ancient reputation as a divinatory practice rather than its medieval vitality as a learned system. Johannes Hartlieb's brief treatment in the <em>Buch aller verbotenen Kunst</em> (c.1456) is typical: he mentions pyromancy as one of the seven forbidden arts without providing any practical details, suggesting he is following the traditional taxonomy rather than describing a living practice he has personally encountered.</p>""",

"hydromancy": """<h2>Definition</h2>
<p>Actor Term. Hydromancy (from Greek <em>hydor</em>, water, and <em>manteia</em>, divination) is divination through water — reading visions or omens in a bowl, basin, pool, or other water surface. It is one of the four classical elemental divinations alongside geomancy, pyromancy, and aeromancy, appearing in standard medieval taxonomies of the prohibited arts. Historical forms of hydromantic practice ranged from catoptromancy (reading reflections in a polished surface) through scrying in water basins to divination by the behaviour of objects cast into water.</p>

<h2>Medieval Examples</h2>
<p>John of Salisbury's <em>Policraticus</em> (c.1159) provides a remarkable first-person account (I.11) of what appears to be a hydromantic or catoptromantic procedure: as a boy, John was used by a priest who attempted to see visions in a polished nail or water basin, seeking the appearance of demons or divine figures. John found the experience unproductive and disturbing, and his account provides unusually direct testimony from someone who participated in such a procedure. The Munich Manual contains procedures for divination through water and polished surfaces alongside its more explicit demonic conjuration material.</p>
<p>Scrying in crystals, polished stones, or water basins was closely related to hydromancy and was the basis of John Dee's angel communications: Edward Kelley gazed into a crystal "shewstone" to receive the Enochian messages. The practice of crystal-gazing (crystallomancy) was a direct descendant of the hydromantic tradition, and the crystal ball of modern popular imagination derives ultimately from this medieval and early modern practice of reflective surface scrying.</p>""",

"magic_and_cognition": """<h2>Definition</h2>
<p>Analyst Term. "Magic and cognition" designates the intersection between medieval theories of perception, imagination, and psychological influence and the explanation of magical causation. Medieval accounts of how magic works — particularly how a practitioner's intense mental concentration, the evil eye, or a charming voice could produce real effects on other persons — drew extensively on the medical and philosophical theories of imagination and passion current in Aristotelian and Arabic cognitive psychology.</p>

<h2>The Imagination in Magic Theory</h2>
<p>Medieval cognitive psychology, drawing on Avicenna's account of the faculty of imagination (<em>wahm</em>), held that the imagination could produce real physical effects: an intensely imagined sensation could cause bodily changes, a mother's fear could mark her unborn child, a melancholic person's imagination could project its visions outward as apparitions visible to others. The "power of imagination" (<em>virtus imaginativa</em>) was thus a recognized causal agency that could explain many apparently magical effects without appeal to demonic intervention.</p>
<p>Roger Bacon's treatment of the multiplication of species included the imagination as one source of efficacious rays: the magician who had trained his imagination could project species that affected distant objects, thereby producing effects that looked magical but were grounded in the natural psychology of perception. Nicole Oresme's <em>De causis mirabilium</em> (c.1360) used the power of imagination as a naturalistic explanation for apparent wonders — apparitions, visions, and other seemingly supernatural experiences could all be generated by the imagination acting on the body and projecting outward. Ioan Couliano's <em>Eros and Magic in the Renaissance</em> (1987) took this tradition as the basis for a theory of Renaissance magic as fundamentally a technology of psychological influence.</p>""",

"confession": """<h2>Definition</h2>
<p>Actor Term in a specific magical context. In the ritual magic tradition, "confession" (Latin: <em>confessio</em>) refers to the requirement — standard in most Solomonic grimoires — that the practitioner confess his sins to a priest and receive absolution before undertaking a major magical operation. This requirement is part of the broader ritual purity regime that Solomonic magic imposes on its practitioner: fasting, prayer, abstention from sexual activity, clean vestments, and sacramental confession are all prerequisites for the major conjurations of the <em>Clavicula Salomonis</em>, the <em>Sworn Book of Honorius</em>, and similar texts.</p>

<h2>Theological Significance</h2>
<p>The confession requirement is theologically anomalous: it incorporates a core sacramental practice of the Church into a magical procedure that the same Church condemned. This incorporation serves multiple functions. Practically, it aligns the magical operation with orthodox religious practice, making it harder to condemn as straightforwardly impious: a practitioner who has confessed and received absolution has satisfied the Church's standard requirements for receiving the sacraments. Theologically, it positions the conjuration within the framework of Christian devotion — the practitioner approaches the spirits as a purified Christian, not as a pagan or a demon-worshipper.</p>
<p>Frank Klaassen's analysis of how Solomonic magic aligned itself with Christian devotional categories — confession, prayer, fasting, Mass attendance — is the most thorough account of this strategy. The strategy was not merely cosmetic: practitioners seem to have genuinely understood their operations as extensions of legitimate Christian practice, operating within the divine order rather than against it. The spirits they conjured were bound by divine authority (invoked in the conjuration formulas), the procedures were conducted under divine oversight (the preparatory prayers), and the purposes were at least nominally legitimate (protecting the practitioner, acquiring knowledge, serving a patron). Whether the Church would have agreed is a different question.</p>""",

}


PERSON_ENRICHMENTS = {

"raziel": """<h2>The Angelic Figure</h2>
<p>Raziel (Hebrew: רזיאל, "Secret/Mysteries of God") is an angel in Jewish mystical and magical tradition, known primarily as the celestial scribe who compiled and transmitted the <em>Sepher Raziel ha-Malakh</em> (Book of Raziel the Angel) — a compendium of magical and cosmological knowledge — to Adam after the Fall, and who served as the intermediary between divine wisdom and human magical knowledge. Raziel appears in post-biblical Jewish literature; his name does not occur in the Hebrew Bible.</p>

<h2>Textual Traditions</h2>
<p>In the Midrashic tradition, Raziel stands at the veil separating the heavenly court from the divine presence and overhears all divine decrees, making him a natural intermediary of celestial secrets. The <em>Sepher Raziel ha-Malakh</em> — a Hebrew magical compendium probably assembled in the Geonic period (sixth to tenth centuries) but presented as Raziel's transmission to Adam — draws on this identification to claim the oldest possible authority for its contents: knowledge revealed before the Fall, preserved through the patriarchs, and eventually reaching Solomon. The text incorporates material related to the <em>Sepher ha-Razim</em> alongside kabbalistic material, amulet formulas, and angel names.</p>
<p>In Latin European magic, Raziel appears primarily through the <em>Liber Razielis</em> — a thirteenth-century Latin compilation drawing on Hebrew sources — which attributes its contents to Raziel's original revelation to Adam. The figure of Raziel thus serves the same pseudepigraphic function in the angelic knowledge tradition as Solomon serves in the demonic conjuration tradition: an ancient, divinely-authorized source whose name legitimates later compiled content. David Pingree's work on the <em>Liber Razielis</em> and Gideon Bohak's on the Hebrew <em>Sepher Raziel</em> tradition provide the scholarly foundations.</p>""",

"apollonius_of_tyana": """<h2>The Figure</h2>
<p>Apollonius of Tyana (c.15–100 CE) was a first-century CE Neopythagorean philosopher from Cappadocia who, in the hagiographic biography written by Philostratus (c.220–230 CE), was presented as a wandering sage and wonder-worker whose miracles — healing the sick, raising the dead, appearing simultaneously in different places — rivalled those of Jesus Christ. The Life of Apollonius made him an important figure in late antique pagan responses to Christianity and established him as a type of the philosopher-magus whose wisdom gave him power over nature.</p>

<h2>Magical Attribution</h2>
<p>In the medieval and Renaissance magical tradition, Apollonius of Tyana was one of the figures to whom magical texts and procedures were attributed as a legitimating pseudepigraphic strategy. The <em>Kitab al-istimaas</em> (Book of the Consultation of the Spirits), known in Latin as the <em>Liber Lunae</em> or related texts, and various other Arabic magical compilations circulated under his authority. The Arabic tradition knew Apollonius as Balinus and attributed to him the discovery of the Emerald Tablet of Hermes — perhaps the most important single document of alchemical tradition — in a vault beneath a statue. This attribution of the Emerald Tablet to Apollonius-Balinus, transmitted through Arabic into Latin, connected him to the Hermetic-alchemical tradition alongside his association with the broader magical tradition.</p>
<p>For historians of magic, Apollonius is significant primarily as a vector of pseudepigraphic attribution: texts circulated under his name exploit the authority of a figure known for wonder-working and ancient wisdom. The historical Apollonius himself remains poorly documented; Philostratus's biography is hagiography rather than history, and modern scholarship (G.R.S. Mead, Maria Dzielska) has found it impossible to determine what is historical in the Philostratan portrait.</p>""",

"agostino_paravicini_bagliani": """<h2>Life and Scholarship</h2>
<p>Agostino Paravicini Bagliani is a Swiss-Italian medievalist and emeritus professor at the University of Lausanne whose work on the medieval papacy, papal court culture, and the relationship between medicine, natural philosophy, and ecclesiastical authority has contributed important context for understanding how learned magic operated at the highest levels of medieval institutional life. His research on the papal court's engagement with natural philosophy, alchemy, and the prolongation of life is particularly relevant to the history of magic at the intersection of medicine, natural philosophy, and theology.</p>

<h2>The Pope's Body</h2>
<p>Paravicini Bagliani's most widely read work in English translation is <em>The Pope's Body</em> (<em>Il corpo del Papa</em>, 1994; English translation University of Chicago Press, 2000), which examines how the medieval papacy constructed the physical person of the pope as a sacred body — simultaneously ordinary (the pope could die, be ill, become old) and extraordinary (his office conferred unique spiritual authority). The book's treatment of the papal court's engagement with medical practitioners, alchemists, and natural philosophers seeking to prolong the pope's life provides context for understanding how the highest levels of medieval institutional Christianity were implicated in the same natural philosophical and proto-magical projects that the Church officially condemned in other contexts.</p>
<p>His broader work on Roger Bacon's relationship to the papal court, on the <em>Speculum astronomiae</em> and its attribution, and on the culture of thirteenth-century natural philosophy at the Roman curia contributes to the history of magic by documenting how natural philosophy — including astrological and alchemical projects with magical dimensions — was pursued at and for the papacy even as the same papacy condemned learned magic in its judicial capacity. This irony — the institutional Church both sponsoring and condemning the same kinds of natural philosophical enquiry — is central to the social history of medieval magic.</p>""",

"beatice_delaurenti": """<h2>Life and Scholarship</h2>
<p>Béatrice Delaurenti is a French historian of medieval philosophy and medicine at the École des hautes études en sciences sociales (EHESS) in Paris whose research focuses on the relationship between fascination, enchantment, and natural philosophy in medieval scholastic thought. Her work examines how medieval philosophers and physicians theorized the power of the gaze, voice, and imagination to produce real physical effects on other persons — the natural philosophical account of what popular tradition called "the evil eye" or fascination.</p>

<h2>La puissance des mots</h2>
<p>Delaurenti's major work, <em>La puissance des mots: «Virtus verborum»: débats doctrinaux sur le pouvoir des incantations au Moyen Âge</em> (Éditions du Cerf, 2007), examines the medieval scholastic debate about the power of incantations — whether words could produce physical effects and, if so, by what mechanism. The book traces the debate from the twelfth century through the late medieval period, analysing how philosophers and theologians argued about whether the efficacy of spoken words in healing or harming required natural, angelic, or demonic causation.</p>
<p>This debate was directly relevant to the status of charms, adjurations, and conjuration formulas in the magical tradition: if words had no natural causal power (a position held by some scholastics), then their use in magical operations necessarily presupposed supernatural — and therefore demonic — assistance. If words had genuine natural power through their association with the speaker's intention and the qualities of sound, then at least some verbal magic could be defended as natural philosophy. Delaurenti's careful reconstruction of this debate provides essential philosophical context for understanding why the condemnation of verbal magic was not as straightforward as it might appear.</p>""",

"bernard_silvester": """<h2>Life</h2>
<p>Bernardus Silvestris (Bernard Silvester, fl. c.1150) was a French scholar associated with the intellectual circle of Tours in the mid-twelfth century, most likely a master in the cathedral school there. He is best known for his <em>Cosmographia</em> (also called <em>De mundi universitate</em>, c.1147–1148), an elaborate allegorical cosmological work in mixed prose and verse (a <em>prosimetrum</em>) that narrates the creation and ordering of the universe through personified cosmic powers. His work is important for the history of magic because it transmits a specifically magical dimension of the twelfth-century Neoplatonic cosmology that influenced the subsequent learned magical tradition.</p>

<h2>The Cosmographia and Natural Magic</h2>
<p>The <em>Cosmographia</em> presents a Neoplatonic cosmology derived from Plato's <em>Timaeus</em>, Macrobius, Martianus Capella, and the Latin Asclepius, in which the universe is created and ordered by cosmic powers — Nous (Mind), Natura (Nature), and Physis (the lower world) — and in which the elemental world is permeated by a world-soul (Endelechia) that connects all things through sympathetic bonds. This framework — a living, intelligent cosmos pervaded by sympathetic connections — is precisely the theoretical basis for natural magic: if all things are connected through the world-soul's sympathies and antipathies, then operations that exploit these connections are natural philosophy rather than demonic practice.</p>
<p>The <em>Cosmographia</em>'s presentation of astrology (the influence of the fixed stars and planets on terrestrial generation) and its treatment of the hidden properties of things as expressions of the world-soul's creative activity provided twelfth-century readers with a Neoplatonic framework for natural magic before the main wave of Arabic natural philosophical translation had reached northern France. Winthrop Wetherbee's work on the twelfth-century Platonists and the relevant sections of Brian Stock's <em>Myth and Science in the Twelfth Century</em> (1972) provide the intellectual context for Bernardus's place in the history of learned magic theory.</p>""",

"catherine_rider": """<h2>Life and Scholarship</h2>
<p>Catherine Rider is an Associate Professor in the Department of History at the University of Exeter and one of the leading historians of medieval magic with a focus on the relationship between magic, medicine, and gender in medieval England and Europe. Her research examines how magic was discussed and regulated in pastoral and scholastic contexts and how magical texts and practices intersected with medical knowledge and practice.</p>

<h2>Magic and Impotence</h2>
<p>Rider's major monograph, <em>Magic and Impotence in the Middle Ages</em> (Oxford University Press, 2006), examines a specific body of medieval magical literature — texts dealing with magically caused impotence and the remedies for it — as a window into how medieval people thought about the relationship between magic, medicine, sexuality, and religious authority. The study demonstrates how texts that combined medical and magical approaches to a practical problem circulated in manuscript collections across the medieval period, and how the institutional Church — in canon law, in pastoral literature, and in theological discussion — responded to the claim that magic could render men unable to perform sexually.</p>
<p>Beyond its specific subject, the book is important as a methodological model: by focusing on a specific, well-documented type of magical practice and tracing it across multiple textual and institutional contexts, Rider shows how the history of magic can be practised with the same archival rigour as other branches of medieval social history. Her subsequent work, including her contributions to Sophie Page and Catherine Rider (eds.), <em>The Routledge History of Medieval Magic</em> (2019), has extended this approach across a wider range of topics in medieval magic history.</p>""",

"florence_chave_mahir": """<h2>Life and Scholarship</h2>
<p>Florence Chave-Mahir is a French medievalist whose research focuses on exorcism, demonic possession, and the relationship between pastoral practice and the demonic in the medieval Church. Her work provides essential context for understanding how the Church's institutional responses to demonic activity — through exorcism and related ritual practices — intersected with the learned magical tradition that also claimed to control demons.</p>

<h2>L'exorcisme des possédés</h2>
<p>Chave-Mahir's major work, <em>L'exorcisme des possédés dans l'Église d'Occident (Xe–XIVe siècle)</em> (Brepols, 2011), provides the most comprehensive account of medieval exorcism practice from the tenth through the fourteenth centuries, examining both the liturgical and canonical framework of exorcism as an official Church rite and the actual practice of exorcism as documented in hagiographical and pastoral sources. The work illuminates the relationship between official exorcism and the unofficial, learned magical procedures for commanding demons that the same Church condemned: both claim authority over demonic beings through divine power, and the boundary between a legitimate exorcism and an illicit conjuration was contested and context-dependent.</p>
<p>For the history of magic, Chave-Mahir's work is significant for demonstrating that the Church's relationship to demonic power was not simply one of condemnation and suppression. The institutional practice of exorcism constituted an acknowledged, officially sanctioned form of commanding demons — not through magical art but through divine authority delegated through the Church's priesthood. Understanding this institutional framework helps explain why practitioners of learned demonic magic could frame their operations within a broadly Christian devotional structure and claim to work within divine authority rather than against it.</p>""",

"lea_olsan": """<h2>Life and Scholarship</h2>
<p>Lea T. Olsan is a scholar of medieval literature and magic, best known for her foundational research on medical charms in Middle English manuscripts. Her work examines the verbal and material culture of healing magic in medieval England, focusing on the charm tradition as it appears in manuscript collections that combined medical, devotional, and magical material. She has taught at the University of Louisiana Monroe.</p>

<h2>Charms and Medical Manuscripts</h2>
<p>Olsan's research on Middle English medical charms — her articles in <em>Magic, Ritual, and Witchcraft</em>, <em>Traditio</em>, and related journals — has been foundational for establishing medical charms as a legitimate subject of scholarly analysis rather than dismissing them as mere superstition or residual paganism. Her work examines how charms functioned within the practical medical culture of medieval England: how they were copied, how they were organized in manuscript collections (typically alongside recipes, herbal lore, and surgical instructions), and how their users understood their efficacy.</p>
<p>A key contribution is her analysis of the relationship between the verbal form of charms and their claimed efficacy: Olsan shows that medieval charm-users had sophisticated understandings of how different types of verbal formula (prayer, adjuration, narrative charm, protective verse) worked through different mechanisms — prayer through divine petition, adjuration through divine authority, narrative charm through analogy and precedent — and that the choice of verbal form was not random but reflected practitioners' views about the nature of magical causation. Her work connects the popular charm tradition to the theoretical debates of scholastic natural philosophy and pastoral theology that addressed the same questions about the power of words and the mechanism of magical causation.</p>""",

"jean_patrice_boudet": """<h2>Life and Scholarship</h2>
<p>Jean-Patrice Boudet is a French historian of medieval science and magic at the Université d'Orléans whose research focuses on astrology, divination, and learned magic at the French royal court and in the broader context of late medieval French intellectual culture. His work documents how astrological and divinatory practices were integrated into the culture of the Valois court and how the relationship between learned magic and royal patronage shaped the production and circulation of magical texts in fourteenth and fifteenth-century France.</p>

<h2>Entre science et nigromance</h2>
<p>Boudet's major work, <em>Entre science et nigromance: Astrologie, divination et magie dans l'Occident médiéval (XIIe–XVe siècle)</em> (Publications de la Sorbonne, 2006), provides the most comprehensive account of the relationship between astrological science and nigromanric practice in medieval Western Europe from the twelfth through the fifteenth centuries. The book traces the gradual development of a learned culture of astrological and divinatory practice — initially dependent on Arabic translation, then increasingly elaborated in Latin and vernacular contexts — and examines how this culture intersected with court patronage, university education, and ecclesiastical regulation.</p>
<p>Boudet's research on the court of Charles V of France — a monarch who patronized astrologers, owned magical texts, and commissioned translations of astrological works — demonstrates how royal courts provided spaces in which learned magic could be practised under aristocratic protection. His analysis of the relationship between Nicole Oresme's critique of astrology and the court culture that simultaneously employed and critiqued astrological practitioners illuminates the contradictory position of learned magic within late medieval intellectual life. His work on the <em>Picatrix</em> and other astrological magic texts at the French court complements the English-focused scholarship of Klaassen and Page.</p>""",

"robert_mathiesen": """<h2>Life and Scholarship</h2>
<p>Robert Mathiesen is a scholar of Slavic languages and literatures and the history of magic, best known for his collaboration with Theitic (Mark Stavish) and his work on the Solomonic magic tradition in Eastern European contexts, particularly his research into the manuscript tradition of Solomonic and related magical texts in Slavic and Cyrillic manuscripts. His academic career was at Brown University, where he worked in the Slavic Studies department.</p>

<h2>Contributions to Magic History</h2>
<p>Mathiesen's contributions to grimoire scholarship include his documentation of Solomonic magical texts in Eastern European manuscript collections — a tradition less well studied than the Western Latin manuscripts but connected to the same Solomonic framework through Byzantine Greek intermediaries. The Byzantine Greek <em>Hygromanteia</em> and related Solomonic texts were transmitted into Slavic manuscript culture, providing a southeastern European branch of the Solomonic tradition that complements the Latin Western tradition documented by Kieckhefer, Klaassen, and Page.</p>
<p>His work on the relationship between Greek, Slavic, and Latin Solomonic traditions contributes to the broader picture of Solomonic magic as a truly pan-European phenomenon with parallel transmission histories across multiple linguistic and cultural zones. His collaborative work with Dan Harms and Joseph Peterson on specific grimoire texts situates this Eastern European dimension within the wider comparative grimoire scholarship that has developed since the 1990s.</p>""",

}


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    updated = 0
    for slug, html in CONCEPT_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM concepts WHERE slug=?", (slug,)).fetchone()
        if row:
            conn.execute("UPDATE concepts SET definition_long=? WHERE slug=?", (html, slug))
            print(f"  concept: {slug} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING concept: {slug}")

    for pid, html in PERSON_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM persons WHERE person_id=?", (pid,)).fetchone()
        if row:
            conn.execute("UPDATE persons SET bio_html=? WHERE person_id=?", (html, pid))
            print(f"  person: {pid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING person: {pid}")

    conn.commit()
    print(f"\nUpdated {updated} entries.")
    conn.close()


if __name__ == "__main__":
    main()
