"""
Enrich priority database entries with full bio_html, analysis_html, and definition_long.

Priority batch 1: the 9 entries flagged in the research agenda.
Run after all seed scripts.
"""
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import DB_PATH


# ---------------------------------------------------------------------------
# CONCEPTS – definition_long
# ---------------------------------------------------------------------------

CONCEPT_ENRICHMENTS = {

"yates_thesis": """<h2>Overview</h2>
<p>The "Yates thesis" is the interpretive framework advanced by Dame Frances Amelia Yates (1899–1981) in her trilogy <em>Giordano Bruno and the Hermetic Tradition</em> (1964), <em>The Art of Memory</em> (1966), and <em>The Rosicrucian Enlightenment</em> (1972). In its strongest form, the thesis holds that Renaissance Hermeticism — the recovery and promotion of the <em>Corpus Hermeticum</em> in Marsilio Ficino's 1463 Latin translation — was a decisive, generative force in the emergence of early modern natural philosophy, and that figures such as Giordano Bruno operated within a coherent "Hermetic tradition" whose emphasis on man as magus and on the active manipulation of natural and celestial forces provided the psychological and conceptual preconditions for the Scientific Revolution.</p>

<h2>The Argument in Detail</h2>
<p>Yates's reading of the <em>Corpus Hermeticum</em> and its Renaissance reception depended heavily on the assumption, widespread since the Renaissance itself, that the Hermetic writings were genuinely ancient — that Hermes Trismegistus was a real Egyptian sage, contemporary with or even prior to Moses, whose wisdom preserved a primordial philosophical theology (<em>prisca theologia</em>). This assumption was demolished by Isaac Casaubon in 1614, who dated the texts to the first three centuries CE on philological grounds. Yates, writing in the 1960s, knew Casaubon's refutation but argued that the <em>belief</em> in the texts' antiquity — regardless of their actual date — was what mattered historically. For Renaissance thinkers, the <em>Hermetica</em> carried the authority of Egyptian antiquity, and this authority structured the way Ficino, Pico della Mirandola, Cornelius Agrippa, and Bruno read them.</p>
<p>The central move in the Yates thesis is the claim that Hermetic <em>magia</em> — the technology of drawing down celestial influences through talismans, suffumigations, music, and ritual — constituted a specifically <em>operative</em> philosophy: an attempt to change the world, not merely understand it. Yates argued that this operativity prefigured, and in some sense enabled, the experimental orientation of seventeenth-century natural philosophy. Where scholastic Aristotelianism had counselled contemplative knowledge of fixed natural essences, the Hermetic magus sought to intervene in nature's processes. The magician and the scientist shared, Yates suggested, a will to power over the natural world.</p>

<h2>Reception and Critique</h2>
<p>The thesis was enormously influential through the 1970s and provoked sustained scholarly revision from the 1980s onward. Brian Vickers's edited volume <em>Occult and Scientific Mentalities in the Renaissance</em> (1984) collected essays challenging the continuity Yates posited between magical and scientific thought, arguing that figures like Francis Bacon explicitly rejected Hermetic magic even while absorbing some Hermetic rhetoric. Robert Westman and J.E. McGuire, in <em>Hermeticism and the Scientific Revolution</em> (1977), questioned whether the specific claims Yates made about Bruno's influence on Copernicus could be sustained.</p>
<p>Nicholas Campion, Wouter Hanegraaff, and Kocku von Stuckrad have assessed the thesis's reception within the historiography of Western esotericism more broadly. D.P. Walker's <em>Spiritual and Demonic Magic from Ficino to Campanella</em> (1958) — published before Yates's <em>Bruno</em> book — had already mapped the territory of Renaissance learned magic with greater caution about grand causal claims, and Walker's more measured approach has aged better than Yates's ambitious synthesis.</p>
<p>The contemporary consensus, represented by scholars such as Liana De Girolami Cheney, Wouter Hanegraaff, and Anthony Grafton, treats the Yates thesis as a productive exaggeration: it opened up the study of Renaissance magic and esotericism as legitimate historical subjects, established the <em>Corpus Hermeticum</em>'s centrality to sixteenth-century intellectual life, and demonstrated that figures previously dismissed as cranks (Bruno, Agrippa, Dee) were engaged with serious philosophical problems — even if the direct causal link Yates drew between Hermeticism and the Scientific Revolution is no longer defended in its strong form.</p>

<h2>Significance for the Study of Grimoire Tradition</h2>
<p>For grimoire scholarship specifically, the Yates thesis matters because it established the learned magical tradition as a coherent intellectual phenomenon worthy of rigorous historical analysis, rather than as an embarrassing footnote to the history of ideas. Frank Klaassen's <em>The Transformations of Magic</em> (2013) and Claire Fanger's edited volumes build on this legitimation while correcting Yates's tendency to flatten the distinction between Renaissance learned magic and the practical ritual books (experiment literature) that circulated alongside philosophical Hermeticism.</p>""",

"renaissance_magic": """<h2>Definition</h2>
<p>Analyst Term. "Renaissance magic" designates the complex of natural-philosophical, astrological, Neoplatonic, and Hermetic theories and practices concerning the manipulation of occult forces that flourished in Italian, German, French, and English learned culture between approximately 1460 and 1620. The term is primarily an analyst category: historical actors spoke of <em>magia naturalis</em>, <em>philosophia occulta</em>, or simply <em>magia</em>, understanding these not as unified movements but as overlapping approaches to a shared problem — how to account for, and exploit, the hidden sympathies, antipathies, and influences that connected the celestial and terrestrial worlds.</p>

<h2>Major Currents</h2>
<p><strong>Ficinian Neoplatonism and <em>magia naturalis</em>.</strong> Marsilio Ficino's <em>De vita coelitus comparanda</em> (1489, Book III of the <em>De vita</em> trilogy) is the founding text of Renaissance learned magic. Building on Plotinus, Iamblichus, and Proclus, Ficino proposed that the spiritus mundi — a subtle pneumatic medium pervading the cosmos — could be attracted and concentrated by materials (stones, plants, metals, foods, images) that resonated with specific planetary influences. The philosopher-physician could draw down solar or Jovian spiritus through talismans, music, and diet, thereby healing a melancholic temperament over-saturated with Saturnine influence. Ficino carefully insisted that his magic operated through purely natural causes, avoiding explicit demonic invocation; whether this insulation was philosophically coherent or merely prudential has been debated by D.P. Walker, Brian Copenhaver, and Wouter Hanegraaff.</p>
<p><strong>Pico della Mirandola and Kabbalah.</strong> Giovanni Pico della Mirandola's <em>Conclusiones</em> (1486) and <em>Apologia</em> added Christian Kabbalah to the Neoplatonic-Hermetic synthesis. Pico argued that Kabbalah — the Jewish mystical tradition of divine names and letter permutations — could confirm Christian theological claims and provide a superior technology of spirit-working that explicitly recruited angelic rather than merely stellar powers. His fusion of Kabbalah, Neoplatonism, and Hermeticism defined what later scholars call "the Florentine synthesis" and shaped Cornelius Agrippa's encyclopedic <em>De occulta philosophia</em> (published 1531).</p>
<p><strong>Agrippa's synthesis and its reception.</strong> Cornelius Agrippa's <em>De occulta philosophia libri tres</em> collected and systematized the full range of Renaissance occult philosophy — natural magic (Book I), celestial or mathematical magic (Book II), and ceremonial or divine magic (Book III). The three-book structure corresponded to the three worlds of Renaissance Neoplatonism: the elemental, the celestial, and the intellectual. Agrippa's handbook became the most widely read compendium of learned magic in early modern Europe, shaping practitioners' self-understanding through to the eighteenth century.</p>
<p><strong>Giordano Bruno and the limits of the tradition.</strong> Bruno's Hermetic writings of the 1580s — the <em>Spaccio de la bestia trionfante</em>, <em>De magia</em>, and the Italian dialogues — represent the tradition in its most philosophically adventurous form, also its most dangerous: Bruno's panpsychic universe, in which all things are animated by a world-soul, dissolved the boundary between natural magic and a kind of immanent theology. His execution in 1600 marked the end of the era in which learned magic could be openly promoted as a philosophically respectable programme.</p>

<h2>Scholarly Frameworks</h2>
<p>The foundational scholarly account is D.P. Walker's <em>Spiritual and Demonic Magic from Ficino to Campanella</em> (1958), which established the tension between natural and demonic interpretations of the same magical operations as the central problem of the field. Yates's <em>Giordano Bruno and the Hermetic Tradition</em> (1964) placed the tradition within a grand narrative of the Scientific Revolution. Brian Copenhaver's work on Ficino and on the <em>Hermetica</em> (his 1992 translation remains standard) has provided the most careful textual analysis. Ioan Couliano's <em>Eros and Magic in the Renaissance</em> (1987) offered a semiotic interpretation. For the English tradition, Deborah Harkness's <em>John Dee's Conversations with Angels</em> (1999) and Glyn Parry's work on Dee in his court context provide the best coverage.</p>""",

"grimoire_printing_history": """<h2>Definition</h2>
<p>Analyst Term. "Grimoire printing history" designates the complex transitions by which the learned magical handbook tradition — previously existing primarily in expensive manuscript copies circulating among clerical, court, and university networks — was transformed by the hand press (from c.1450) and later offset and print-on-demand technologies into a widely available, commercially produced genre. The history is neither simply one of democratization nor of degradation, but of repeated negotiations between the social capital of rarity, the commercial logic of print, and the legal and theological risks of publication.</p>

<h2>Manuscripts Before Print</h2>
<p>Before Gutenberg, grimoires existed as expensive, laboriously produced codices whose cost of production limited circulation. The <em>Picatrix</em>, the <em>Clavicula Salomonis</em>, the Ars Notoria, and the Munich Manual all circulated in small numbers of manuscripts, often among university graduates, cathedral clergy, and court astrologers. Don Skemer's <em>Binding Words: Textual Amulets in the Middle Ages</em> (2006) and Claire Fanger's edited volumes document this manuscript culture. The relative rarity of copies did not make manuscripts safe from ecclesiastical attention — inquisitors seized and destroyed them — but scarcity provided a degree of practical protection.</p>

<h2>The First Wave of Printed Magic, 1486–1600</h2>
<p>The earliest printed magical texts appeared in contexts that minimized their transgressive content. Ficino's <em>De vita</em> (1489), including the controversial third book on astral magic, was published under Medici patronage in Florence. Agrippa's <em>De occulta philosophia</em> (1531) appeared openly in Cologne. Giovanni Battista della Porta's <em>Magia naturalis</em> first appeared in 1558 (four books) and was expanded to twenty books in 1589, becoming one of the best-selling books of the sixteenth century; della Porta consistently framed his magic as natural philosophy. The <em>Heptameron</em> of pseudo-Pietro d'Abano circulated as an appendix to Agrippa's fourth book.</p>
<p>The grimoires most resistant to print were those involving explicit demonic conjuration — the <em>Munich Manual</em>, the <em>Sworn Book of Honorius</em>, the <em>Clavicula Salomonis</em> — which circulated in manuscript long after other magical texts had been printed. The reason was legal and theological: explicit demonic pact had been criminalized by the Constitutio Criminalis Carolina (1532) in Germany and by various inquisitorial procedures elsewhere.</p>

<h2>Seventeenth and Eighteenth Centuries: The Chapbook Grimoire</h2>
<p>The decisive transformation came in the seventeenth and especially eighteenth century, when cheaper printing methods enabled the production of small, inexpensive pamphlet grimoires for a popular market. The <em>Grand Albert</em>, the <em>Petit Albert</em>, the <em>Grimorium Verum</em>, and the <em>Grand Grimoire</em> (also known as the Dragon Rouge) were printed, reprinted, and translated across France, Germany, and eventually England in editions designed for a market of literate craftsmen, village cunning folk, and urban fortune-tellers. Owen Davies's <em>Grimoires: A History of Magic Books</em> (2009) provides the most comprehensive account of this shift, tracing how magical texts moved from elite clerical culture to popular commercial publishing.</p>
<p>The <em>Sixth and Seventh Books of Moses</em>, first printed in Germany c.1849 but drawing on older manuscript material, represents the endpoint of this trajectory: a grimoire produced explicitly for a mass market, with no pretence of elite origins, that spread through German immigrant communities into the American South and Caribbean, influencing hoodoo practice.</p>

<h2>Nineteenth and Twentieth Century: Occult Revival Editions</h2>
<p>The Hermetic Order of the Golden Dawn's manuscript-sharing culture in the 1880s–1900s was print culture's partial inverse: a movement of ritual magicians who deliberately withheld texts from publication, grading access by initiation level. Samuel Liddell Mathers's edition of the <em>Key of Solomon</em> (1889) and his translation of the <em>Book of the Sacred Magic of Abramelin</em> (1898) bridged manuscript scholarship and occult practice, appearing as commercial editions through Kegan Paul while retaining the air of recovered secrets. A. E. Waite's parallel editorial production served a similar market.</p>
<p>Joseph Peterson's Esoteric Archives (online from 1997) and his print editions through Ibis Press represent the contemporary digital-first equivalent: the exhaustive scholarly edition produced for practitioners and historians simultaneously, using digital technology to circulate texts previously known only to manuscript specialists.</p>

<h2>Key Scholarly Resources</h2>
<p>Owen Davies, <em>Grimoires: A History of Magic Books</em> (Oxford, 2009) is the essential overview. Frank Klaassen's <em>The Transformations of Magic</em> (2013) covers the manuscript period. For chapbook grimoires in France, see Lawrence Principe and Lloyd DeWitt (eds.), <em>Chymists and Chymistry</em>. For print and magic more broadly, see the essays in Claire Fanger (ed.), <em>Invoking Angels</em> (2012) and the relevant sections of Richard Kieckhefer, <em>Magic in the Middle Ages</em> (1989).</p>""",

}


# ---------------------------------------------------------------------------
# PERSONS – bio_html
# ---------------------------------------------------------------------------

PERSON_ENRICHMENTS = {

"marsilio_ficino": """<h2>Life</h2>
<p>Marsilio Ficino (1433–1499) was born in Figline Valdarno, near Florence, the son of a physician who served the Medici. Cosimo de' Medici, recognizing the young scholar's promise, placed him under the tutelage of humanist teachers and eventually entrusted him with the translation of the newly acquired manuscripts of Plato and the Neoplatonists — a project that would occupy Ficino's entire career and reshape European intellectual life. Ficino spent most of his adult life at the Medici villa at Careggi, the nominal centre of what later scholars called the "Platonic Academy." He was ordained a priest in 1473, an event that introduced productive tensions between his philosophical commitments and his theological obligations that run through all his major works.</p>

<h2>The Translation Project</h2>
<p>Ficino's first major task, at Cosimo's urgent request, was to interrupt his Platonic translation project to render the newly arrived <em>Corpus Hermeticum</em> — fourteen Greek treatises attributed to Hermes Trismegistus — into Latin. This translation, completed in 1463 and circulated in manuscript before its 1471 printed edition, introduced the <em>Hermetica</em> to Latin Europe. Ficino accepted the traditional attribution: Hermes Trismegistus was, he believed, a real Egyptian sage of Mosaic antiquity, and the <em>Hermetica</em> preserved a primordial philosophical theology (<em>prisca theologia</em>) that anticipated Christian truth. This conviction structured his entire philosophical project: the recovery of ancient wisdom was also a preparation of pagan learning for Christian reception.</p>
<p>His translations of Plato's complete dialogues (1484), Plotinus's <em>Enneads</em> (1492), Iamblichus, Porphyry, Proclus, and Pseudo-Dionysius the Areopagite established Latin versions that remained standard for centuries. His commentaries — especially the <em>Commentarium in Convivium Platonis de amore</em> (1469, printed 1484) — transmitted Platonic philosophy in a form accessible to humanist readers across Europe.</p>

<h2>Magia and De vita</h2>
<p>The most controversial element of Ficino's intellectual production was the third book of his <em>De vita</em> trilogy, <em>De vita coelitus comparanda</em> (On Drawing Life from the Sky, 1489). Here Ficino outlined a system of therapeutic astral magic. The basis was Neoplatonic: the <em>spiritus mundi</em>, a subtle intermediary pervading the cosmos, linked the celestial bodies to all terrestrial things through bonds of sympathy and antipathy. A philosopher-physician — especially one of melancholic constitution (Saturn's children were the scholars and intellectuals) — could mitigate the excessive cold and dryness of Saturnine influence by attracting solar or Jovian <em>spiritus</em> through the use of appropriate materials: gold, amber, saffron, wine, images of the sun, solar music, exposure to sunlight and cheerful company.</p>
<p>D.P. Walker, in <em>Spiritual and Demonic Magic from Ficino to Campanella</em> (1958), was the first modern scholar to analyse this system in depth, arguing that it occupies an ambiguous position: Ficino consistently insisted that his magic operated through purely natural celestial causes, yet the Neoplatonic framework it drew on — especially from Iamblichus and Proclus — involved genuine spirit-working that could not easily be naturalised. Brian Copenhaver's subsequent work has been more sympathetic to Ficino's self-presentation as a natural philosopher, while acknowledging the philosophical instability of the position. The 1489 text caused Ficino genuine anxiety; he was investigated by the Florentine curia and appended a lengthy self-defence to subsequent editions.</p>

<h2>Influence and Reception</h2>
<p>Ficino's influence on the subsequent century of European thought was immense. Giovanni Pico della Mirandola absorbed and radicalised his synthesis, adding Christian Kabbalah. Lefèvre d'Étaples translated and promoted his work in France. Cornelius Agrippa's <em>De occulta philosophia</em> (1531) drew extensively on Ficino for its theory of the world-soul and elemental magic. John Colet in England and the German humanists engaged his Platonic commentaries. His influence on English Neoplatonism reached from the Cambridge Platonists of the seventeenth century to the Romantic poets.</p>
<p>For the history of magic specifically, the key secondary literature includes Brian Copenhaver's edition and translation of the <em>Hermetica</em> (1992) and his philosophical studies of Ficino's sources; D.P. Walker's foundational 1958 monograph; Michael Allen's work on Ficino's Platonic commentaries; and Stéphane Toussaint's studies of Ficino's natural magic and its reception.</p>""",

"john_dee": """<h2>Life and Career</h2>
<p>John Dee (1527–1608/09) was the most intellectually formidable of Elizabethan England's learned magicians, a mathematical practitioner, natural philosopher, court astrologer, and angelic communicant whose career intersects with virtually every current of sixteenth-century occult philosophy. Born in Tower Ward, London, of Welsh descent, Dee entered St John's College Cambridge in 1542 and became a founding fellow of Trinity College in 1546. His early reputation was built on mathematical science: his 1570 "Mathematical Preface" to Henry Billingsley's English translation of Euclid is a landmark in the promotion of mathematics as a practical art of navigation, engineering, and natural inquiry.</p>
<p>Dee's library at Mortlake, accumulated over decades, was one of the largest private libraries in Elizabethan England — he estimated it at over 4,000 volumes in a 1583 petition — and served as both a research centre and a node in the European republic of letters. He corresponded with Ortelius, with Gerard Mercator (who gave him his projection globes), and with Continental scholars of natural philosophy and mathematics. His continental visits (1547–1548, 1562–1563, 1583–1589) placed him within networks extending to the Habsburg court.</p>

<h2>Angel Magic and the Enochian System</h2>
<p>The angel conversations, conducted from 1582 to 1589 with the scryer Edward Kelley as the primary medium, represent the most extensively documented angelic communication project in European history. Dee's diaries of the sessions (now principally British Library MS Sloane 3188, 3677, and the volumes published posthumously by Meric Casaubon in 1659 as <em>A True and Faithful Relation</em>) record hundreds of sessions in which Kelley, gazing into a crystal "shewstone," received messages from angelic communicants. These messages included the Enochian (or "Angelic") language — a complete constructed language with its own alphabet, grammar, and nineteen "Keys" or "Calls" — along with extensive eschatological prophecy, instructions on alchemical operations, and political advice concerning the Catholic powers threatening Protestant Europe.</p>
<p>Dee understood the angel conversations not as magical operations in the grimoiric sense (he consistently denied using demonic spirits) but as a divinely sanctioned programme of reformed natural philosophy: the angels, he believed, were restoring the pure Adamic knowledge of nature lost at the Fall, equipping him to reform learning and serve the Protestant cause. Deborah Harkness's <em>John Dee's Conversations with Angels</em> (1999) provides the most thorough analysis of this project, situating it within the context of Elizabethan natural philosophy, religious reform, and Dee's political ambitions. Glyn Parry's <em>The Arch-Conjuror of England</em> (2011) provides a more sceptical reading focused on Dee's court career and the political uses of his occult reputation.</p>

<h2>Works and Manuscripts</h2>
<p>Dee's published output is smaller than his manuscript production. The <em>Propaedeumata Aphoristica</em> (1558, rev. 1568) sets out his theory of rays and celestial influence. The <em>Monas Hieroglyphica</em> (Antwerp, 1564) — dedicated to Maximilian II — is an alchemical-Kabbalistic meditation on a single glyph that Dee believed compressed universal wisdom. The <em>General and Rare Memorials pertaining to the Perfecte Arte of Navigation</em> (1577) argued for a British empire based on naval supremacy and was explicitly political.</p>
<p>His manuscripts, widely scattered during his lifetime — his library was ransacked at Mortlake during his absence in 1583 — survive principally in the British Library (Sloane and Cotton collections), the Bodleian, and Trinity College Cambridge. The Cotton Appendix and the Royal College of Physicians MS preserve key records of the angelic conferences. Stephen Clucas has edited and analysed several important manuscript sources.</p>

<h2>Scholarship</h2>
<p>The historiography of Dee has moved through several phases. Frances Yates's treatment in <em>The Rosicrucian Enlightenment</em> (1972) placed him within a Hermetic-Rosicrucian network; this was contested by scholars who found the Rosicrucian connection anachronistic. Nicholas Clulee's <em>John Dee's Natural Philosophy</em> (1988) was the first comprehensive study to treat Dee's natural philosophy seriously on its own terms. Harkness (1999) and Parry (2011) represent the current state of Dee scholarship, from complementary perspectives.</p>""",

"cornelius_agrippa": """<h2>Life</h2>
<p>Heinrich Cornelius Agrippa von Nettesheim (1486–1535) was born in Cologne into a minor noble family. His education at the University of Cologne gave him the Latin learning and Scholastic philosophy that underpin his major works, while his subsequent wandering career — soldier, diplomat, court physician, lecturer, and perennial debtor — exposed him to the intellectual currents of humanist Italy, French and English royal courts, and the reform milieu of early German Lutheranism. He served in Maximilian I's campaigns in northern Italy around 1511, where contact with Italian Platonists (including possibly pupils of Ficino's circle) sharpened his interest in occult philosophy. He lectured on Reuchlin's Kabbalistic works at Dôle in 1509 and at a young age completed a first draft of his encyclopedic <em>De occulta philosophia</em>.</p>

<h2>De occulta philosophia</h2>
<p>The <em>De occulta philosophia libri tres</em>, first circulated in manuscript from 1510 onward and finally published in 1531 (Cologne, Soter), is the most comprehensive synthesis of Renaissance occult philosophy: a structured encyclopedia covering all three "worlds" of the Neoplatonic cosmos. Book I treats natural magic — the occult properties of things in the elemental world, the four elements, the harmony of the macrocosm and microcosm, the magical use of stones, plants, metals, animals, and numbers. Book II treats celestial or mathematical magic — the influences of the seven planets, the fixed stars, and the signs of the zodiac; the construction of magical images and talismans; magical squares, the <em>camea</em> of the planets. Book III treats ceremonial or divine magic — the celestial hierarchy of angels and demons, divine names, the Kabbalah, the power of words and letters, ritual operations for drawing down divine assistance.</p>
<p>The work synthesizes an enormous range of sources: Ficino's Neoplatonism and astral medicine, Pico's Kabbalah, Trithemius on cryptography and angelic communication, pseudo-Albertus on occult properties, the Hermetic writings, Pliny, and Arabic astrological theory via al-Kindi and the <em>Picatrix</em>. Its ambition was not merely encyclopedic but philosophical: Agrippa wanted to demonstrate that a unified science of nature, properly understood, encompassed what the ignorant dismissed as superstition.</p>

<h2>De incertitudine and the Sceptical Turn</h2>
<p>The paradox of Agrippa's career is that his other major published work, <em>De incertitudine et vanitate scientiarum et artium</em> (1530, published slightly before <em>De occulta philosophia</em>), appears to repudiate everything the larger book argues for. <em>De incertitudine</em> is a Pyrrhonist satire attacking all human knowledge, including magic: Agrippa denounces the whole project of occult philosophy as vanity, asserting that only Scriptural revelation provides genuine knowledge. The relationship between the two works has been debated for centuries. Charles Nauert's <em>Agrippa and the Crisis of Renaissance Thought</em> (1965) remains the standard monograph. Paola Zambelli's work reassessed Agrippa's scepticism in the context of fideist theology and rhetorical strategies of self-protection.</p>

<h2>Influence</h2>
<p>Agrippa's influence was enormous and long-lasting. <em>De occulta philosophia</em> was reprinted throughout the sixteenth and seventeenth centuries; English versions circulated in manuscript before the 1651 printed edition (which included the spurious "Fourth Book"). John Dee owned copies and annotated them; the Elizabethan magus Simon Forman and others drew on it directly. Christopher Marlowe almost certainly drew on the Agrippa legend for <em>Doctor Faustus</em> (c.1592). The <em>Fourth Book of Occult Philosophy</em>, a demonic conjuration manual falsely appended to Agrippa's name, circulated from the 1550s, further complicating his posthumous reputation. His reputation as an extreme magician persisted long after his death.</p>""",

"frances_yates": """<h2>Life and Career</h2>
<p>Dame Frances Amelia Yates (1899–1981) was one of the most influential historians of Renaissance thought in the twentieth century, whose work transformed the study of the relationship between magic, Hermeticism, and the history of science. She was educated privately and at University College London (BA, 1924; MA, 1926), never holding a doctorate but spending her career at the Warburg Institute in London, where she rose from research associate (1941) to Reader (1956) and ultimately Honorary Fellow. Her career exemplifies the Warburg Institute's distinctive method: rigorous archival research in the iconographic and textual traditions of Renaissance Europe, guided by the conviction that images, symbols, and philosophical programmes were as historically significant as political or economic events.</p>

<h2>Major Works</h2>
<p>Yates's scholarly production falls into two broad phases. Her early work focused on the French and English Renaissance, producing studies of the <em>Académie de Poésie et de Musique</em> (<em>The French Academies of the Sixteenth Century</em>, 1947), John Florio (<em>A Study of Love's Labour's Lost</em>, 1936), and the Elizabethan court festival (<em>Astraea: The Imperial Theme in the Sixteenth Century</em>, 1975). Her method in these works — close reading of complex symbolic programmes in theatrical performances, court masques, and emblematic visual culture — gave her the tools she would bring to Hermeticism.</p>
<p>The second and most influential phase began with <em>Giordano Bruno and the Hermetic Tradition</em> (Routledge, 1964), in which she argued that Bruno's philosophical system was fundamentally Hermetic rather than proto-scientific, and that the recovery of the <em>Corpus Hermeticum</em> by Ficino in 1463 inaugurated a tradition of "Hermetic" thought that ran through the Renaissance and into the seventeenth century, contributing to the emergence of what she called "the Rosicrucian enlightenment." <em>The Art of Memory</em> (1966) traced the ancient and Renaissance tradition of the memory systems from Cicero through Ramon Llull, Giulio Camillo's memory theatre, and Bruno's mnemonic works, arguing that the art of memory was deeply implicated in magical and Hermetic thinking. <em>The Rosicrucian Enlightenment</em> (1972) extended the argument into the early seventeenth century, linking the anonymous Rosicrucian manifestos (1614–1616) to the Palatine court of Frederick V and Elizabeth Stuart and to a utopian programme of Hermetic reform that Yates connected to Francis Bacon and early modern science.</p>

<h2>The Yates Thesis and Its Afterlife</h2>
<p>The central claim of the "Yates thesis" — that Hermetic magic provided crucial psychological and conceptual preconditions for the Scientific Revolution — was debated intensely from the 1970s onward. Brian Vickers, Robert Westman, David Lindberg, and others argued that the thesis overstated Hermeticism's role and understated the continuities with Scholastic Aristotelian natural philosophy. The specific claim about Hermeticism's causal role in Copernicanism (Yates had suggested Bruno influenced Copernicus's heliocentric commitment) was largely abandoned. Yet the broader achievement — establishing the study of Renaissance magic and esotericism as a legitimate historical discipline, and demonstrating that Hermetic and occult traditions deserved the same rigorous historical attention as mathematical astronomy or Protestant theology — remains acknowledged as a foundational contribution.</p>
<p>Yates was appointed OBE in 1972 and DBE in 1977. She received honorary degrees from Edinburgh, Essex, East Anglia, and Exeter. Her papers are held at the Warburg Institute.</p>""",

}


# ---------------------------------------------------------------------------
# TEXTS – analysis_html
# ---------------------------------------------------------------------------

TEXT_ENRICHMENTS = {

"de_occulta_philosophia": """<h2>Overview</h2>
<p><em>De occulta philosophia libri tres</em> (Three Books of Occult Philosophy) by Heinrich Cornelius Agrippa von Nettesheim was first circulated in manuscript from around 1510, circulated widely in that form through networks connecting the Rhine valley humanists to Italian Neoplatonists, and finally published in printed form in 1531 (Cologne, Johannes Soter). A heavily revised version appeared the same year in Antwerp. The work is the most ambitious encyclopedic synthesis of Renaissance occult philosophy: a three-book structure corresponding to the three worlds of Neoplatonic cosmology — the elemental world, the celestial world, and the intellectual world — and providing a comprehensive account of the theory and practice of natural, celestial, and ceremonial magic.</p>

<h2>Structure and Contents</h2>
<p><strong>Book I (Natural Magic)</strong> covers the occult properties of the four elements, the sympathies and antipathies among things in the elemental world, the medical and magical uses of plants, stones, and metals, the doctrine of occult qualities (following pseudo-Albertus and al-Kindi), the role of the imagination and passions in magical operations, and the theory of the world-soul as the mediating principle through which magical influence travels.</p>
<p><strong>Book II (Celestial or Mathematical Magic)</strong> addresses the seven planets and their influence on temperament and character, the construction of astrological talismans and magical images, the magical squares (<em>camea</em>) attributed to each planet (with their numerological and geometric properties), the magical significance of numbers, proportions, and geometric figures, and the doctrine of the fixed stars and their images.</p>
<p><strong>Book III (Ceremonial or Divine Magic)</strong> is the most contentious and the most theologically ambitious. It treats the angelic and demonic hierarchies in their relationship to the divine names; the Kabbalah as a technology of divine name manipulation; the power of words, letters, characters, and seals; and the operations by which the magus might ascend through the celestial hierarchy to communicate with angels, culminating in the figure of the <em>homo divinus</em> who unites the three worlds in a single act of mystical gnosis. This book draws heavily on Pico della Mirandola, Reuchlin's Kabbalistic works, and Trithemius.</p>

<h2>Sources and Method</h2>
<p>The erudition deployed across the three books is remarkable. Agrippa synthesizes Ficino's <em>De vita</em> and <em>Platonic Theology</em>, Pico's <em>Conclusiones</em>, the pseudo-Albertian natural magic treatises, al-Kindi's <em>De radiis</em>, the <em>Picatrix</em>, Proclus, Iamblichus, the <em>Corpus Hermeticum</em>, Pseudo-Dionysius, the <em>Sefer Yetzirah</em>, and hundreds of other sources from ancient, Arabic, Jewish, and Christian traditions. The organization is not merely encyclopedic but argumentative: Agrippa wants to demonstrate that all these traditions converge on a unified account of how occult power operates in the universe, and that a properly trained philosophical magician can work within this system without demonic pact.</p>

<h2>Manuscript Tradition and Printed Editions</h2>
<p>The manuscript versions of <em>De occulta philosophia</em> circulated from 1510 onward, with a copy sent to Trithemius (who responded cautiously but approvingly) and others reaching Erasmus's circle. The differences between the manuscript versions and the 1531 printed text are significant: Agrippa removed some of the more provocative material on ceremonial magic and added a preface emphasizing the work's natural-philosophical orientation. The 1531 Antwerp edition incorporates further revisions. The 1651 English edition (attributed to J.F.) is the version most familiar to Anglophone occultists but contains numerous translation errors and was accompanied by the spurious <em>Fourth Book of Occult Philosophy</em>, which has caused confusion about the limits of Agrippa's authorship.</p>

<h2>Scholarly Reception</h2>
<p>Charles Nauert's <em>Agrippa and the Crisis of Renaissance Thought</em> (1965) remains the standard scholarly biography and remains essential for understanding the <em>De occulta philosophia</em> in context. Brian Copenhaver's work on Renaissance magic has repeatedly returned to Agrippa as a central case study in the relationship between Neoplatonic philosophy and practical magic. Wouter Hanegraaff's <em>Esotericism and the Academy</em> (2012) treats the work as a founding text in the Western esoteric tradition. For the manuscript tradition, see the studies of V. Perrone Compagni, who produced the critical edition (Brill, 1992).</p>""",

"transformations_of_magic": """<h2>Overview</h2>
<p>Frank Klaassen's <em>The Transformations of Magic: Illicit Learned Magic in the Later Middle Ages</em> (Penn State University Press, 2013) is the most rigorous analysis of what Klaassen calls the "experiment literature" — the practical ritual magic books (nigromantic handbooks, ars notoria texts, Solomonic conjuration manuals) that circulated in manuscript among clerically trained readers in medieval England and Continental Europe from approximately 1300 to 1500. The book argues against two misleading models: the model that treats medieval magic as a unified, coherent tradition with stable content, and the model that treats the learned magical tradition as a pale copy of, or preparation for, Renaissance Hermeticism. Instead, Klaassen documents what actually survived in English manuscripts and shows how the content, purposes, and social contexts of learned magic shifted substantially over two centuries.</p>

<h2>Argument and Evidence</h2>
<p>Klaassen's central methodological contribution is the systematic survey of a defined corpus: he identifies and analyses approximately 270 surviving manuscripts containing ritual magic material in the medieval English tradition, rather than relying on a handful of well-known texts. This allows him to distinguish majority practice (ars notoria texts, image magic, simple conjurations) from exceptional cases (full demonic pact rituals), to trace the social circulation of texts across different manuscript contexts, and to identify two distinct types of transformation across the later medieval period.</p>
<p>The first transformation Klaassen identifies is a shift from "Solomonic" ritual magic — which emphasised the magician's moral purity, his Solomonic authority, and the coercive binding of spirits within a broadly Christian ritual framework — toward a more openly demonic conjuration literature in which the pact and explicit appeal to demonic power become more visible. The second transformation, running in the opposite direction, is the gradual absorption of Solomonic and image magic into the emerging idiom of "natural philosophy": Klaassen documents how later medieval readers and scribes increasingly framed magical operations in naturalistic terms, aligning them with Albertan and Arabist accounts of occult properties and celestial influence, effectively naturalising what earlier manuscripts had treated as operations of religious power.</p>

<h2>Significance for Grimoire Studies</h2>
<p>The book makes three major contributions to the study of the grimoire tradition. First, by documenting the manuscript evidence rather than relying on printed editions, Klaassen corrects the distortions introduced by the selective survival and editorial intervention of printed magical texts. Second, by demonstrating that "the learned magical tradition" is not a single thing but a set of practices and texts that changed substantially across two centuries, the book warns against the anachronistic projection of later Renaissance or early modern magical theory back onto medieval texts. Third, by focusing on what scribes and readers actually did with manuscripts — how they copied, excerpted, combined, and reorganised texts — Klaassen provides a model of manuscript-culture analysis that influenced subsequent work on the Ars Notoria, the Munich Manual, and Solomonic texts.</p>

<h2>Context and Reception</h2>
<p>Klaassen's work was preceded by and engages throughout with Richard Kieckhefer's <em>Forbidden Rites</em> (1997), which edited and analysed the Munich Manual of demonic magic, and with Claire Fanger's edited volumes on medieval ritual magic. It has been widely cited in subsequent scholarship on the grimoire tradition, including Dan Harms and Joseph Peterson's work on specific texts and Sophie Page's studies of magical manuscripts in institutional collections.</p>""",

"spiritual_demonic_magic_walker": """<h2>Overview</h2>
<p>D.P. Walker's <em>Spiritual and Demonic Magic from Ficino to Campanella</em>, first published by the Warburg Institute in 1958 (and reissued in paperback by Penn State University Press, 2000), is the foundational scholarly study of Renaissance learned magic as a philosophical problem. Written before Frances Yates's more ambitious synthetic works, the book is more cautious in its causal claims and more attentive to the philosophical difficulties confronting Renaissance thinkers who sought to claim legitimate natural-philosophical authority for operations that resembled, and often derived from, the demonic magic condemned by medieval theologians. It remains required reading for any study of Renaissance occult philosophy.</p>

<h2>Argument</h2>
<p>Walker's central question is: how did Renaissance Neoplatonist magicians — above all Ficino and his successors — attempt to distinguish their operations from demonic magic, and how successful were these attempts philosophically and practically? The problem Walker identifies is structural: the theoretical framework through which Ficino explained the efficacy of his astral magic (the doctrine of the world-soul, pneumatic mediation, the sympathy of like for like) derived from Neoplatonic sources — Plotinus, Iamblichus, Proclus — that were not themselves entirely innocent of demonic implication. Iamblichus and Proclus had both discussed the role of daemons in ritual operations; the intermediary spirits of Neoplatonic theurgy shaded imperceptibly into the Christian demons that any orthodox theologian was required to condemn.</p>
<p>Walker traces the problem through a sequence of case studies: Ficino's <em>De vita coelitus comparanda</em>, Pico della Mirandola's attempt to distinguish Kabbalah from demonic magic, Francesco Giorgi's <em>Harmonia mundi</em>, Cornelius Agrippa's <em>De occulta philosophia</em>, Giambattista della Porta's <em>Magia naturalis</em>, the music-magic theory of Ficino's successors, and the later career of the tradition through Francesco Patrizi, Giordano Bruno, and Tommaso Campanella. In each case, Walker shows both the sophistication of the attempt to naturalize magical operations and the points at which the naturalization broke down — where the philosopher needed to invoke spirit-working that could not be fully distinguished from demonic cooperation.</p>

<h2>Key Concepts</h2>
<p>"Spiritual magic" in Walker's usage designates operations that work through the <em>spiritus</em> — the subtle pneumatic vehicle of the soul and the world-soul — and that their practitioners claimed were purely natural, operating through the sympathetic relationships between celestial and terrestrial things. "Demonic magic" designates operations that require explicit cooperation with demonic or angelic intelligences as rational, personal agents. Walker's argument is that the boundary between these two types was genuinely contested and philosophically unstable throughout the tradition he surveys.</p>
<p>Walker also contributed the concept of "spiritual magic as a problem of orthodoxy" — the observation that Renaissance philosophers were not simply operating in a pre-scientific context where magic was unproblematically acceptable, but were themselves aware of the theological dangers and sought to manage them. This insight corrected older historiography that presented Renaissance magic as naive belief, and anticipated more recent work on learned magic as a theoretically sophisticated practice.</p>

<h2>Legacy</h2>
<p>Walker's book was the immediate predecessor and in some respects the model for Frances Yates's work, and the relationship between them is worth noting. Walker's caution and his focus on philosophical tensions contrasts with Yates's synthetic ambition; scholars who found Yates's thesis too sweeping have generally returned to Walker's more cautious framework. Brian Copenhaver's philosophical analysis of Ficino builds directly on Walker; D.P. Walker's other work on music and magic (in essays collected in <em>Music, Spirit and Language in the Renaissance</em>, ed. Pennelope Gouk, 1985) extends the book's concerns. The Walker tradition — careful philosophical reading, attention to the natural/demonic distinction, sensitivity to the risks faced by Renaissance magical thinkers — remains the dominant approach in the field.</p>""",

}


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    updated = 0
    for slug, html in CONCEPT_ENRICHMENTS.items():
        row = conn.execute("SELECT id FROM concepts WHERE slug=?", (slug,)).fetchone()
        if row:
            conn.execute("UPDATE concepts SET definition_long=? WHERE slug=?", (html, slug))
            print(f"  concept: {slug} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING concept: {slug}")

    for pid, html in PERSON_ENRICHMENTS.items():
        row = conn.execute("SELECT id FROM persons WHERE person_id=?", (pid,)).fetchone()
        if row:
            conn.execute("UPDATE persons SET bio_html=? WHERE person_id=?", (html, pid))
            print(f"  person: {pid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING person: {pid}")

    for tid, html in TEXT_ENRICHMENTS.items():
        row = conn.execute("SELECT id FROM texts WHERE text_id=?", (tid,)).fetchone()
        if row:
            conn.execute("UPDATE texts SET analysis_html=? WHERE text_id=?", (html, tid))
            print(f"  text: {tid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING text: {tid}")

    conn.commit()
    print(f"\nUpdated {updated} entries.")
    conn.close()


if __name__ == "__main__":
    main()
