"""
Enrich batch 6: texts and remaining persons.
"""
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import DB_PATH


CONCEPT_ENRICHMENTS = {}  # No new concepts this batch


PERSON_ENRICHMENTS = {

"abu_mashar": """<h2>Life</h2>
<p>Abu Mashar al-Balkhi (787–886 CE) — known in Latin as Albumasar — was the most influential Islamic astrologer and astronomer of the ninth century, whose works became the primary channel through which Aristotelian cosmology and astrological theory were transmitted to the Latin West in the twelfth century. Born in Balkh (in modern Afghanistan), he moved to Baghdad, initially as a hadith scholar, and converted to astrology under the influence of al-Kindi. He spent most of his career in Baghdad, dying at the remarkable age of ninety-nine.</p>

<h2>Works and Influence</h2>
<p>Abu Mashar's <em>Kitab al-madkhal al-kabir</em> (Great Introduction to Astrology) — translated into Latin by Hermann of Carinthia in 1140 as <em>Introductorium maius in astronomiam</em> — provided the most systematic account available in the Latin West of the theoretical basis for astrology. The prologue, in which Abu Mashar argued that Aristotle himself had acknowledged celestial influence on terrestrial change, was enormously influential: it gave astrology a philosophical pedigree and made it appear as a straightforward application of Aristotelian natural philosophy. Roger Bacon cited Abu Mashar extensively in his arguments for the legitimacy of astrological enquiry.</p>
<p>Abu Mashar's <em>De magnis coniunctionibus</em> (On Great Conjunctions), translated by John of Seville, applied astrological theory to historical prophecy: the conjunctions of Jupiter and Saturn every twenty years, and of all planets at longer intervals, determined the rise and fall of religions, dynasties, and civilisations. This historico-astrological theory was taken up by medieval and Renaissance political astrologers and contributed to the tradition of prophetic astrology that intersected with learned magic. David Pingree's work on Abu Mashar's sources and influence provides the scholarly context.</p>""",

"adelard_of_bath": """<h2>Life</h2>
<p>Adelard of Bath (c.1080–c.1152) was an English natural philosopher and translator who made crucial early contributions to the transfer of Arabic natural philosophy and mathematics into Latin Europe. Born probably in Bath, he studied in Tours and Laon, then travelled extensively in southern Italy, Sicily, and probably the Arabic-speaking world (Antioch, possibly further east), learning Arabic and gaining access to the learned culture of the Islamic world before its full transmission to northern Europe. He returned to England and served at the court of the young King Henry II.</p>

<h2>Translations and Natural Philosophy</h2>
<p>Adelard's translations introduced foundational texts to the Latin West: Euclid's <em>Elements</em> (from Arabic, c.1120) in a translation that remained standard for centuries; al-Khwarizmi's astronomical tables (<em>Zij</em>); and Abu Mashar's <em>Introductorium minus</em> (the shorter introduction to astrology). His own <em>Quaestiones naturales</em> — a dialogue framed as a conversation with his nephew — introduced naturalistic explanations of a wide range of phenomena (why plants grow from seeds, why the sea is salty, how the senses work) that he attributed to "the Arabs," framing natural philosophy as the distinctive achievement of Arabic learning that Latin Europe lacked.</p>
<p>For the history of magic, Adelard is important as one of the earliest Latin conduits for Arabic astrological and natural magical theory, and for his methodological commitment to natural explanation: the <em>Quaestiones naturales</em> consistently seeks natural causes for apparently marvellous phenomena, prefiguring the naturalization strategies of Albertus Magnus and Roger Bacon. His translations of astronomical tables also enabled the precise timing of astrological and magical operations that the more sophisticated Latin magical tradition required.</p>""",

"isidore_of_seville": """<h2>Life</h2>
<p>Isidore of Seville (c.560–636 CE) was Archbishop of Seville from around 600 CE until his death, a central figure in the Visigothic Spanish church, a church council president, and the most important encyclopedist between late antiquity and the twelfth-century renaissance. Born into a noble Hispano-Roman family that included two other bishops, he was educated in the episcopal school at Seville, possibly under his brother Leander. He presided over the Third Council of Toledo (589) that oversaw the Visigothic conversion from Arianism to Catholicism, and continued to shape Spanish ecclesiastical and intellectual culture until his death.</p>

<h2>The Etymologiae and Magic</h2>
<p>Isidore's <em>Etymologiae</em> or <em>Origines</em> (completed c.623–636, in twenty books) was the most widely copied reference work in medieval Europe from the seventh through twelfth centuries — over one thousand manuscripts survive. It is organized as an encyclopedia of all knowledge, proceeding by etymology (tracing the origins of words) on the principle that a thing's name reveals its nature. Book VIII, chapter 9 (on the magicians) provides the taxonomy of forbidden arts that dominated medieval Christian classification of magic for six centuries: <em>magi</em> (magicians, from the Persian priestly caste), <em>malefici</em> (evildoers), <em>mathematici</em> (those who predict through stars), <em>haruspices</em> (from entrails), <em>augures</em> (from birds), <em>pythones</em> (those speaking through demons), <em>arioli</em> (who prophesy through demons), <em>astrologi</em>, and <em>sortilegi</em> (casters of lots). Each term is given an etymology and a brief characterization.</p>
<p>This taxonomy was transmitted into the medieval canon law tradition — Rabanus Maurus's <em>De magicis artibus</em> (c.842) follows it closely; Burchard of Worms's <em>Decretum</em> (c.1012) incorporates it; and ultimately Gratian's <em>Decretum</em> (c.1140) enshrined it in the canonical legal collection that governed the medieval Church's response to magic and divination. When Thomas Aquinas in the <em>Summa theologiae</em> asks whether divination is sinful, he is working within a framework whose categories ultimately derive from Isidore. Richard Kieckhefer and Michael Bailey both identify the <em>Etymologiae</em> as the starting point for any history of medieval magic classification.</p>""",

"michael_scot": """<h2>Life</h2>
<p>Michael Scot (c.1175–c.1232) was a Scottish scholar whose career exemplifies the role of the Arabic-Latin translator in transmitting Aristotelian and astrological learning to the Latin West. Educated probably in Oxford and Paris, he spent time in Toledo (where he learned Arabic) and eventually in Palermo at the court of Frederick II of Sicily — one of the most intellectually adventurous courts in medieval Europe. He served Frederick as court astrologer and intellectual advisor, and Dante placed him in the Inferno among the sorcerers (Inferno XX, 116), attributing to him magical knowledge that was almost certainly legendary.</p>

<h2>Translations and Works</h2>
<p>Michael's translations from Arabic into Latin were among the most important of the twelfth and thirteenth centuries. He translated Averroes's (Ibn Rushd's) commentaries on Aristotle's natural philosophical works — the <em>De caelo</em>, <em>De anima</em>, <em>De generatione et corruptione</em>, and the zoological works — introducing the "Commentator" (Averroes's standard scholastic title) to Latin scholasticism. He also translated Aristotle's <em>De animalibus</em> directly from Arabic and Alpetragius's astronomical work <em>De motibus celorum</em>. These translations transformed Latin natural philosophy by making the Arabic Aristotelian commentaries available.</p>
<p>Michael's own works include an <em>Introductorium</em> (introduction to astrology and physiognomy), a <em>Liber particularis</em> (on physiognomy and astronomy), and a work on alchemy attributed to him. The reputation for magical knowledge that Dante attributes to him was built up in the Italian literary tradition and probably reflects the same tendency to ascribe occult knowledge to learned Arabic-Latin translators visible in the pseudo-Albertine literature: proximity to Arabic learning was construed as magical expertise. Charles Burnett's work on Michael Scot and the Toledo translation tradition provides the scholarly context.</p>""",

"pablo_torijano": """<h2>Life and Scholarship</h2>
<p>Pablo Torijano is a Spanish historian of Jewish and Christian antiquity at the Complutense University of Madrid, specializing in the traditions of learned magic and esoteric knowledge in late antique and medieval Judaism, Christianity, and Islam. His doctoral and postdoctoral work, conducted partly at Harvard Divinity School, focused on the pseudepigraphic attribution of magical and esoteric authority to King Solomon across the three Abrahamic traditions.</p>

<h2>Solomon the Esoteric King</h2>
<p><em>Solomon the Esoteric King: From King to Magus, Development of a Tradition</em> (Brill, 2002) is Torijano's principal contribution to Solomonic studies and one of the foundational works for understanding the historical development of the Solomonic magical tradition. The book traces the transformation of the biblical Solomon — the wise, wealthy, divinely-favoured king of the Hebrew Bible — into the master of demons, angels, and occult knowledge who appears in late antique and medieval magical literature. Torijano works across the full range of relevant sources: the <em>Testament of Solomon</em> and related pseudepigrapha, Qurʾanic and Islamic commentary traditions concerning Sulayman, Jewish magical texts from the Geonic period (<em>Sepher ha-Razim</em>, Solomonic adjurations), and the Latin grimoire tradition.</p>
<p>The book's central argument concerns attribution as a dynamic textual strategy: Solomonic authority was not a fixed attribute of a defined body of texts but a mobile legitimating claim that different communities in different periods attached to different textual traditions. Jewish, Christian, and Islamic communities all used Solomonic attribution, but for different texts and in different theological and social contexts. Torijano's comparative cross-cultural analysis — requiring competence in Hebrew, Greek, Arabic, and Latin — makes the book an unusual achievement in the history of religions.</p>""",

"peter_abano": """<h2>Life</h2>
<p>Pietro d'Abano (c.1257–c.1316) — known in Latin sources as Petrus de Abano — was an Italian physician and natural philosopher from Abano Terme near Padua who became one of the most influential medical and astrological authorities of the early fourteenth century. He studied medicine at Paris and was associated with the University of Padua, where he may have taught. He was twice accused of heresy before the Inquisition — once acquitted during his lifetime, once condemned posthumously — for astrological claims touching on determinism and for allegedly possessing a philosopher's stone.</p>

<h2>Works and Significance for Magic</h2>
<p>Pietro's <em>Conciliator differentiarum philosophorum et praecipue medicorum</em> (Conciliator, printed 1472) was his most influential work: a vast reconciliation of the disagreements between Arabic and Galenic medicine and between Arabic astrology and Aristotelian natural philosophy, organized in 210 "differences" (disputationes). Several differences address the relationship between celestial influence and terrestrial events, including the production of marvellous effects through astrological knowledge.</p>
<p>The pseudo-Abanian <em>Heptameron, seu elementa magica</em> was attributed to Pietro d'Abano and circulated extensively in the sixteenth and seventeenth centuries, often appended to Agrippa's <em>De occulta philosophia</em>. The <em>Heptameron</em> provides a system of spirit conjuration organized by the days of the week and the angels and spirits associated with each day, with conjuration formulas, magic circles, and fumigations. Whether Pietro had any connection to this text is unclear; the attribution exploited his authority as a naturalistic philosopher to legitimate a practical conjuration system. Nicolas Weill-Parot's work on Pietro's engagement with image magic theory in the <em>Conciliator</em> clarifies his genuine contribution to the scholastic debate about astrological causation.</p>""",

"sophie_page": """<h2>Life and Scholarship</h2>
<p>Sophie Page is a historian of medieval intellectual and religious culture at University College London, specializing in magical manuscripts, their institutional contexts, and their relationship to natural philosophy and theology in medieval England. Her work addresses questions about how magical texts were collected, stored, used, and theorized within institutional (especially monastic) settings, challenging the assumption that magical manuscripts were only or primarily the product of disreputable clerical subculture.</p>

<h2>Magic in the Cloister</h2>
<p><em>Magic in the Cloister: Pious Motives, Illicit Interests, and Occult Approaches to the Medieval Universe</em> (Penn State University Press, 2013) is Page's major work. The book examines the manuscript evidence for magical texts in English monastic and collegiate libraries — principally the collections associated with St Augustine's Canterbury, the Augustinian canons at Oxford, and related institutions — and argues that monks and other religious who possessed and used magical texts did so for reasons that made sense within their own religious framework: curiosity about the natural world, the pursuit of practical knowledge (medical, astronomical, calendrical), and a genuine interest in the relationship between the observable world and its hidden causes.</p>
<p>Page's approach, combining codicological analysis (examining how magical texts are bound, where they appear in manuscript collections, what they are associated with) with intellectual history (what theoretical frameworks the possessors brought to the texts), has been influential in demonstrating that magical manuscripts cannot be understood in isolation from their manuscript contexts. A text appearing in a miscellany alongside medical recipes, astronomical tables, and grammatical exercises tells a different story than the same text appearing alone or in a collection of overtly transgressive material.</p>""",

"dan_harms": """<h2>Life and Scholarship</h2>
<p>Dan Harms is an independent scholar and librarian who has made major contributions to the editing and documentation of early modern English magical manuscripts and to making grimoire scholarship accessible to both specialist and general readers. His work combines archival research in manuscript collections with the rigorous editorial standards developed by academic grimoire scholars, producing editions that serve both historians and practitioners of magic.</p>

<h2>The Book of Oberon</h2>
<p><em>The Book of Oberon: A Source Book of Elizabethan Magic</em> (Llewellyn, 2015), co-edited with James R. Clark and Joseph H. Peterson, is the critical edition of a previously unstudied seventeenth-century English magical manuscript (Folger Shakespeare Library MS V.b.26). The manuscript — a miscellany of Elizabethan and Jacobean magical material including conjurations of named spirits, including the fairy Oberon, love magic, treasure-finding procedures, and Solomonic-style ritual — provides an invaluable window into the practical magic of educated Elizabethan England. The edition provides complete transcription, translation where necessary, and extensive annotation identifying sources and parallels in the wider grimoire tradition.</p>
<p>Harms's collaboration with Joseph Peterson on <em>The Long-Lost Friend</em> (Llewellyn, 2012) — a scholarly edition of John George Hohman's 1820 Pennsylvania German magical handbook — applied the same editorial rigour to American folk magic, tracing the sources of Hohman's compilation in German magical literature and documenting its use in Pennsylvania Dutch and later African-American magical traditions. These editorial projects exemplify the democratization of grimoire scholarship: making rigorously edited primary texts available to non-specialist readers without sacrificing scholarly standards.</p>""",

"etienne_tempier": """<h2>Life</h2>
<p>Étienne Tempier (d. 1279) was appointed Bishop of Paris in 1268, after a career as a master of theology at Paris. His tenure as bishop coincided with the height of the "radical Aristotelianism" controversy: the teaching by Siger of Brabant and others of philosophical positions derived from Aristotle and Averroes that seemed to conflict with Christian doctrine, including the eternity of the world, the unity of the intellect (there is only one intellect for all humanity, not individual intellects), and the necessary determination of events by celestial causes. Tempier responded to this controversy with two rounds of condemnations that permanently shaped the intellectual context of the medieval and Renaissance university.</p>

<h2>The Condemnations of 1270 and 1277</h2>
<p>The condemnation of 1270 (thirteen theses) targeted the most immediately problematic propositions associated with radical Aristotelianism, including the unity of the intellect, the eternity of the world, and determinism about celestial causation. The condemnation of 1277 (219 theses) was far more sweeping. Issued on 7 March 1277 — the third anniversary of Thomas Aquinas's death, a coincidence that generated immediate comment — the 219 condemned theses included propositions concerning free will and celestial determination, the limits of divine omnipotence, the impossibility of multiple worlds, and many others. Among those condemned were propositions associated with Aquinas himself, though Aquinas was not named.</p>
<p>For the history of magic, the condemnations are significant for their treatment of celestial causation: several condemned theses assert that celestial bodies necessarily determine terrestrial events including human choices (propositions 161, 162, 207 in the standard enumeration). Condemning astrological determinism forced subsequent natural philosophers to be more careful about how they articulated the relationship between stellar influence and human freedom — which in turn constrained how they could theorize the causal basis of astrological and talismanic magic. Nicolas Weill-Parot's work on addressative magic analyses these effects in detail.</p>""",

"dan_attrell": """<h2>Life and Scholarship</h2>
<p>Dan Attrell is a scholar of Renaissance magic and esotericism whose primary contribution to the field is his co-translation (with David Porreca) of the <em>Picatrix</em> — the most comprehensive medieval Latin text of astrological magic — into English, published by Penn State University Press in 2019. The translation, the first complete scholarly English rendering of the Latin text, makes David Pingree's 1986 critical edition accessible to readers without Latin and provides an extensively annotated version that identifies sources, parallels, and scholarly context throughout.</p>

<h2>Picatrix Translation</h2>
<p>The Attrell-Porreca translation draws on Pingree's two-volume critical edition and the earlier Spanish translation (by Maslama al-Majriti, 1256) to produce an English text that is both readable and scholarly. The introduction and notes situate the text within its Arabic and Latin transmission history, identifying the philosophical sources (Neoplatonic, Hermetic, Aristotelian) that underpin the <em>Picatrix</em>'s theory of astral magic and providing the contextual information that readers need to use the text as a historical source. The translation has been widely adopted in university courses on Renaissance magic and the history of science.</p>
<p>Attrell's broader scholarly interests include Renaissance Neoplatonism, the history of Western esotericism, and the theory of magic in early modern Europe. His work contributes to the continuing project of making primary sources in the medieval and Renaissance magical tradition available in rigorous scholarly editions — essential infrastructure for a field that has long suffered from a gap between specialist manuscript scholarship and popular occultist editions.</p>""",

}


TEXT_ENRICHMENTS = {

"ancient_jewish_magic": """<h2>Overview</h2>
<p>Gideon Bohak's <em>Ancient Jewish Magic: A History</em> (Cambridge University Press, 2008) is the most comprehensive and analytically rigorous account of Jewish magical practice from the biblical period through the end of late antiquity, and the essential foundation for understanding the Jewish roots of the Solomonic grimoire tradition. Bohak draws on an extraordinary range of material and textual evidence: biblical and deuterocanonical literature, Dead Sea Scrolls, Greek magical papyri, Aramaic incantation bowls, lead curse tablets, Genizah fragments, and rabbinic literature.</p>

<h2>Argument and Evidence</h2>
<p>Against the tendency to treat "ancient Jewish magic" as simply one local variant of a homogeneous Mediterranean magical culture, Bohak argues that Jewish magical practice was a distinctive tradition with identifiable features, practices, and practitioners — even as it both borrowed from and contributed to the broader magical cultures of Egypt, Mesopotamia, and the Hellenistic world. The distinctively Jewish features include: the use of specific divine names (YHWH rendered in Greek as IAO, SABAOTH, ADONAI) as compelling forces in adjuration; the invocation of biblical patriarchs and figures (Abraham, Isaac, Jacob, Moses, Solomon) as authorizing precedents; the use of Hebrew and Aramaic in formulas where other languages would serve equally well magically; and the integration of magical practice with a specifically Jewish cosmology of angels, demons, and divine names.</p>
<p>The book proceeds chronologically: biblical period attestations (the <em>urim and thummim</em>, the bronze serpent, prophylactic and curative procedures); Second Temple literary sources (Dead Sea Scrolls, Enochic literature, early Solomonic traditions); the Greek magical papyri and their Jewish elements; Aramaic incantation bowls from Babylonian Jewish communities; and Genizah magical texts. The final chapters discuss the relationship between Jewish magic and rabbinic authority, arguing that the rabbis both condemned and participated in magical practice.</p>

<h2>Significance</h2>
<p>For the history of the Solomonic tradition specifically, Bohak provides the indispensable pre-history: the early Jewish foundations of Solomonic magical authority, the angelic adjuration traditions that the <em>Sepher ha-Razim</em> and <em>Testament of Solomon</em> develop, and the role of Hebrew divine names in creating the distinctive character of Solomonic conjuration. Together with Pablo Torijano's <em>Solomon the Esoteric King</em> (2002), Bohak's work establishes the Jewish scholarly foundation for the entire Solomonic corpus.</p>""",

"corpus_hermeticum_latin": """<h2>Overview</h2>
<p>The <em>Corpus Hermeticum</em> is a collection of seventeen Greek philosophical and religious dialogues attributed to Hermes Trismegistus (the "thrice-greatest Hermes"), a syncretic figure identified with the Egyptian god Thoth and presented as an ancient Egyptian sage who received divine revelations about the cosmos, the soul, and spiritual ascent. The texts, actually composed in the first three centuries CE (as Casaubon demonstrated in 1614), were translated into Latin by Marsilio Ficino in 1463 at the urgent request of Cosimo de' Medici, circulated in manuscript as <em>Pimander</em>, and printed in 1471. Ficino's translation initiated the "Hermetic Renaissance" and provided the theoretical foundation for Renaissance natural magic.</p>

<h2>Contents</h2>
<p>The seventeen dialogues are varied in character. The most important for the magical tradition are: <em>Poimandres</em> (Treatise I), in which Hermes receives a cosmogonic vision from the divine Mind; Treatise IV, on the cup of the mind and the opportunity for gnosis; Treatise X, on the divine mind; and the <em>Asclepius</em> (transmitted separately in Latin, probably through Apuleius), which includes the famous passage on the "animated statues" of Egypt — images made by priests that were believed to draw divine powers into material forms, the closest ancient parallel to Renaissance talismanic magic.</p>
<p>Ficino interpreted the texts as evidence of a <em>prisca theologia</em> predating Plato — Moses had inspired Hermes, or vice versa — that anticipated Christian theology. This reading, accepted by virtually all Renaissance readers, made the texts authoritative and safe. Isaac Casaubon's 1614 demonstration that the texts were early Christian in date rather than Egyptian in origin did not immediately destroy their influence, but gradually undermined the <em>prisca theologia</em> framework.</p>

<h2>Scholarship</h2>
<p>Brian Copenhaver's edition and translation (<em>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</em>, Cambridge University Press, 1992) is the scholarly standard and includes an extensive introduction. Garth Fowden's <em>The Egyptian Hermes</em> (Cambridge, 1986) provides the historical context for the texts' composition. For the Renaissance reception, D.P. Walker's and Frances Yates's work remain foundational; Wouter Hanegraaff's <em>Esotericism and the Academy</em> (2012) situates the Hermetic texts in the longer history of Western esotericism.</p>""",

"de_radiis": """<h2>Overview</h2>
<p>Al-Kindi's <em>De radiis stellarum</em> (On Stellar Rays) — surviving only in a medieval Latin translation, its Arabic original apparently lost — is the most theoretically systematic account of magical causation in the Arabic-Latin intellectual tradition and the primary source for the naturalistic theory that underlies astrological and talismanic magic. Probably written around 850 CE and translated into Latin in the twelfth century, the text argues from first principles that all causation in the cosmos operates through the radiation of qualities from every existing thing, and that this universal radiation system provides the mechanism by which magic works.</p>

<h2>The Theory of Rays</h2>
<p>Al-Kindi argues that every entity in the world — celestial and terrestrial, material and immaterial — continuously emits rays in all directions, analogous to the emission of light from a luminous body. These rays carry the specific qualities of their source and affect the things they strike, changing their qualities, movements, or states. Celestial bodies emit the most powerful and pervasive rays, because their nature is superior and their position gives them access to the entire sublunary world. But terrestrial things also emit rays; the human will and imagination, when intensely concentrated, can emit rays that affect other things at a distance — this is the theoretical basis for the magician's power.</p>
<p>The magician who understands the ray-system can work within it: by concentrating his will on a specific intention, using materials and words that resonate with specific celestial sources, timing his operations to celestial configurations that strengthen the relevant rays, he produces effects at a distance through purely natural (if hidden) causes. Al-Kindi is thus the philosopher of natural magic in its most rigorous form: magic is applied natural philosophy, and the boundaries between the two are established by knowledge rather than by essential difference.</p>

<h2>Influence</h2>
<p>The influence of <em>De radiis</em> on Latin natural philosophy was extensive. Thabit ibn Qurra's <em>De imaginibus</em> applies the ray theory to astrological image magic. Robert Grosseteste's metaphysics of light and Roger Bacon's multiplication of species draw on related principles. The <em>Speculum astronomiae</em> cites al-Kindi's works on images; Nicolas Weill-Parot's analysis of addressative magic situates <em>De radiis</em> as the theoretical foundation that subsequent scholastic discussion of image magic either accepted, qualified, or rejected. David Pingree's catalogue of al-Kindi's works provides the bibliographic context.</p>""",

"de_mineralibus": """<h2>Overview</h2>
<p>Albertus Magnus's <em>De mineralibus</em> (On Minerals, c.1262) is the most important medieval Latin treatise on the occult properties of stones, metals, and related mineral substances, and the foundational text for the scholastic naturalization of mineral magic. Composed at Cologne within Albertus's massive project of paraphrasing the entire Aristotelian corpus, the work draws on Aristotle's lost <em>Meteorologica</em> IV (reconstructed from Arabic sources), Avicenna's mineralogical sections of the <em>Shifa</em>, pseudo-Aristotelian lapidaries, and Albertus's own claimed experience with stones.</p>

<h2>Contents and Theory</h2>
<p><em>De mineralibus</em> is organized in five books. Books I–II cover the theoretical basis: the generation of metals and stones from the influence of celestial bodies acting on terrestrial matter through heat and vapour; the principle that each stone receives a "specific form" from the celestial configuration dominant at its formation, which gives it powers exceeding its elemental composition. Books III–V provide the practical coverage: individual metals, individual stones (organized as a lapidary), and individual minerals, with their properties, locations of occurrence, and uses.</p>
<p>The theoretical move is philosophically important: by grounding the occult properties of stones in their formation under specific celestial configurations, Albertus naturalizes mineral magic entirely — the stone's power comes from the stars, which are natural causes, not from demonic agency. A stone used in a talisman works because it concentrates the specific celestial virtue impressed on it during formation, acting as a kind of natural lens for planetary power. This framework was the primary scholastic resource for defending talismanic magic as licit natural philosophy rather than condemned demonic magic.</p>

<h2>Pseudo-Albertine Literature</h2>
<p>The enormous authority of <em>De mineralibus</em> generated a pseudo-Albertine literature of practical magic texts — the <em>Liber aggregationis</em> (Secrets of Albertus Magnus), <em>De virtutibus herbarum, lapidum, et animalium</em>, and related texts — that circulated under Albertus's name as authorizing attributions. These texts, widely printed after 1500, blur the boundary between Albertus's naturalistic framework and practical magical application, showing how the scholarly authority of <em>De mineralibus</em> was exploited to legitimate popular and practical magic.</p>""",

"de_universo_william_auvergne": """<h2>Overview</h2>
<p>William of Auvergne's <em>De universo</em> (On the Universe, c.1231–1236), the most ambitious part of his <em>Magisterium divinale et sapientiale</em>, is the most systematic scholastic analysis of natural magic, astral influence, and demonic operations composed before Thomas Aquinas. Written when William was already Bishop of Paris (from 1228), it represents both a serious philosophical engagement with the newly available Arabic natural philosophy and a determined effort to maintain the boundaries of orthodox Christian thought against what William saw as the errors of astrological determinism and natural magic theory.</p>

<h2>Treatment of Magic and Natural Causation</h2>
<p>William distinguished sharply between natural powers (admissible in principle) and demonic cooperation (always forbidden). His engagement with Arabic astrological image magic — the theory that planetary images, properly made and timed, could attract and concentrate celestial influence through purely natural causation — was sustained and philosophically sophisticated. William's conclusion was that image magic as described in Arabic sources (al-Kindi, Thabit ibn Qurra, the <em>Picatrix</em>) was impossible through natural causes alone: the specificity of the operations (not merely "attract solar influence" but "make this specific person love that specific person") exceeded what the general mechanism of celestial influence could plausibly deliver. If the operations worked, they required demonic cooperation — and were therefore condemned regardless of the practitioner's intent.</p>
<p>Nicolas Weill-Parot identifies William as the key transition figure between twelfth-century natural philosophy (which had been relatively permissive about natural magic, accepting much of the Arabic framework without detailed critique) and the stricter thirteenth-century scholastic framework that required a more rigorous naturalistic grounding before magical claims could be accepted. William's critical engagement with the Arabic magical tradition set the agenda for the subsequent debate that Albertus Magnus and Thomas Aquinas would continue.</p>""",

"etymologiae": """<h2>Overview</h2>
<p>The <em>Etymologiae</em> or <em>Origines</em> of Isidore of Seville (completed c.623–636), in twenty books, is the most comprehensive encyclopedia of late antique and early medieval knowledge and the most widely copied reference work in medieval Europe from the seventh through twelfth centuries. Over one thousand manuscripts survive. The work is organized thematically and proceeds by etymology — the principle that tracing a word's origins reveals the nature of the thing it designates — covering grammar, rhetoric, mathematics, music, astronomy, medicine, law, theology, language, anthropology, cosmology, natural history, geography, and architecture.</p>

<h2>Book VIII on the Magical Arts</h2>
<p>Book VIII, chapter 9 (<em>De magis</em>) provides the taxonomy of forbidden magical arts that became canonical for medieval Christian classification of magic. Isidore traces each term to its supposed origin: <em>magi</em> from the Persian priestly class; <em>mathematici</em> as those who cast horoscopes; <em>haruspices</em> from inspecting entrails; <em>augures</em> from observing birds; <em>sortilegi</em> from casting lots; and so forth. Each category receives an etymology and a brief characterization of its practice and its demonic basis. The list is ultimately indebted to earlier patristic writers (Tertullian, Augustine, Lactantius), but Isidore's encyclopedia gave it an authoritative, easily accessible form.</p>
<p>This taxonomy was reproduced and transmitted into the medieval canon law tradition through Rabanus Maurus's <em>De magicis artibus</em> (c.842), Regino of Prüm's penitential (<em>De ecclesiasticis disciplinis</em>, c.906), Burchard of Worms's <em>Decretum</em> (c.1012), and ultimately Gratian's <em>Decretum</em> (c.1140), which codified it in the canonical legal framework of the Western Church. When late medieval theologians and inquisitors asked what kinds of magic existed and why they were condemned, they were working within categories that ultimately derive from Isidore's encyclopedia.</p>

<h2>Book III on Astronomy</h2>
<p>Book III treats the mathematical arts, including astronomy and astrology. Isidore maintained the classical distinction between astronomy (the legitimate science of the celestial movements) and astrology in its judicial form (the prediction of individual fates from horoscopes, condemned). This distinction, transmitted through Isidore, remained a resource for medieval natural philosophers who wanted to maintain astrological natural philosophy (legitimate) while condemning divinatory astrology (illicit).</p>""",

"mafteah_shelomoh": """<h2>Overview</h2>
<p>The <em>Mafteah Shelomoh</em> (Hebrew: Key of Solomon) is a Hebrew recension of the Solomonic grimoire tradition, of which the most important surviving manuscript is British Museum MS Oriental 14759 (now British Library MS Or. 14759), edited by Herman Gollancz in 1914. Additional Hebrew manuscripts of the Key of Solomon tradition exist in the British Library, the Jewish Theological Seminary, and other collections. The Hebrew text provides independent evidence for the Solomonic spirit-binding and pentacle tradition, demonstrating that Hebrew-language versions of the Key of Solomon circulated alongside the Latin <em>Clavicula Salomonis</em> tradition and maintained distinctive features not found in the Latin manuscripts.</p>

<h2>Relationship to the Latin Clavicula</h2>
<p>The precise relationship between the Hebrew <em>Mafteah Shelomoh</em> and the Latin <em>Clavicula Salomonis</em> tradition is one of the unresolved questions of Solomonic textual scholarship. Several possibilities have been proposed: the Hebrew text preceded the Latin and the Latin tradition represents a Christian adaptation; the Hebrew text derived from Latin or Greek sources; or both derive independently from a common earlier (possibly Greek or Aramaic) tradition. The manuscripts share ritual categories — conjurations, pentacles, spirit hierarchies, ritual preparation requirements — but differ in specific content, formulary, and organizational structure in ways that suggest neither is simply a translation of the other.</p>
<p>Gollancz's 1914 edition, based on the Or. 14759 manuscript, was the first critical edition of any Hebrew recension and established the scholarly framework for discussing the Hebrew tradition. Joseph Peterson's online edition and commentary have extended this work using additional manuscripts. Gideon Bohak's analysis of the relationship between the Hebrew Solomonic tradition and the broader Jewish magical corpus provides essential context. Pablo Torijano's comparative approach in <em>Solomon the Esoteric King</em> (2002) situates the Hebrew Key of Solomon within the long development of Solomonic magical authority across religious traditions.</p>""",

"magia_naturalis": """<h2>Overview</h2>
<p>Giovanni Battista della Porta's <em>Magia naturalis</em> (Natural Magic) was first published in Naples in 1558 in four books and expanded to twenty books in 1589, becoming one of the best-selling books of the sixteenth century and the most widely read Renaissance definition of natural magic as a respectable intellectual enterprise. Translated into Italian, French, Dutch, English, and German, the work popularized the concept of natural magic as applied natural philosophy: the study and exploitation of the hidden properties of things, the effects of celestial influence, and the secrets of nature that ordinary observation misses.</p>

<h2>Contents and Definition</h2>
<p>Della Porta defines natural magic in the preface as the practical summit of natural philosophy — the discipline that, having understood nature's hidden causes, puts that knowledge to work in producing remarkable effects. The twenty-book expansion covers an extraordinary range: sympathies and antipathies among things, the production of new plant varieties, the preparation of cosmetics and perfumes, pyrotechnics, the magnet and its properties, optical instruments (including the camera obscura, which della Porta may have invented or developed independently), hydraulics, pneumatics, the transmutation of metals, fishing and fowling, and remedies against poisons. The work is remarkable for its mixture of genuine natural observation, received Aristotelian and Neoplatonic theory, and outright legend, all presented in the same confident empirical tone.</p>

<h2>Significance</h2>
<p>Della Porta's <em>Magia naturalis</em> is significant for several reasons. First, it demonstrates the enormous popular appetite for natural philosophical knowledge in the sixteenth century: the book's repeated editions and translations show that a lay readership existed for serious — if often credulous — natural philosophy. Second, it represents the most explicit attempt in the Renaissance to legitimate natural magic by severing it from demonic operation: della Porta consistently frames his procedures as natural and empirical. Third, the work's camera obscura description and its discussion of optical instruments connects it to the history of early modern experimental science, illustrating the overlap between natural magic and what would become experiment-based natural philosophy.</p>""",

"opus_majus": """<h2>Overview</h2>
<p>Roger Bacon's <em>Opus maius</em> (Great Work, c.1267), composed at the request of Pope Clement IV and sent to him in three copies, is the most ambitious and original work of Latin natural philosophy in the thirteenth century — a comprehensive programme for the reform of Christian learning through mathematics, languages, optics, moral philosophy, and experimental science. The work is not a treatise on magic, but it contains the most sophisticated account of the relationship between natural philosophy and magical causation produced in the medieval period, and its concept of <em>scientia experimentalis</em> (experimental science) overlaps substantially with the project of natural magic.</p>

<h2>Structure</h2>
<p>The <em>Opus maius</em> is organized in seven parts. Part I attacks the four "offendicula" (obstacles) to wisdom: deference to authority, habit, popular prejudice, and concealment of ignorance behind a show of learning. Part II argues for the necessity of linguistic knowledge (Latin, Greek, Hebrew, Arabic) for proper understanding of Scripture and natural philosophy. Part III covers mathematics as the foundation of all sciences. Part IV covers optics (perspectiva) — Bacon's most original scientific contribution, synthesizing Alhazen's <em>De aspectibus</em> with Aristotelian and Augustinian accounts of light. Part V applies mathematics and optics to geography and the configuration of the world. Part VI treats experimental science as the crown of philosophy and the key to producing marvellous practical effects. Part VII covers moral philosophy.</p>
<p>Part VI on experimental science is most important for the history of magic. Bacon argues that genuine knowledge of natural causes — particularly the multiplication of species (the mechanism by which all natural agents, including celestial bodies, transmit their qualities through a medium) — enables the philosopher to produce effects that are marvellous to the uninitiated but purely natural in their operation. He mentions the possibility of explosive mixtures, optical instruments producing distant vision, and mechanical devices, all as examples of what experimental science could achieve. The relationship between this programme and the project of natural magic is explicit and close.</p>""",

"secretum_secretorum": """<h2>Overview</h2>
<p>The <em>Secretum secretorum</em> (Secret of Secrets) is a pseudo-Aristotelian letter-treatise, purportedly written by Aristotle to his pupil Alexander the Great during the latter's campaigns, advising him on kingship, health, physiognomy, and various practical matters including astrology and the occult properties of stones and plants. Originally composed in Arabic (as the <em>Kitab sirr al-asrar</em> or <em>Sirr al-asrar</em>), it was translated into Latin by John of Seville (a partial translation, c.1120) and by Philip of Tripoli (a longer version, c.1220–1250), and became one of the most widely circulated texts in medieval Europe — surviving in over two hundred Latin manuscripts.</p>

<h2>Contents</h2>
<p>The text's contents are varied: advice to rulers on governance and personal conduct; a physiognomic section (reading character from physical features); an account of the proper diet, sleep, and exercise for maintaining health in different seasons; an astrological section on the influence of the stars and the proper timing of activities; and sections on the occult properties of stones, plants, and animals. The attribution to Aristotle gave all of these sections enormous authority: if Aristotle himself had validated astrology, physiognomy, and natural magic as legitimate arts, their status within the Aristotelian university curriculum was secured.</p>
<p>Roger Bacon edited and commented on the <em>Secretum secretorum</em> extensively — it was one of the works he considered most important for natural philosophy and for practical wisdom. His commentary treated the text as genuine Aristotle and drew on its astrological and physiognomic sections in his broader natural philosophical system. Don Skemer's work on medieval amulet texts and Sophie Page's on magical manuscripts both document the <em>Secretum secretorum</em>'s circulation in contexts that included magical material.</p>""",

"solomon_esoteric_king": """<h2>Overview</h2>
<p>Pablo Torijano's <em>Solomon the Esoteric King: From King to Magus, Development of a Tradition</em> (Brill, 2002) is the foundational scholarly study of how the biblical King Solomon was transformed across late antique and medieval sources into the supreme master of demons, angelic revelation, and occult knowledge, and of how this transformation operated across three religious traditions — Judaism, Christianity, and Islam — simultaneously. The book is the essential starting point for any serious engagement with the Solomonic magical tradition.</p>

<h2>Argument and Evidence</h2>
<p>Torijano's argument is that Solomonic esoteric authority was not a fixed body of tradition but a dynamic attribution strategy: the name "Solomon" carried an authority — royal, prophetic, divinely-gifted — that different communities in different periods attached to different textual traditions for legitimating purposes. The strategy was available across religious boundaries because all three traditions shared the biblical narrative of Solomon's divinely-granted wisdom, while differing in how they elaborated and applied it.</p>
<p>The book proceeds through four main areas of evidence. First, the Second Temple Jewish pseudepigraphic literature (Wisdom of Solomon, Psalms of Solomon, and related texts) that first established Solomon as a figure of cosmic wisdom and spiritual authority. Second, the <em>Testament of Solomon</em> and related texts (the Solomonic adjurations, the <em>Hygromanteia</em>) that developed the demonological dimension: Solomon as master of individual named demons. Third, the Islamic tradition of Sulayman as a prophet-king given power over jinn by divine command, and the Islamic magical texts that drew on Qurʾanic Solomonic traditions. Fourth, the Latin and Hebrew grimoire tradition (the <em>Clavicula Salomonis</em>, the <em>Mafteah Shelomoh</em>, the <em>Lemegeton</em>) as the medieval crystallization of Solomonic magical authority.</p>""",

"speculum_astronomiae": """<h2>Overview</h2>
<p>The <em>Speculum astronomiae</em> (Mirror of Astronomy), attributed to Albertus Magnus though the attribution has been contested (Nicolas Weill-Parot argues against it; most scholars accept it), is the most systematic scholastic treatment of the boundary between legitimate and illegitimate astrological magic composed in the thirteenth century. Probably written in the 1260s, the text was addressed to the growing number of natural philosophers who were encountering Arabic astrological image magic and needed guidance on which procedures were compatible with Christian orthodoxy and which were not.</p>

<h2>The Tripartite Classification</h2>
<p>The <em>Speculum</em>'s central contribution is a tripartite classification of astrological image-making. The first category — fully licit — comprises images that work through purely natural celestial causes: talismans whose figures, materials, and timing are keyed to the natural influences of specific planets, operating as material focal points for stellar power in the way that a burning glass concentrates light. The second category — potentially licit, depending on content — comprises images that may or may not involve demonic invocation: the key question is whether the text that accompanies the image explicitly addresses spiritual agents by name (thereby becoming "addressative" in Weill-Parot's terminology) or merely exploits natural stellar influence. The third category — clearly illicit — comprises images that explicitly invoke demonic names or require demonic cooperation: these are condemned without qualification.</p>
<p>This classification had significant consequences for subsequent natural philosophy and magic. It legitimated a domain of astrological talisman-making as natural philosophy, provided a framework for evaluating specific texts and procedures, and influenced later Renaissance defenders of natural magic (Ficino, Agrippa, della Porta) who sought to work within the licit category. It also identified the key diagnostic question — whether a magical procedure explicitly addresses spiritual agents — that Nicolas Weill-Parot's concept of addressative magic systematizes and applies to the broader history of medieval astrological image magic.</p>""",

"de_praestigiis_daemonum": """<h2>Overview</h2>
<p>Johann Weyer's <em>De praestigiis daemonum et incantationibus ac veneficiis</em> (On the Tricks of Demons and on Incantations and Poisons, Basel, 1563) is one of the most important books in the history of early modern witchcraft theory: a sustained argument by a physician and humanist scholar that the women accused of witchcraft in the trials of his time were not genuine witches exercising real demonic power but mentally disturbed, elderly, or impoverished persons whose confessions were products of delusion, suggestion, or coercion. The book was the first sustained critique of witch-trial practice by a learned professional with access to medical and theological arguments.</p>

<h2>Weyer's Argument</h2>
<p>Weyer accepted the standard scholastic demonology: demons were real, fallen angels with genuine but limited causal powers. His innovation was to separate this demonological orthodoxy from the specific claim that the accused women in witch trials were genuine witches exercising demonic power. Weyer argued that demons certainly existed and sometimes deceived people, but that the old women who confessed to flying to sabbaths, having intercourse with the Devil, and causing harm through maleficia were being deceived by demons (who implanted false memories and delusions) or were suffering from natural melancholic conditions that produced hallucinations. The appropriate response was not execution but medical treatment and pastoral care.</p>

<h2>The Pseudomonarchia Daemonum</h2>
<p>Appended to Weyer's <em>De praestigiis</em> is the <em>Pseudomonarchia Daemonum</em> (False Monarchy of Demons), a spirit catalogue listing sixty-nine named demons with their ranks, powers, and characteristics. Weyer presented this as evidence of demonic deception — the catalogue demonstrates how demons claim to be kings and princes — but it became, in practice, a primary source for subsequent spirit catalogues. The <em>Ars Goetia</em> of the <em>Lemegeton</em> is directly related to the <em>Pseudomonarchia</em>, expanding its sixty-nine spirits to seventy-two and adding individual seals. Weyer's sceptical treatise thus paradoxically became a source for the demonic conjuration tradition it was intended to refute.</p>""",

"discoverie_of_witchcraft": """<h2>Overview</h2>
<p>Reginald Scot's <em>The Discoverie of Witchcraft</em> (London, 1584) is the most comprehensive Elizabethan treatment of witchcraft and magic, combining a sceptical argument against witch trials with an extensive documentation of magical practices — conjuration, exorcism, popular charms, and learned ritual magic — that makes the book an indispensable primary source for Elizabethan magical culture. Scot, a Kentish justice of the peace with no formal theological or philosophical training, assembled an impressive range of sources to argue that the witch trials were unjust and that the magical beliefs underlying them were superstition.</p>

<h2>The Sceptical Argument</h2>
<p>Scot's argument against witch trials rests on several connected claims: that the physical effects attributed to witches (flying, transformation, causing disease) are physically impossible and contradict natural philosophy; that the confessions of accused witches are products of delusion, senility, mental illness, or torture rather than genuine evidence; that the scriptural basis for witchcraft prosecution has been misinterpreted (the Witch of Endor was a ventriloquist, not a genuine necromancer); and that the accused women are typically poor, old, and marginalized persons who deserve pity rather than prosecution. The humanitarian impulse running through the book is genuine and historically significant.</p>

<h2>The Magical Content</h2>
<p>Books XV and XVI of the <em>Discoverie</em> present a different kind of document: extensive transcriptions of conjuration rituals, exorcism procedures, and magical formulas, apparently reproduced to show that learned magic is as fraudulent as witchcraft — but in practice constituting one of the most detailed accounts of Elizabethan learned magic available. The conjuration rituals are related to those in the <em>Heptameron</em> and the Solomonic tradition; the exorcism procedures are both ecclesiastical (based on Catholic rites Scot deplored) and popular. James VI of Scotland attacked the book in his <em>Daemonologie</em> (1597); subsequent English dramatists including Marlowe and Shakespeare drew on it for magical material.</p>""",

}


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    updated = 0
    for slug, html in CONCEPT_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM concepts WHERE slug=?", (slug,)).fetchone()
        if row:
            conn.execute("UPDATE concepts SET definition_long=? WHERE slug=?", (html, slug))
            print(f"  concept: {slug} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING concept: {slug}")

    for pid, html in PERSON_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM persons WHERE person_id=?", (pid,)).fetchone()
        if row:
            conn.execute("UPDATE persons SET bio_html=? WHERE person_id=?", (html, pid))
            print(f"  person: {pid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING person: {pid}")

    for tid, html in TEXT_ENRICHMENTS.items():
        if not html:
            continue
        row = conn.execute("SELECT id FROM texts WHERE text_id=?", (tid,)).fetchone()
        if row:
            conn.execute("UPDATE texts SET analysis_html=? WHERE text_id=?", (html, tid))
            print(f"  text: {tid} ({len(html)} chars)")
            updated += 1
        else:
            print(f"  MISSING text: {tid}")

    conn.commit()
    print(f"\nUpdated {updated} entries.")
    conn.close()


if __name__ == "__main__":
    main()
